### PR TITLE
Release v2.0.18 with ESP-IDF v4.4.8

### LINKED ISSUE #7729: support for arm64-apple-macosx13.0.0 binaries
### Related area

toolchain support on aarch64 macos hosts

### Hardware specification

XIAO ESP32C3

### Is your feature request related to a problem?

refiling the issue I filed at: https://github.com/espressif/crosstool-NG/issues/39:

See also https://github.com/arduino/arduino-ide/issues/1818 and https://forum.arduino.cc/t/one-mac-sees-my-arduinos-the-other-doesnt/1076201/20. I'm on macos on apple silicon. Following https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/, I'm using https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json. Grepping the json for apple, I see cross compilers provided for x86_64-apple-darwin but not any of the apple silicon targets, which are aarch64 based.

This can result in the Arduino IDE swallowing errors since it can't run the utilities from the command line if rosetta is not installed.

### Describe the solution you'd like

I guess https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json should have entries for aarch64 macos host triples? @Jason2866 claims they exist, but perhaps the json needs to describe that they do?

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

### PR DESCRIPTION
**Pull request by me-no-dev**
Fixes #7729

### CODE REVIEW

**Comment by VojtechBartoska** [comment]
@me-no-dev is https://github.com/espressif/arduino-esp32/issues/7729 covered in this PR?

**Comment by mrengineer7777** [comment]
@me-no-dev 2.0.7 was released.  What does this PR do?

**Comment by Jason2866** [comment]
@me-no-dev Still open?

**Comment by me-no-dev** [comment]
@Jason2866 we keep it here for the CI ;)

**Pull request closed without merging**
