### PR TITLE
[CI] Add to Boards Test check if build.board is uppercase

### PR DESCRIPTION
**Pull request by P-R-O-C-H-Y**
## Description of Change
Added automated check if boards_name.build.board is uppercase.

## Tests scenarios
Tested locally

## Related links
#7942

### CODE REVIEW

**Review by SuGlider — APPROVED** [review]
Nice check!

**Comment by SuGlider** [comment]
I found a board with '-' symbol too
`ttgo-t-oi-plus.build.board=TTGO-T-OI-PLUS_DEV`

**Comment by P-R-O-C-H-Y** [comment]
> I found a board with '-' symbol too `ttgo-t-oi-plus.build.board=TTGO-T-OI-PLUS_DEV`

I see but almost all boards use only uppercase chars + numbers + _ 
I think we should just stick to it and don't allow any other symbols.

**Comment by P-R-O-C-H-Y** [comment]
> Will we change all board to upper case?

For keeping compatibility we will leave old boards as is and only check this for new incoming boards.
Probably will change only some Heltec boards which were causing some issue. Need to double check it first.

**Pull request merged**
