### PR TITLE
Add support for new unphone boards

### PR DESCRIPTION
**Pull request by garethhcoleman**
First time doing this - please advise if any changes or clarification needed thanks!

## Description of Change
Please describe your proposed Pull Request and it's impact.
Adds two new boards, the unPhone spin 8 and spin 9 to boards.txt and variants/unphone8 and variants/unphone9

## Tests scenarios
Please describe on what Hardware and Software combinations you have tested this Pull Request and how.
Tested on our prototype hardware with a variety of test sketches, pin assignments seem correct.

## Related links
Hardware description at [unphone.net](https://unphone.net/the-unphone/) and software at https://gitlab.com/hamishcunningham/unphone

### CODE REVIEW

**Comment by SuGlider** [comment]
@garethhcoleman - Please sign the CLA in order to move formward

**Comment by garethhcoleman** [comment]
@SuGlider thanks for prompt - I didn't realise that!

I will ask my collaborator to also sign.

Thanks again!

**Comment by SuGlider** [comment]
@hamishcunningham - Please sign the CLA in order to move forward

**Comment by SuGlider** [comment]
@garethhcoleman @hamishcunningham 

It seems that there are some conflicts when merging `boards.txt` file because other vendors have already made their changes and those are already merged into the master branch. I think you may need to "rebase" your local repository and pull latest master branch from ESP32 in order to get the last version of `boards.txt` and just add your board entries at the end.

When done commit the changes and we will merge it to main master branch.

**Pull request merged**
