### PR TITLE
add DFRobot FireBeetle-ESP32 support

### PR DESCRIPTION
**Pull request by ouki-wang**
Please add DFRobot FireBeetle-ESP32 support, thanks

### CODE REVIEW

**Comment by arcao** [comment]
Please change board id from `esp32` to `firebeetle32` and add `variants/<board_id>/pins_arduino.h` header file for that board.

**Comment by me-no-dev** [comment]
@ouki-wang will you do the changes that @arcao mentioned? I can not accept this PR as-is

**Comment by ouki-wang** [comment]
@me-no-dev i have add variants for esp32 and modify build.variant . Thanks for arcao's help

**Comment by arcao** [comment]
@ouki-wang Please change the board_id from `esp32` it `firebeetle32`.

I mean your boards.txt changes should be:
```text
firebeetle32.name=FireBeetle-ESP32

firebeetle32.upload.tool=esptool
firebeetle32.upload.maximum_size=1044464
firebeetle32.upload.maximum_data_size=294912
firebeetle32.upload.wait_for_upload_port=true

...etc...
```

**Pull request merged**
