### PR TITLE
Updated preferences and FAQ documentation (added SPIFFS)

### PR DESCRIPTION
**Pull request by PilnyTomas**
**Preferences:**
A large block of code had lines beyond the visible edge and the reader was forced to scroll down to reach the vertical scroller, scroll up, see the hidden portion, then back down to scroll left and return to reading - this is unacceptable. I have folded those lines. Smaller blocks of code were left unchanged even when the code reached beyond the edge.
code comment

**FAQ:**
Added note about SPIFFS mount failed - based on "for reference" issue #638

### CODE REVIEW

**Comment by VojtechBartoska** [comment]
@PilnyTomas good point, have notice this as well. Can you please rename PR name to something meaningful? Less generic. For example, "Format Update of codes blocks rendering in Documentation" or something similar. Thanks

**Review by pedrominatel — APPROVED** [review]
LGTM, thanks!

**Comment by pedrominatel** [comment]
Is there any way to check this automatically before merging? CI/Action?

**Comment by PilnyTomas** [comment]
> Is there any way to check this automatically before merging? CI/Action?

Maybe just make sure that code blocks don't exceed a certain length per line...

**Pull request merged**
