### PR TITLE
Fixed "Invalid mbox" error in SimpleTime example

### PR DESCRIPTION
**Pull request by kinoh**
## Description of Change

As stated in https://github.com/espressif/arduino-esp32/issues/8661, we have to call `WiFi.mode` before networking.

## Tests scenarios

I've tested my Pull Request on arduino-esp32 v2.0.14 with ESP32-DevKitC-32E Board.

## Related links

- https://github.com/espressif/arduino-esp32/issues/8661

### CODE REVIEW

**Comment by SuGlider** [comment]
@me-no-dev - This should also be merged to the `release/v2.x` branch.

**Review by lucasssvaz — APPROVED** [review]

**Comment by P-R-O-C-H-Y** [comment]
@SuGlider is it ok now to call Wifi.begin() twice?

**Comment by SuGlider** [comment]
> @SuGlider is it ok now to call `Wifi.begin()` twice in the example?

You are right, it is also called latter. I must call it at first and then use IDF calls.

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Comment by vortigont** [comment]
Does mentioned issue (invalid mbox) really affects this ntp example? It is related to TCP socket, but NTP does not use TCP at all.
What this change is definitely breaks is NTPoDHCP feature, because dhcp client option should be set _before_ acquiring IP address as stated in comment below.

https://github.com/espressif/arduino-esp32/blob/50ef6f4369fb85139f000f7bbc5a9f9d5bc02b9f/libraries/ESP32/examples/Time/SimpleTime/SimpleTime.ino#L45-L53

**Pull request merged**
