### PR TITLE
Add Ticker library

### PR DESCRIPTION
**Pull request by bertmelis**
see #30

### CODE REVIEW

**Comment by bertmelis** [comment]
Hmm, Travis fail because of LED_BUILTIN isn't defined.

**Comment by bertmelis** [comment]
Travis Fixed 😃

**Comment by me-no-dev** [comment]
cool :) Thanks for the contribution! Ticker has been requested for a while

**Comment by gjt211** [comment]
@bertmelis, @me-no-dev 

This is not working for me.
Just updated the core files, the Ticker library folder and examples are there but they won't compile.
Always get ```fatal error: Ticker.h: No such file or directory```
I have restarted the Arduino IDE a few times as well.
Am I doing something wrong?

**Comment by gjt211** [comment]
@bertmelis, @me-no-dev 

Sorry, I renamed the old code library folder but left it in the same place.
```
/hardware/espressif/esp32
/hardware/espressif/esp32_old
```
I moved the esp32_old folder outside of the Arduino/hardware folder, restarted the IDE and now it compiles.

**Pull request merged**
