### PR TITLE
Create lionbit board.

### PR DESCRIPTION
**Pull request by niwantha33**
## Summary
Arduino pin definition of Lion:Bit  Dev Board (https://lionbit.lk)

## Impact
In order to use this dev board in all the available platform. 

## Related links
https://github.com/LionBit-Sri-Lanka/lionbit_dev_board

### CODE REVIEW

**Comment by me-no-dev** [comment]
Hi @niwantha33 :) Because of recent commit that changed boards.txt quite a bit, there is now a conflict with your changes. Please redo the PR or fix the conflicts :)

**Comment by niwantha33** [comment]
> Hi @niwantha33 :) Because of recent commit that changed boards.txt quite a bit, there is now a conflict with your changes. Please redo the PR or fix the conflicts :)

Hi. Thanks,I have fixed the issue. please check again.

**Comment by me-no-dev** [comment]
You can still see there is a conflict. Easiest solution is to copy your changes, update your fork to the latest master and create the PR again.

Screenshot 2022-01-18 at 12 40 55

**Comment by niwantha33** [comment]
> https://github.com/LionBit-Sri-Lanka/lionbit_dev_board

Thank you for the assitances.

**Comment by niwantha33** [comment]
Create New PR niwantha33:patch-3 close #6144.

**Pull request closed without merging**
