### PR TITLE
ESP32-S3 PowerFeather Support for v2.x

### PR DESCRIPTION
**Pull request by powerfeatherdev**
Cherry-picked commits from #8889 and #9052, but for release/v2.x.

### CODE REVIEW

**Comment by powerfeatherdev** [comment]
Hello @P-R-O-C-H-Y, in https://github.com/espressif/arduino-esp32/pull/8889#discussion_r1401878889 you mentioned that these definitions are no longer necessary. I thought it was only for v3, but is it also the case for v2 (since apparently all checks have passed?).

**Comment by P-R-O-C-H-Y** [comment]
> Hello @P-R-O-C-H-Y, in https://github.com/espressif/arduino-esp32/pull/8889#discussion_r1401878889 you mentioned that these definitions are no longer necessary. I thought it was only for v3, but is it also the case for v2 (since apparently all checks have passed)?

Hello @powerfeatherdev, our core is not using those definitions anywhere, so as you said all check passed without that. But there are lot of 3rd party libraries and examples which may use those definitions. So if they are not defined for the board, the user may get in trouble :)

**Comment by powerfeatherdev** [comment]
@P-R-O-C-H-Y Thanks for the clarification.

**Comment by powerfeatherdev** [comment]
@SuGlider @me-no-dev @P-R-O-C-H-Y Please take a look.

**Review by P-R-O-C-H-Y — APPROVED** [review]
Looks good :)

**Pull request merged**
