### PR TITLE
Update boards.txt for Onehorse's ESP32 Dev Module

### PR DESCRIPTION
**Pull request by arcao**
See #334.

### CODE REVIEW

**Comment by me-no-dev** [comment]
DOUT? ughhh...

**Comment by arcao** [comment]
It's PR only, I used info for `variant.h` from Tindie: https://www.tindie.com/products/onehorse/esp32-development-board/

**Comment by me-no-dev** [comment]
Please do not do it again ;) if you want to add something to the repo, test it first! I expect that to be the case with every PR.

**Comment by arcao** [comment]
Sorry.

**Pull request merged**
