### PR TITLE
 Implement official Arduino IDE debugger API on 2.x 

### PR DESCRIPTION
**Pull request by pillo79**
This PR replaces the current experimental sketch debugging description with a full implementation according to the finalized [Arduino Platform Debug Specification](https://arduino.github.io/arduino-cli/latest/platform-specification/#sketch-debugging-configuration). It is a backport of #9116 to the `release/v2.x` branch.

### CODE REVIEW

**Comment by pillo79** [comment]
While testing this we found an issue with Cortex-Debug. It seems that some global symbols that are defined in core 2.x cause the plugin to crash when opening the "globals" sidebar. Since this feature was not present until now, I have disabled it in bca404dbc71972b20b2dc3986f44ddb10c7fa463.
Otherwise, all tests OK on our side so marking this ready for review/merge.

**Comment by me-no-dev** [comment]
@pillo79 is it now supported by the latest released IDE?

**Comment by pillo79** [comment]
Not yet - IDE 2.6.0 is currently scheduled to be released by mid next week.

**Comment by me-no-dev** [comment]
@pillo79 OK. let's merge it when it's released. LGTM

**Comment by pillo79** [comment]
IDE 2.3 has been [released](https://blog.arduino.cc/2024/02/07/ide-2-3-is-out-and-youll-love-the-new-debugging-features-in-it/) yesterday :+1:

**Pull request merged**
