### PR TITLE
Replace the libesp32-camera.a file fix the issue with ov2640 camera driver

### PR DESCRIPTION
**Pull request by nqh2412**
Newly compiled esp32-camera driver from https://github.com/espressif/esp32-camera

### CODE REVIEW

**Comment by me-no-dev** [comment]
did you compile the very latest camera lib? it has 270K difference

**Comment by nqh2412** [comment]
Yes. It is the latest version of the esp32-camera. 
It was compiled with esp-idf

**Comment by me-no-dev** [comment]
latest ESP-IDF with the latest toolchain esp-2021r1?

**Comment by me-no-dev** [comment]
I wonder why there is such big size difference...

**Pull request merged**
