### PR TITLE
Examples update, add a note for configTime()

### PR DESCRIPTION
**Pull request by vortigont**
lwip lib bundled with esp32 Arduino supports only one ntp server. Any additional servers set are just silently ignored.
This default is different from esp8266 Arduino core and very confusing. Most of the examples provided uses 3 different ntp servers for redundancy while only the first one is used actually.
Addressing issue #4964

### CODE REVIEW

**Comment by me-no-dev** [comment]
Hi @vortigont :) Thanks for taking the time! LITTLEFS was recently renamed to LittleFS. Could you please adjust your pull request?

**Comment by vortigont** [comment]
@me-no-dev merged with recent master changes. Tnx for the hint.
I was thinking that maybe lwip build defines should be changed to match esp8266? So that by default all 3 ntp servers options could be used? esp8266 Arduino core bundle contains several versions of lwip, like full-featured, small-mss, IPv6. But esp2 offers only one version, and rebuilding your own version doesn't look that easy for everyone's. So, maybe it would be better to match the defauls? I can prepare a PR for the build-scripts changes instead of this PR. How do you think?

**Comment by me-no-dev** [comment]
@vortigont if this is an IDF menuconfig option, then change should be added in the [lib-builder](https://github.com/espressif/esp32-arduino-lib-builder) sdkconfigs, which will then propagate to arduino the next time that IDF has some updates for us :)

**Comment by vortigont** [comment]
OK, then I will check for lib-builder's defines and make a PR, then you can choose between this PR or lwip fix :)
Tnx!

**Comment by vortigont** [comment]
@me-no-dev looks like lib-builder won't help here since esp-idf's lwip [Kconfig](https://github.com/espressif/esp-idf/blob/master/components/lwip/Kconfig) and [lwipopts.h](https://github.com/espressif/esp-idf/blob/master/components/lwip/port/esp32/include/lwipopts.h) doesn't have proper defines to adjust SNTP_MAX_SERVERS at build time. 
Would appreciate if this PR for examples could be accepted, meanwhile I'll try to prepare PR for esp-idf to implement required menuconfig option and maybe someday we could get back to lib-builder's default override for arduino-esp32
Tnx!

**Comment by me-no-dev** [comment]
Merged @vortigont thanks!

**Pull request merged**
