### PR TITLE
Added UM FeatherS2 Neo to boards.txt and variants folder

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
As title states, just adding my newest FeatherS2 Neo board to the boards list with the appropriate variants folder.

### CODE REVIEW

**Comment by me-no-dev** [comment]
@UnexpectedMaker can you sign the cla please?

**Comment by UnexpectedMaker** [comment]
> @UnexpectedMaker can you sign the cla please?

I just signed it...   but I'm sure I have done that already.
Maybe it was for the ESP-IDF? Do I need to sign per repo? I thought it would have been for the GitHub org.

**Comment by me-no-dev** [comment]
it's per repo :) you just made the 2.0.0 release

**Comment by UnexpectedMaker** [comment]
> it's per repo :) you just made the 2.0.0 release

Ahh, that makes sense then!

Yes, I know, thanks heaps for merging it!!!! How exciting....  It's been a long journey to get 2.0.0 out, congrats to you and the team!

**Pull request merged**
