### PR TITLE
Add submodule of Azure IoT library

### PR DESCRIPTION
**Pull request by lirenhe**
This library is a port of the Microsoft Azure IoT device SDK for C to Arduino for esp32 devices. It allows user to use several Arduino compatible ESP32 boards with Azure IoT Hub.

### CODE REVIEW

**Comment by me-no-dev** [comment]
@lirenhe there is an error while building the example. Can you please check? https://travis-ci.org/espressif/arduino-esp32/builds/385585599?utm_source=github_status&utm_medium=notification

**Comment by lirenhe** [comment]
The build issue is fixed. Thanks

**Comment by me-no-dev** [comment]
@lirenhe thanks! merged :)

**Comment by sieren** [comment]
Any plans on updating this? There's a compiler error with the most recent toolchains using cmake / IDF. See my PR here: https://github.com/VSChina/ESP32_AzureIoT_Arduino/pull/15

**Pull request merged**
