### PR TITLE
Add new UM TinyC6 board and re-ordered UM boards in boards.txt file.

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
## Description of Change
Added Unexpected Maker TinyC6 development board to the boards list.
Renamed and re-ordered all UM boards in boards.txt to make them more identifiable. 

## Tests scenarios
I've tested this on my TinyC6, and it's working as expected.

@me-no-dev Can you please tag this for 3.0.0? I'm not quite sure how this all works when doing a PR for a tag.

### CODE REVIEW

**Comment by me-no-dev** [comment]
@UnexpectedMaker everything is 3.0.0 now :) @P-R-O-C-H-Y PTAL

**Comment by UnexpectedMaker** [comment]
> @UnexpectedMaker everything is 3.0.0 now :) @P-R-O-C-H-Y PTAL

Oh! That's even better - wicked!
Now I have to get my other new S3 boards ready for a PR as well.

**Review by P-R-O-C-H-Y — APPROVED** [review]
Looks good :)

**Comment by UnexpectedMaker** [comment]
Thanks @me-no-dev :)

**Pull request merged**
