### PR TITLE
Update RMT initialization code

### PR DESCRIPTION
**Pull request by diplfranzhoepfinger**
- Commented out setting interrupt priority for both TX and RX configurations in the RMT initialization code.

otherwise we get an Compile Error with esp-idf 5.1.1

### CODE REVIEW

**Comment by me-no-dev** [comment]
and you break it for anyone on 5.1.2. Proper fix would be to check the ESP-IDF version

**Comment by Jason2866** [comment]
why should be an outdated IDF version be supported?

**Comment by diplfranzhoepfinger** [comment]
Cool.
https://github.com/espressif/esp-idf/releases/tag/v5.1.2
5.1.2 is here.

**Comment by SuGlider** [comment]
@diplfranzhoepfinger - I changed your PR to include the IDF 5.1.x version check...

**Comment by SuGlider** [comment]
It could be useful when using Arduino as IDF component with any IDF 5.1.x version.

**Comment by diplfranzhoepfinger** [comment]
Cool done.

**Review by lucasssvaz — APPROVED** [review]

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Pull request merged**
