### PR TITLE
fix(littlefs): Use VFSImpl::exists() to avoid false error log

### LINKED ISSUE #7615: LittleFS.exists() is giving an error
### Board

ESP32-S3

### Device Description

ESP32-S3 16MB Dev-Kit

### Hardware Configuration

Nothing

### Version

v2.0.5

### IDE Name

Arduino IDE 2.0.4

### Operating System

Windows 10

### Flash frequency

240MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

I am using the LittleFS library.
When I try to check if a file exists, this function is executed:
https://github.com/espressif/arduino-esp32/blob/bb8c8559b62a0d2e888d51bf12bd50cc070f0b4b/libraries/LittleFS/src/LittleFS.cpp#L46
```
bool LittleFSImpl::exists(const char* path)
{
    File f = open(path, "r",false);
    return (f == true);
}
```

As it try to open a file, I get this error:
[E][vfs_api.cpp:104] open(): /littlefs/g00000/c001 does not exist, no permits for creation

From this line:
https://github.com/espressif/arduino-esp32/blob/bb8c8559b62a0d2e888d51bf12bd50cc070f0b4b/libraries/FS/src/vfs_api.cpp#L105

I think this error should not be logged, if we just check if a file exists.

### Sketch

```cpp
char path[20];
createPath(path);  
if(!LittleFS.exists(path))
{
  LittleFS.mkdir(path);
}
```

### Debug Message

```plain
[E][vfs_api.cpp:104] open(): /littlefs/g00000/c001 does not exist, no permits for creation
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by BlueAndi**
## Description of Change
Use exists() from VFSImpl base class and avoid using open() to check whether the file exists, because open() will log an error in case a file doesn't exists which is confusing, but might be relevant in case a developer uses open() directly and expects that the file is there.

## Related links
Closes #7615

### CODE REVIEW

**Comment by me-no-dev** [comment]
I think the proper action here would be to make the error a warning or even debug.

**Comment by BlueAndi** [comment]
> I think the proper action here would be to make the error a warning or even debug.

This could be done additional. But I would not expext any log by using exists.

**Comment by me-no-dev** [comment]
If you remove the method, then `exists` will stop functioning correctly. The log is there to let you know that the file was not found and will not be created. If the log is the issue, then that is where it should be fixed.

**Comment by me-no-dev** [comment]
I do not recall, because LittleFS was not implemented by us, but I see it being implemented much the same for the other file systems. Issue here seems the same as https://github.com/espressif/arduino-esp32/issues/6749 though for FFat. @lbernstone do you recall why FFat needs to open the file to check if it exists? If the issue is the error log, I do agree that it's a bit to much to issue an error, where a warning or even debug will suffice for the cases where one will need to get more information.

**Comment by BlueAndi** [comment]
> If you remove the method, then `exists` will stop functioning correctly.

Didn't realize this in my tests. Whats exactly is the problem by using base class exists method?

**Comment by me-no-dev** [comment]
@lucasssvaz can you please test this same solution with LittleFS, FFat and SPIFFS?

**Comment by ioviedodev** [comment]
I experiment the same issue in arduino esp32 version 3.0.4 as component idf with version 5.1.4

**Comment by aeljandro2** [comment]
Same here. Been struggling with the and then realized is just a log thing "Seems". Anyway I think supporting littleFS is kinda important.

**Comment by lucasssvaz** [comment]
@me-no-dev Tested for LittleFS, SPIFFS and FFat. This solution works for LittleFS and FFat. For SPIFFS this error does not appear and when trying this solution it causes `exists()` to always return true.

**Review by lucasssvaz — APPROVED** [review]

**Review by me-no-dev — APPROVED** [review]

**Comment by GeorgeIoak** [comment]
I have a situation where I'm not able to update the library yet so I was trying to implement a code fix to directly use `VFSImpl::exists()` in place of `fs->exists()` which currently throws the error. I've made several attempt at implementing it but it's always returning false even if the file exists. This is what I had to do to get it to compile so I'm thinking I've botched this up and perhaps someone can help fix it who knows better.

```
bool IHPFirmware::doesFirmwareFileExist() {
    VFSImpl* vfsImpl = reinterpret_cast<VFSImpl*>(this->deps.fs);
    return vfsImpl->VFSImpl::exists(this->firmwarePath);
}
```

I confirmed that I'm passing the same path as I was using with `fs->exists()`

Sorry for asking here but I wasn't sure where else would be appropriate to ask

**Pull request merged**
