### PR TITLE
docs(contrib): Add instructions on how to test changes

### LINKED ISSUE #10185: Add developer contributor guidelines to build and test our PR locally
### Board

N/A

### Device Description

N/A

### Hardware Configuration

N/A

### Version

latest master (checkout manually)

### IDE Name

na

### Operating System

na

### Flash frequency

na

### PSRAM enabled

yes

### Upload speed

na

### Description

Hello,

I am preparing a PR to contribute middleware support (aka Expressif) to WebServer, plus some examples and middleware implementations (cors, security, logging). 

I didn't find any guidelines explaining the process to compile our changes and test the examples we write on a real board before submitting the PR.

Right now, I work around that by adding some platformio.ini files and using PIO to build the examples, but this is quite a hack.

What contributors should do to locally test and run the examples we write against the modifications we did ?

Thanks :-)

### Sketch

```cpp
na
```

### Debug Message

```plain
na
```

### Other Steps to Reproduce

na

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by lucasssvaz**
## Description of Change

Add instructions on how to create and run tests.
Fix formatting.

## Tests scenarios

Built locally

## Related links

Closes #10185

### CODE REVIEW

**Comment by lucasssvaz** [comment]
@Jason2866 @mathieucarbou PTAL.
Any feedback is welcome

**Comment by mathieucarbou** [comment]
> @Jason2866 @mathieucarbou PTAL. Any feedback is welcome

Thank you I will go though the doc when I will be back from vacation and try it for my PR https://github.com/espressif/arduino-esp32/pull/10186

**Comment by Jason2866** [comment]
Thank you. Exactly what i wanted to know. Will try some ;-) Feedback follows. Will need some days ;-)

**Comment by VojtechBartoska** [comment]
looks really nice @lucasssvaz!

**Review by P-R-O-C-H-Y — APPROVED** [review]
LGTM

**Review by pedrominatel — APPROVED** [review]
LGTM

**Comment by me-no-dev** [comment]
@lucasssvaz typo: https://github.com/espressif/arduino-esp32/actions/runs/10736557292/job/29776228500?pr=10221#step:8:25

**Pull request merged**
