### PR TITLE
BLE5 features to use with C3/S3

### PR DESCRIPTION
**Pull request by chegewara**
Added new BLE5 features to use on C3/S3 family:
- extended scan,
- extended/multi advertising

New code is not fancy (no feedback from events), but i think it is functional. To get feedback from events i am suggesting to use custom GAP callback, which is already implemented in BLEDevice.

### CODE REVIEW

**Comment by chegewara** [comment]
@me-no-dev Should i skip examples for esp32s2 and c3?

**Comment by h2zero** [comment]
Looks nice, wish I had a C3 to test it out with 😢

**Comment by chegewara** [comment]
@h2zero  Please contact me, and i can send you one.

**Comment by h2zero** [comment]
That would be amazing! I will be in touch, thanks.

**Pull request closed without merging**
