### PR TITLE
Rename variants/heltec_wifi_kit_32_V3 to match entry in boards.txt.

### PR DESCRIPTION
**Pull request by audiophyl**
-----------
## Description of Change
Rename the variant folder for heltec_wifi_kit_32_V3 board to match the contents of boards.txt

## Tests scenarios
I have tested my Pull Request on Arduino-esp32 core v2.0.14 with the heltec_wifi_kit_32_V3 board.

## Related links
N/A

### CODE REVIEW

**Comment by me-no-dev** [comment]
@P-R-O-C-H-Y PTAL

**Review by P-R-O-C-H-Y — APPROVED** [review]
LGTM, Thanks for fixing that.

**Comment by P-R-O-C-H-Y** [comment]
@me-no-dev The PR is targeting 2.X branch, but it needs to be fixed in master too.

**Comment by audiophyl** [comment]
This typo doesn't exist in master. I'm only aware of it as a result of installing 2.0.14 in Arduino IDE, and it seems this only impacts 2.x releases.

**Comment by P-R-O-C-H-Y** [comment]
@audiophyl Yes you are right. I probably didn't check the master properly. My bad.
@me-no-dev So no need to fix in master. This can be merged.

**Pull request merged**
