### PR TITLE
RainMaker - Add switch example using array

### PR DESCRIPTION
**Pull request by FernandoGarcia**
Hi!

I have spent some time searching for example with multiple switches using arrays but I couldn't find.

After some trouble  with compiling error I have managed to make it work with help of Arduino forum's user.

So I would like to add this example here to help other user to make a clean and easily editable code.

I have tested the code and it works as expected.

Best regards.

### CODE REVIEW

**Comment by pipi61** [comment]
Please add lots of comments

**Comment by FernandoGarcia** [comment]
Hi!

It's done.

Best regards.

**Comment by pipi61** [comment]
great, thanks

**Comment by VojtechBartoska** [comment]
Thanks for the contibution @FernandoGarcia, we'll review it soon.

**Comment by FernandoGarcia** [comment]
Hi!

There's an error in partition scheme in build check,

It should be `default,PartitionScheme=rainmaker`

```
Building Sketch Index 5 - BLE5_extended_scan
Building BLE5_extended_scan with arduino-cli and FQBN=espressif:esp32:esp32s3:PSRAM=opi,USBMode=default,PartitionScheme=huge_app
Error: The operation was canceled.
```

Best regards.

**Comment by sanketwadekar** [comment]
@FernandoGarcia
First of all, you have included `AceButton` library, which is not a part of this repo. Using third-party libraries in examples will cause issues for users who don't have them installed.
Secondly, Rainmaker examples are meant to introduce the different APIs and functionalities provided by the SDK. This example is basically an extension of the Switch example. In most cases, users start off with the Switch example and then continue to add their own devices and parameters in the sketch that suit their requirements (just as you might have done😄). Other than the number of switches, this example is no different from the existing Switch example.
Also, as I have mentioned [here](https://github.com/espressif/arduino-esp32/issues/7893#issuecomment-1453806397), using random output pins might cause issues that might go unnoticed.
For consistency, we create an example in the Rainmaker repo first and then replicate it in Arduino.

**Comment by FernandoGarcia** [comment]
> First of all, you have included AceButton library, which is not a part of this repo. Using third-party libraries in examples will cause issues for users who don't have them installed.

Can I specify library dependency in read me? We can find libraries with third part dependencies all time.

>Secondly, Rainmaker examples are meant to introduce the different APIs and functionalities provided by the SDK. This example is basically an extension of the Switch example. In most cases, users start off with the Switch example and then continue to add their own devices and parameters in the sketch that suit their requirements (just as you might have donesmile). Other than the number of switches, this example is no different from the existing Switch example.

Yes, but it's doesn't help beginners improve their skills because all code that I can find is like the code below including [RMakerSonoffDualR3](https://github.com/espressif/arduino-esp32/blob/master/libraries/RainMaker/examples/RMakerSonoffDualR3/RMakerSonoffDualR3.ino) example.

```
LightSwitch switch_ch1 = {gpio_switch1, false};
LightSwitch switch_ch2 = {gpio_switch2, false};
LightSwitch switch_ch3 = {gpio_switch3, false}
LightSwitch switch_ch4 = {gpio_switch4, false}
LightSwitch switch_ch5 = {gpio_switch5, false}
LightSwitch switch_ch6 = {gpio_switch6, false}
LightSwitch switch_ch7 = {gpio_switch7, false}

static Switch my_switch1;
static Switch my_switch2;
static Switch my_switch3;
static Switch my_switch4;
static Switch my_switch5;
static Switch my_switch6;
static Switch my_switch7;

void write_callback(Device *device, Param *param, const param_val_t val, void *priv_data, write_ctx_t *ctx)
{
  const char *device_name = device->getDeviceName();
  const char *param_name = param->getParamName();

  if(strcmp(device_name, "Switch_ch1") == 0) 
  {
  } 
  else if(strcmp(device_name, "Switch_ch2") == 0) 
  {
  }
  else if(strcmp(device_name, "Switch_ch3") == 0) 
  {
  }
  else if(strcmp(device_name, "Switch_ch4") == 0) 
  {
  }
  else if(strcmp(device_name, "Switch_ch5") == 0) 
  {
  }
  else if(strcmp(device_name, "Switch_ch6") == 0) 
  {
  }
  else if(strcmp(device_name, "Switch_ch7") == 0) 
  {
  }
}
```
>Also, as I have mentioned https://github.com/espressif/arduino-esp32/issues/7893#issuecomment-1453806397, using random output pins might cause issues that might go unnoticed.
For consistency, we create an example in the Rainmaker repo first and then replicate it in Arduino.

For this reason I'm talking with you about sanity check [here](https://github.com/espressif/arduino-esp32/issues/7893#issuecomment-1453928367).

**Comment by FernandoGarcia** [comment]
Regard library dependencies, I could add a YAML file  with the list of dependencies so the build check could do a git clone before try build.

**Comment by sanketwadekar** [comment]
@shahpiyushv Please take a look

**Comment by FernandoGarcia** [comment]
Hi @shahpiyushv  @sanketwadekar !

Any news?

Best regards.

**Comment by me-no-dev** [comment]
Because this example uses external library, CI will always fail. Please rewrite it to not require AceButton

**Comment by FernandoGarcia** [comment]
> Because this example uses external library, CI will always fail. Please rewrite it to not require AceButton

Hi!

Have you considered my suggestion above to use YML file to specify dependencies?

Best regards.

**Pull request closed without merging**
