### PR TITLE
Fix gen_insights_package.py missing on release

### PR DESCRIPTION
**Pull request by me-no-dev**
Fixes: https://github.com/espressif/arduino-esp32/issues/7649

### CODE REVIEW

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Review by SuGlider — CHANGES_REQUESTED** [review]
Testing Compiling Example from `ESP Insights` --> `MinimalDiagnostics.ino` + Arduino Core 2.0.6
Issue #7649 confirmed using IDE 1.8.15 :: got error message: 
`'C:\Users\espUser\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6/tools/gen_insights_package.exe' is not recognized as an internal or external command, operable program, or batch file`

Tried fixing it by copying `/tools/gen_esp32part.exe` from Arduino GitHub to 
`'C:\Users\espUser\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\tools\'` folder

But it didn't work because Win11 can't execute the EXE file, terminating the compilation with this error:

 
 `This version of C:\Users\espUser\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.6\tools\gen_insights_package.exe is not compatible with the version of Windows you're running. 
Check your computer's system information and then contact the software publisher.`

**Comment by SuGlider** [comment]
@me-no-dev 
Something seems wrong with the Windows EXE file `gen_insights_package.exe`

I see that the icon for this EXE is different from the icon for other EXE files in tools, like `espota.exe` and `gen_esp32part.exe`
I think that it may have been generated with a different process or tool (from the Python Script).

**Comment by me-no-dev** [comment]
@sanketwadekar please have a look at the windows expecutable

@SuGlider thanks for finding this out, but it's a bit unrelated to the issue that this PR is fixing :)

**Comment by SuGlider** [comment]
@me-no-dev @sanketwadekar 
As requested by Sanket, I have built the file `gen_insights_package.exe` for Windows 10/11 compatibility.
I tested it with Arduino IDE 1.8.15 using ESP32 and the example provided. It compiled correctly.

I have pushed the new file to this branch for merging this PR.

**Review by SuGlider — APPROVED** [review]

**Comment by me-no-dev** [comment]
Also just added one of the Insights example to be compiled by CI under mac and windows

**Pull request merged**
