### PR TITLE
Adds S3 GPIO48 in  digitalPinToInterrupt() + GPIO INTR Review

### LINKED ISSUE #8560: digitalPinToInterrupt doesn't accept pin 48
### Board

bpi_leaf_s3, and other ESP32-S2 and ESP-S3 variants

### Device Description

Not relevant

### Hardware Configuration

A pushbutton on IO48.

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Any

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

5000000

### Description

In many variants for ESP32S2 and ESP32S3, digitalPinToInterrupt is defined as:

#define digitalPinToInterrupt(p)    (((p)<48)?(p):-1)
But pin 48 is also valid as interrupt source.
Without a fix, this crashes:

attachInterrupt(digitalPinToInterrupt(48), Callback, FALLING);

The line should read:
#define digitalPinToInterrupt(p)    (((p)<=48)?(p):-1)

Furthermore, returning -1 doesn't play nice with attachInterrupt() that accepts an uint8_t. attachInterrupt lacks a bounds check for array access so this gives undefined behavior (for me, a crash).

### Sketch

```cpp
// Not a working sketch

void IRAM_ATTR Callback() {
}

void setup() {
  //This does not work:
  attachInterrupt(digitalPinToInterrupt(48), Callback, FALLING);
  //This works:
  attachInterrupt(48, Callback, FALLING);
}
```

### Debug Message

```plain
Crash
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Description of Change
A user has open an issue about not being able to add an Interrupt to ESP32-S3 GPIO 48 because the GPIO num shall be lower than 48 in `digitalPinToInterrupt()` macro.

Based on it, this PR has a initial review of the macros and the values used in `pins_arduio.h` for the main SoCs (ESP32, S2, S3 and C3).

## Tests scenarios
Simples test done in ESP32/S2/S3/C3 with `attachInterrupt()`.

## Related links
Closes #8560

### CODE REVIEW

**Comment by SuGlider** [comment]
@me-no-dev - Please let me know if this change makes sense. 
In case it makes sense, should I change all variants, before merging?

**Review by P-R-O-C-H-Y — APPROVED** [review]
Looks good :) LGTM

**Review by lucasssvaz — APPROVED** [review]
LGTM

**Comment by VojtechBartoska** [comment]
Resolution:
- we can add to all variants

**Comment by SuGlider** [comment]
@lucasssvaz @P-R-O-C-H-Y @me-no-dev -- ready for reviewing....
This was a lot of work and time... :-(

**Comment by SuGlider** [comment]
I also fixed a wrong already merged file name (pins_arduino.h.txt) :

12 changes: 6 additions & 6 deletions12  
[variants/lilygo_t_display/pins_arduino.h.txt → variants/lilygo_t_display/pins_arduino.h](https://github.com/espressif/arduino-esp32/pull/8562/files#diff-8863c15ed72eab912c09bed8982d382a25a85d26076cd8b398f5d35e9433ed76)

**Comment by SuGlider** [comment]
The changes in this PR include all recently added board (last 4 days).

**Comment by SuGlider** [comment]
But... there may be errors... so please take some time to review it carefully. Thanks!

**Comment by VojtechBartoska** [comment]
Thanks @SuGlider for handling this! I can imagine it was time consuming.

**Comment by me-no-dev** [comment]
I am not sure how to properly review this, but if you are worried that there might be issues, I would suggest we leave it for 3.0.0 and not risk another bugfix 2.0.x

**Comment by VojtechBartoska** [comment]
What about modifying slightly https://github.com/espressif/arduino-esp32/actions/workflows/boards.yml and check this by that?

**Comment by P-R-O-C-H-Y** [comment]
> I am not sure how to properly review this, but if you are worried that there might be issues, I would suggest we leave it for 3.0.0 and not risk another bugfix 2.0.x

As @VojtechBartoska mentioned, we can at least run the allboards workflow to see if there are any issues. I will add to the workflow new trigger on some label, let's say "Boards test" and then we can run it. I am not sure if we are able to run it now on PR when the workflow is set to run only on remote dispatch.

What do you think @me-no-dev ? That test can at least cover some typos check as I already found one.

**Comment by me-no-dev** [comment]
>  I am not sure if we are able to run it now on PR when the workflow is set to run only on remote dispatch.

You would need to specify the target pr when executing the workflow. Pass it as argument and then act in the workflow itself.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by SuGlider** [comment]
@P-R-O-C-H-Y @me-no-dev - This PR seems now ready and fine. It passes the Boards CI.
https://github.com/SuGlider/arduino-esp32/actions/runs/6067330536

@P-R-O-C-H-Y had some concerns about changing all the boards... we can discuss what would be best to do.
Anyway, if necessary, I can quickly create a new PR that addresses only the critical issue with the S3 GPIO48 and some other issues found in the CI process.

**Comment by VojtechBartoska** [comment]
This PR with changes for all variants is left to 3.0.0 milestone as it can have more consequences.

@SuGlider will open new PR with GPIO pin change from 48 to 49 for 2.0.12 milestone.

**Pull request closed without merging**
