### PR TITLE
Added compiler.warning_flags to platform.txt; fixing #6118

### PR DESCRIPTION
**Pull request by PilnyTomas**
## Summary
Added `compiler.warning_flags` to all chips in `platform.txt` to reflect users setting of warning level output during compilation (set up in Arduino IDE preferences)

## Impact
When a warning is set to none the compilation will no longer display warnings

## Related links
Solves issue #6118

### CODE REVIEW

**Comment by mrengineer7777** [comment]
Why does this PR modify "cores/esp32/esp32-hal-i2c-slave.c" and "libraries/WiFiClientSecure/src/esp_crt_bundle.c"?

**Comment by PilnyTomas** [comment]
> Why does this PR modify "cores/esp32/esp32-hal-i2c-slave.c" and "libraries/WiFiClientSecure/src/esp_crt_bundle.c"?

With the new compiler settings, the previously hidden warnings are now treated as errors and the CI is failing. Following commits are simply satisfying the compiler/CI. The changes are mostly removing unused variables and such.

**Comment by VojtechBartoska** [comment]
any updates on this @PilnyTomas?

**Comment by me-no-dev** [comment]
Thanks @PilnyTomas for your hard work :)

**Pull request merged**
