### PR TITLE
Expand gitignore to cover files created by Visual Micro

### PR DESCRIPTION
**Pull request by dok-net**
The Arduino IDE for Visual Studio in part uses the standard MS Visual Studio project layout.

### CODE REVIEW

**Comment by me-no-dev** [comment]
Dude... there are gazillion of commits and changes here :) let's do one by one.

**Comment by dok-net** [comment]
@me-no-dev OMG!!! Sorry, Git turns out to be a total mind-boggler after all, just like all the other tools before... sorry, I picked the wrong branch, one sec please :-) :-) :-)

**Comment by dok-net** [comment]
@me-no-dev And thank you for quickly pointing this out, what an embarrassment ;-)

**Comment by me-no-dev** [comment]
happens no worries :)

**Pull request merged**
