### PR TITLE
Add full setsocketoption to WifiClient and WifiClientSecure

### PR DESCRIPTION
**Pull request by 20162026**
-----------
## Description of Change
Adds full setsockopt method to WifiClient and WifiClientSecure as the previous implementation did not allow selection of option level, e.g. no way to change IPPROTO_TCP options for WifiClientSecure.

## Tests scenarios
tested with wroom32e based custom board, feature is backward compatible and should not break anything

## Related links
workaround for #6997

### CODE REVIEW

**Review by P-R-O-C-H-Y — APPROVED** [review]
LGTM, thanks @20162026 for PR

**Comment by SuGlider** [comment]
@20162026 - Should merging this PR close #6997? It seems good for merging.

**Comment by 20162026** [comment]
@SuGlider this PR will not solve #6997 by itself , it will just give user a possibility to modify TCP_KEEPIDLE as a workaround

**Review by SuGlider — APPROVED** [review]
LGTM

**Pull request merged**
