### PR TITLE
Add ATMegaZero ESP32-S2 microcontroller

### PR DESCRIPTION
**Pull request by eddieespinal**
## Summary
Adds support for the new ATMegaZero ESP32-S2 board. Adds the relevant section to `boards.txt` and adds the folder for the `atmegazero-esp32s2` with the proper `pins_arduino.h` to the `variants` folder.

## Impact
Allows users to compile code properly for the ATMegaZero ESP32-S2 without having to use a similar board and manually entering pin numbers.

## Links
[ATMegaZero ESP32-S2](https://atmegazero.com/#/atmegazero_esp32s2_overview)

Thanks!

### CODE REVIEW

**Comment by eddieespinal** [comment]
What else is needed in order to get this PR merged in?

**Comment by pedrominatel** [comment]
Done @eddieespinal

**Comment by manchoz** [comment]
Hi @eddieespinal, `arduino-cli` is complaining about a malformed option:

```sh
$ arduino-cli board list
Error initializing instance: loading platform release esp32-git:esp32@2.0.0: loading boards: skipping loading of boards esp32-git:esp32:deneyapmini, esp32-git:esp32:atmegazero_esp32s2: malformed custom board options
```

**Comment by chegewara** [comment]
i want this board due to FLASH and SPIRAM size.

**Pull request merged**
