### PR TITLE
Update README.MD - "Type: For reference" labels link

### PR DESCRIPTION
**Pull request by VojtechBartoska**
## Summary
Updating a link to issues labeled with "Type: For reference". The old one is not working due to the updates of labels in the past.

## Impact
None

### CODE REVIEW

**Comment by pedrominatel** [comment]
@VojtechBartoska please add a new RELEASE NOTES mandatory field.

We can use this new field to improve our release notes for the next release.

**Comment by VojtechBartoska** [comment]
@pedrominatel It will overlap a bit with PR "Summary field". Other option is to edit this field manually (if it's not properly filled up by author of PR) and set up some script which will consider that "Release notes" field and build release notes automatically from that. What do you think?

**Review by pedrominatel — APPROVED** [review]
LGTM

**Comment by VojtechBartoska** [comment]
@me-no-dev can you please merge this to update README?

**Comment by me-no-dev** [comment]
didn't we have this template already?

**Comment by VojtechBartoska** [comment]
Ah, it's the same. No changes there, I didn't pull properly. Changes only on README.

**Pull request merged**
