### PR TITLE
Feature/selective compilation

### PR DESCRIPTION
**Pull request by nathanjel**
Enable selective compilation of Arduino libraries. Makes a big difference for projects which use entire Arduino library for late linking purposes (as in COMPONENT_ADD_LDFLAGS := -Wl,--whole-archive -l$(COMPONENT_NAME) -larduino-esp32 -Wl,--no-whole-archive)

### CODE REVIEW

**Comment by me-no-dev** [comment]
@nathanjel is this good to go?

**Comment by nathanjel** [comment]
I incorporated Your comments and use this updated version in my code successfully. So the answer is Yes :)

**Comment by me-no-dev** [comment]
merged!

**Comment by psykokwak-com** [comment]
I have some build error since this update.
I have added some libraries on my libraries folder and I have these warning : 
```
AR build/app_update/libapp_update.a
/home/Jyce/esp/arduino/components/arduino/component.mk:3: avertissement : variable « CONFIG_ARDUINO_SELECTIVE_ESPAsyncWebServer » indéfinie
/home/Jyce/esp/arduino/components/arduino/component.mk:3: avertissement : variable « CONFIG_ARDUINO_SELECTIVE_AsyncTCP » indéfinie
/home/Jyce/esp/arduino/components/arduino/component.mk:3: avertissement : variable « CONFIG_ARDUINO_SELECTIVE_ArduinoJson » indéfinie
```

**Comment by nathanjel** [comment]
Adjust Kconfig.projbuild accordingly to support the new libraries You added locally.

**Comment by psykokwak-com** [comment]
If I unset selective compilation, it should scan and build all lib in the folder.

**Comment by nathanjel** [comment]
Indeed, You have a point there. What would You believe is the right behaviour if You choose selective compilation and pick some, what should happen with Your added libraries? Should they go in or out? Or a checkbox like "include additional"?

By the way, I still hope there is way to trick IDF to regenerate Kconfig... You just got me a bit closer to researching that.

**Comment by psykokwak-com** [comment]
Good question. "include additionnal" will help users that do not know how to add them manually. It could be a good idea.

**Comment by nathanjel** [comment]
If I don't get a bright idea how to adjust Kconfig automatically, that seems the next best solution. @me-no-dev - any ideas/comments from You?

**Comment by me-no-dev** [comment]
Here is how it should work. If a library is not in the list for selection, it should be automatically included, regardless of what is selected in the menu.

**Comment by nathanjel** [comment]
#1678 issue created. @psykokwak-com, it seems @me-no-dev was quicker than me with the fix. please check now and confirm the issue is resolved.

**Pull request merged**
