### PR TITLE
Set ESP-IDF to 3.2

### PR DESCRIPTION
**Pull request by me-no-dev**
Also updates the camera example and detaches the BLE lib from the source repo (code is now included in Arduino)

### CODE REVIEW

**Comment by pgrisu** [comment]
Hi @me-no-dev can you indicate the exact esp-idf commit number you used to create binary libraries for this arduino-esp32 repo?
By the subject I supposed you used the esp-idf tag v3.2, but checking the esp-wifi-libs it seems that some different esp-idf commit (and esp-wifi-lib submodule) was used.
Can you clarify this?
Thanks

**Comment by me-no-dev** [comment]
i used the 3.2 tag to create all libs. What do you see exactly that is different?

**Comment by pgrisu** [comment]
Tag 3.2 uses esp32-wifi-lib submodules at commit eb53491( https://github.com/espressif/esp32-wifi-lib/tree/eb53491cf6eb18d6cfd98f7b3bb4e09fb241733c ) but the  arduino-esp32 v1.0.2 wifi libraries into tools/sdk/lib are different from the above (as binary size and contents).
Moreover I checked that also some esp-idf v3.2 headers files into mbedtls, newlib and soc components are a bit different from the same exported into arduino-esp32 v1.0.2 tools/sdk/include.
Can you check it? May be you missed some git submodules update?

**Comment by me-no-dev** [comment]
I will doublecheck, though I did made sure that I selected the proper commit, that I did update the submodules to whatever version the tag requested and that I made a clean build and import of all libs.

**Comment by pgrisu** [comment]
Ok thanks, I digged a bit more...
regarding differences on some headers files my mistake on mbedtls and newlib headers.
Regarding soc headers both tools/sdk/include/soc/soc/soc.h and tools/sdk/include/soc/soc/soc_memory_layout.h into arduino-esp32 v1.0.2 are at previous commit compared with the esp-idf v3.2.

Here the esp-wifi-libs mismatching the esp-idf 3.2 components/esp32/lib submodule contents
tools/sdk/lib/libcoexist.a
tools/sdk/lib/libcore.a
tools/sdk/lib/libespnow.a
tools/sdk/lib/libmesh.a
tools/sdk/lib/libnet80211.a
tools/sdk/lib/libpp.a
tools/sdk/lib/libwpa.a
tools/sdk/lib/libwpa2.a
tools/sdk/lib/libwps.a

**Comment by me-no-dev** [comment]
Can you check the current situation. We are tracking the 3.2 branch now on a clean import.
Available as 1.0.3-rc1 from the development package manager link

**Pull request merged**
