### PR TITLE
Mention size limitation in default configuration

### PR DESCRIPTION
**Pull request by tko**
Given that BLE and WiFi are kind of a selling point of ESP32 to begin with it's worth mentioning they can't be used together without some tweaks to default configuration.

---

The alternate partitioning scheme I picked is one I think is the _least_ drastically different from the default. I have no experience to evaluate the alternatives other than things like dropping OTA completely, or switching to FATFS just feel completely unwarranted when all one needs is some more bytes. (I can guess the implications of no-OTA but I've absolutely no idea about FATFS.)

IMO the default configuration should "just work" out of the box to minimize any friction with newcomers while making as much of the chip accessible as possible, but I've no idea of all the things default configuration needs to cater to.

Ref: https://github.com/espressif/arduino-esp32/issues/4668

### CODE REVIEW

**Comment by lbernstone** [comment]
What does this have to do with installing the board package?  Perhaps this belongs at https://github.com/espressif/arduino-esp32/tree/master/libraries/BLE

**Comment by chegewara** [comment]
I have a question. When you will have another project, not related to ble and wifi, and binary size will exceed default partition, you will come back again and add new description? Changing partition scheme is most basic thing in arduino, not only esp32.

BTW not everyone is buying esp32 because of ble + wifi, there is many more features including 2 cores, psram, RMT etc

**Comment by tko** [comment]
@lbernstone the change is to the README that is linked from the "Using Arduino IDE Boards Manager (preferred)" from the repo root and so following the instructions gives some visibility to the unobvious restrictions. libraries/BLE is buried deeper and not even mentioned at repo root so it's relatively invisible.

@chegewara Depends on the context. From what I vaguely understand only BLE is is so massive that combining it with anything else is likely to exceed default partition size. Or are there some other surprises that simply won't work by default?

My concern is about the out of the box surprises, IMO for a beginner friendly project like Arduino it is important that the defaults are good ones and not add any unnecessary roadblocks. As it currently stands BLE+WiFi just plain does not work (more below) -- if changing partitioning scheme fixes it, couldn't the default partitioning scheme support it already and save everyone some trouble? Would changing the defaults to accommodate an important(?) use case break other use cases? If not then why not change it so that getting started is easier, and beginners wouldn't be _required_ to know about partitions when starting?

Regarding the wording in the PR I noticed the instruction is incomplete as apparently each board has its own partitioning schemes. My chip just arrived and depending on which details I read it's either a NodeMCU (default partition doesn't work and there is no easy alternative either as there is no "Partition Scheme" menu option at all) or WROOM (not present as a board alternative)

**Comment by me-no-dev** [comment]
While I do not mind such notes to be added, that should happen in another place. Like some general help/FAQ page

**Pull request closed without merging**
