### PR TITLE
Added Servo Library 

### PR DESCRIPTION
**Pull request by zeynepdicle**
*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

### Checklist
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [ ] Please **update relevant Documentation** if applicable
4. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
Added servo motor library. Maker easily develops his projects using this library.

## Tests scenarios
- I have tested my Pull Request on  Arduino-esp32 core v2.0.5 with ESP32, ESP32-S2 and ESP32C3 Board with this scenario.
- I have used my [Deneyap Arduino Core v1.3.8](https://github.com/deneyapkart/deneyapkart-arduino-core) with ESP32, ESP32-S2 and ESP32C3 Board with this library.

(*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with ESP32 and ESP32-S2 Board with this scenario*)

## Related links
Please provide links to related issue, PRs etc.
(*eg. Closes #number of issue*)

### CODE REVIEW

**Comment by P-R-O-C-H-Y** [comment]
Hi @zeynepdicle, why did you close it? I was about to review next week :)

**Comment by zeynepdicle** [comment]
@P-R-O-C-H-Y When I open these issues I see x(close) symbols in the tab so I thought this repo was unacceptable and closed it but opened it again.
Thanks for the comment :)

**Comment by zeynepdicle** [comment]
@P-R-O-C-H-Y i have 2 pull request.

1 added Servo Motor library

2 added newly Deneyap Boards
- added newly Deneyap Mini v2 Board (ESP32S2)
- added newly Deneyap Kart 1A v2 Board (ESP32S3)
- updated Deneyap pin_arduino.h files

I would like to do two separate pull request. Is that possible ?

**Comment by P-R-O-C-H-Y** [comment]
@zeynepdicle For sure make it 2 separate pull requests :)

**Comment by P-R-O-C-H-Y** [comment]
@zeynepdicle We appreciate a lot your time and effort!
But, we have discussed internally and given that the Servo library is not a peripheral API or SoC Core library, it was decided to do not include it in our Arduino-esp32 core repository.

Would you consider to create an external repository with this library?
Or add it to the Arduino Library List
https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries

About the boards, please open a new PR. I will review it there.
Thank you, P-R-O-C-H-Y

**Comment by zeynepdicle** [comment]
> @zeynepdicle We appreciate a lot your time and effort! But, we have discussed internally and given that the Servo library is not a peripheral API or SoC Core library, it was decided to do not include it in our Arduino-esp32 core repository.
> 
> Would you consider to create an external repository with this library? Or add it to the Arduino Library List https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries
> 
> About the boards, please open a new PR. I will review it there. Thank you, P-R-O-C-H-Y

Thank you:)

**Pull request closed without merging**
