### PR TITLE
cores: replace max and min macros with imports from std

### LINKED ISSUE #1734: Arduino.h: error on max macro definition
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			up to date as of 06/08/2018
IDE name:							VSCode
Flash Frequency:					80Mhz
Upload Speed:						921600

### Description:
I am working with a TTGO esp32 module and I'm using vectors in my code, and it compiled fine up to a certain point. Then, out of the blue, it suddenly started giving me this error when trying to upload the code to the board: 

```
c:\users\ivano\documents\arduino\hardware\espressif\esp32\tools\xtensa-esp32-elf\xtensa-esp32-elf\include\c++\5.2.0\bits\stl_vector.h: 
In member function 'std::vector<_Tp, _Alloc>::size_type std::vector<_Tp, _Alloc>::_M_check_len(std::vector<_Tp, _Alloc>::size_type, const char*) const':

C:\Users\Ivano\Documents\Arduino\hardware\espressif\esp32\cores\esp32/Arduino.h:182:18: error: expected unqualified-id before '(' token

 #define max(a,b) ((a)>(b)?(a):(b))
```

To get it to compile again I had to undefine min and max after including Arduino.h

```c++
#include <Arduino.h>
#undef min
#undef max
```

It might be worth noting that I'm also including `vector` in another file but commenting that include out did not change the problem. 

Is there a reason why this should happen?

### PR DESCRIPTION
**Pull request by yoursunny**
fixes #1734

### CODE REVIEW

**Comment by yoursunny** [comment]
TravisCI is unhappy. I tried the two examples from AzureIoT library locally (Arduino IDE 1.8.5 on Windows), and they all build correctly. I couldn't figure out what's wrong.

**Comment by stickbreaker** [comment]
Looks like the problem is a redefinition of `round()` in `Arduino.h`


>/home/travis/build/espressif/arduino-esp32/tools/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/bits/random.tcc: In member function 'void std::poisson_distribution<_IntType>::param_type::_M_initialize()':
/home/travis/arduino_ide/hardware/espressif/esp32/cores/esp32/Arduino.h:78:22: error: expected unqualified-id before '(' token
 #define round(x)     ((x)>=0?(long)((x)+0.5):(long)((x)-0.5))

**Comment by yoursunny** [comment]
There's a usage of `std::round`.
https://github.com/jmattsson/nodemcu-prebuilt-toolchains/blob/3f4f3890f97fe01870770dd5a624ee0823d71a13/esp32/xtensa-esp32-elf/include/c%2B%2B/5.2.0/bits/random.tcc#L1408

Looks like I also need to replace `#define round` with `using std::round`.

**Comment by yoursunny** [comment]
I’ve completed the `round` changes. Hopefully this can be reviewed soon.

**Comment by me-no-dev** [comment]
Hey! Thanks for going through this :) It was somewhere on the list of things to do...

**Comment by radiumray** [comment]
hi, we got this issue, the test code is below:

```
uint8_t a = 2;
uint16_t b = 6;
uint16_t c = 0;
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  c = min(a, b);
  Serial.println(c);
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

this code will got error:
`no matching function for call to 'min(uint8_t&, uint16_t&)'`

we think this change cause this issue:
https://github.com/espressif/arduino-esp32/commit/1e4bf14a3eef4894f65783b4940d98777d5e2263#diff-50967a1be7f16cc780e7a8501c5d6c34

**Pull request merged**
