### PR TITLE
Added instructions for installation with boards manager

### PR DESCRIPTION
**Pull request by lbernstone**
(stolen directly from esp8266)

### CODE REVIEW

**Comment by lbernstone** [comment]
The main links there do go to dl.espressif . The "latest" release is some magic from img.shields.io to make a fancy image from the release number in github. I assume the undefined it shows now is due to the rc in the version number.  Take a look at https://github.com/esp8266/Arduino/#installing-with-boards-manager to see where I lifted it from.

**Comment by me-no-dev** [comment]
you are currently linking to `_dev` package ;)

**Comment by me-no-dev** [comment]
Maybe we want to spice things up a bit? There are better options for icons :)
Remove "-pre" from the links to make it release

Latest Release: Latest Release
Latest Pre-Release Date: Latest Pre-Release Date
Latest Pre-Release Downloads: Latest Pre-Release Downloads
Total Pre-Release Downloads: Total Pre-Release Downloads

**Comment by CornyjK** [comment]
What about adding link for this file to `readme.md`?

**Comment by me-no-dev** [comment]
We will once we push a release. We are in prerelease stage now. Links are not valid ;)

**Comment by lbernstone** [comment]
I didn't put the downloads count.  I think you will be the only one really interested in that.  See if you like the wording/layout of the install list now.

**Comment by me-no-dev** [comment]
Maybe we should also add the _dev link for those that want the very latest package possible? We want it to be used. why else do it :D

**Comment by lbernstone** [comment]
I think with all the "undefined" grey images on the stable line, this is probably clear enough to go into use before the stable release is done

**Pull request merged**
