### PR TITLE
Fix stall on usb write: try to write only if usb is actually connected

### PR DESCRIPTION
**Pull request by imwhocodes**
-----------
## Description of Change
While developing on local esp32-s3 the program stalled if no pc was connected to the USB
USB was written by both normal `Stream::write` and the native log infrastructure  

This fix the issue by checking if USB is _enabled_ before trying to actually write

## Related links
I'm aware of https://github.com/espressif/arduino-esp32/commit/1d595fd35c9755bbf42e8c1193200a616e81d536 by @SuGlider but it is not clear to me as this could completely address the 'unconnected USB problem': changing `tx_timeout_ms` impact only if there are 2 threads writing to the USB and one of them is already stuck trying to write

Maybe I'm missing something,
Luca

### CODE REVIEW

**Review by SuGlider — COMMENTED** [review]
Not sure if the PR is necessary. Plese check my comments above.

**Comment by SuGlider** [comment]
>I'm aware of https://github.com/espressif/arduino-esp32/commit/1d595fd35c9755bbf42e8c1193200a616e81d536 by @SuGlider but it is not clear to me as this could completely address the 'unconnected USB problem': changing tx_timeout_ms impact only if there are 2 threads writing to the USB and one of them is already stuck trying to write

Thanks @imwhocodes for the PR.
PR #7583 fixes the issue you want to address with this PR.
**Please let me know if you have an specific use case to demonstrate the issue.**

### I used this Testing Sketch:

I have an [ESP32-S3 with 2 USB ports](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html) here. One for UART and another for USB CDC.
I have plugged both USB ports to may Win11 PC.
I Selected ESP32-S3 board with these options in the IDE Board Menu:
* USB Mode: "Hardware CDC and JTAG"  ==>  this is the option associated to HWCDC.cpp code
* USB CDC On Boot: "Enabled"    ==> it will work with USB CDC (Serial = CDC)
In this mode, `Serial` will be the HW USB CDC port and `Serial0` will be the UART port.

The idea of this testing sketch is to write a message in UART and USB CDC every 1 second. 

I used PuTTY as terminal to connect to the Win11 COM port from the S3 UART and used Arduino Serial Monitor to connect to the USB CDC Win11 COM port. In this way, Putty will display the loop UART messages while I can experiment with the USB CDC port, plugging, unplugging, closing the Serial Terminal etc.

``` cpp
void setup() {
  Serial.begin(115200);
  Serial0.begin(115200);

  while(!Serial0) delay(1);
  Serial0.print("\n=================\nPrinting on UART\n=================\n");
}

void loop() {
  static uint32_t now = millis();

  if (millis() > now + 1000) {
    Serial0.printf("[%d] Loop running...\n", millis());
    Serial.printf("[%d] Loop running USB CDC...\n", millis());
    now += 1000;
  }
}
```

### Conclusion of the experiment:

1- If I start the S3 only with the Serial Port plugged, I get the loop working fine, every 1 second, even when it is trying to write to the CDC port as well. Therefore, it never stalls.

2- If I start the S3 with both ports plugged and then open the Arduino Serial Monitor (which will only work when Windows enumerates the USB CDC), I see both ports with messages. Because the messages are buffered into the Ring Buffer, I can see all of them from the beginning.

Now, if I unplug the USB from the S3, the serial monitor stops displaying new messages, which is OK.
But the UART continues in PuTTY, which means that the S3 has not stalled.

Now close the Serial Monitor Window. Plug the USB back again.
Open the Serial Monitor again and see the messages flowing in both the Serial Monitor and PuTTY.
No stall...
In the Serial Monitor you may see the Time Stamp a bit jumping, it is due to, again, buffering written data.

**Comment by imwhocodes** [comment]
Ok I did some testing and found the problem:
If you try to call `void Stream::flush()` on the USB-CDC Serial it get stuck

```cpp
#include <Arduino.h>

void setup() {
  Serial.begin(115200);
  Serial0.begin(115200);

  while(!Serial0) delay(1);

  Serial0.print("\n=================\nPrinting on UART\n=================\n");
  Serial0.flush();

  Serial.print("\n=================\nPrinting on USB CDC\n=================\n");
  Serial.flush(); // <-- HERE PROGRAM STALL


}

void loop() {
  static uint32_t now = millis();

  if (millis() > now + 1000) {
    Serial0.printf("[%d] Loop running UART...\n", millis());
    Serial0.flush();

    Serial.printf("[%d] Loop running USB CDC...\n", millis());
    Serial.flush();

    now += 1000;
  }
}
```



I'm working on platformio, here you have the complete test project
On `platformio.ini` file you can change the `platform_packages =` parameter between release _2.0.6_ and my _branch-fix_


Honestly I still think that the timeout is a stop-gap measure, proper way should be to check if usb is connected (**indicated by the value of `initial_empty`**) and bail-out of all operation if it is disconnected, as propose by my PR

[Serial-USB-Fixes-Test.zip](https://github.com/espressif/arduino-esp32/files/10556362/Serial-USB-Fixes-Test.zip)

Thanks,
Luca

**Comment by SuGlider** [comment]
Maybe related to #7554

**Comment by SuGlider** [comment]
@imwhocodes - What is the OS of the computer used for the `flush()` testing?

**Comment by imwhocodes** [comment]
> @imwhocodes - What is the OS of the computer used for the `flush()` testing?

MacOS and Ubuntu
But it is not correlated, it stall only if the CDC-USB is not connected to the PC

**Comment by SuGlider** [comment]
> [CLA assistant check](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7721) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7721) before we can accept your contribution.
> 
> **Luca** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=7721) it.

@imwhocodes - please review and sign the CLA in order to continue with the process. Thanks!

**Comment by SuGlider** [comment]
@imwhocodes 

I'm sorry, but it seems that CI won't let it pass because of commit e392b551b9cd609ae4d87a86d4b6fa9c0af2755b
It was done by another user (the wrongly configured one) and because it has no CLA/valid Github user, it won't be able to pass CI and then we can't merge it after reviewing it.

Please close this PR and open a new one with a single commit from your valid GH user ID.

**Comment by VojtechBartoska** [comment]
This PR needs more investigation and testing, milestone changed to 3.0.0.

**Comment by VojtechBartoska** [comment]
Hello @imwhocodes, can you please sign CLA?

**Comment by imwhocodes** [comment]
> Hello @imwhocodes, can you please sign CLA?

Commit is signed with "Luca" but my user-name is "imwhocodes" so it refuse my signing

**Comment by lucasssvaz** [comment]
> > Hello @imwhocodes, can you please sign CLA?
> 
> Commit is signed with "Luca" but my user-name is "imwhocodes" so it refuse my signing

Please recommit with the proper author configuration.

**Comment by Jason2866** [comment]
We (Tasmota) use this to detect if JTAG USB is connected:
```
#if SOC_USB_SERIAL_JTAG_SUPPORTED  // Not S2
  rtc_clk_bbpll_add_consumer();    // Maybe unneeded
  usb_serial_jtag_ll_ena_intr_mask(USB_SERIAL_JTAG_INTR_SOF);
  usb_serial_jtag_ll_clr_intsts_mask(USB_SERIAL_JTAG_INTR_SOF);
  // First check if USB cable is connected
  for (uint32_t i = 0; i < 1000; i++) {  // Allow the host to send at least one SOF packet, 1ms should be enough but let's be very conservative here - maybe unneeded
      is_connected_to_USB = ((usb_serial_jtag_ll_get_intraw_mask() & USB_SERIAL_JTAG_INTR_SOF) != 0);
      if (is_connected_to_USB) { break; }
      delay(1);
  }
  rtc_clk_bbpll_remove_consumer();
#else
  is_connected_to_USB = true;      // S2
#endif  // SOC_USB_SERIAL_JTAG_SUPPORTED
```

**Review by SuGlider — COMMENTED** [review]
This PR demonstrates an issue, but the solution was changed to use USB SOF signal from IDF 5.1 implementation. It will be solved within Arduino Core 3.0.0.

Thanks @imwhocodes !!

**Pull request closed without merging**
