### PR TITLE
Update pins_arduino.h - Adafruit feather ESP32

### PR DESCRIPTION
**Pull request by Gius-8**
I had to make this change to use the Serial UART. Serial1 does not seem to work, while with this change I can use Serial2 correctly.
Do you think it is correct to modify it in this way? Thanks

### CODE REVIEW

**Comment by me-no-dev** [comment]
don't know :) let's try to chime in @ladyada and see if she knows what would be the best option. I too wondered why RX and TX are defined to such pins. In any way, you can start any serial on any pins you like:
```Serial1.begin(115200, SERIAL_8N1, rx_pin, tx_pin);``` so predefinitions are not really needed

**Comment by ladyada** [comment]
hihi - here's the schematic
image

and on the Feather we label **IO17** as Serial1 TX and **IO16** as Serial1 RX. Serial is the USB-serial converter and just for debug/upload. Serial1 is Arduino standard naming for the 'external' UART for GPS, cell, etc.
Serial2 is confusing, that's for the second UART, whereas we only have one, so it should be called **Serial1**

**Comment by me-no-dev** [comment]
@ladyada so are those definitions tied anywhere in your code? maybe makes sense to label them RX1/TX1? but will that break anything?

**Comment by ladyada** [comment]
i dont use those literal pin names anywhere - historically those pins have 'just worked' in the definition to set up **Serial1** - if the BSP has changed so that they need to be named differently you can change em. Only requirement is it must be **Serial1** (which is hardcoded everywehere in the universe)

**Comment by me-no-dev** [comment]
Ahh now I am starting to recall what was the whole thing about. I'll have a look and make sure that Serial1 corresponds to those pins by default. Maybe even dig up the old issue for refreshment :)

**Comment by me-no-dev** [comment]
@ladyada @Gius-8 according to [this line](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/HardwareSerial.cpp#L46), names must be RX1 and TX1 for Serial1 to auto select them.
@Gius-8 will you make the appropriate change? Maybe also replace the pins for RX and TX to 3 and 1 for clarity :)

**Comment by Gius-8** [comment]
Hi everyone, I had to modify otherwise Serial1 didn't work for me.

**Comment by me-no-dev** [comment]
But how did Serial1 worked for you with this definition if you are changing it for Serial2?

**Comment by me-no-dev** [comment]
See here: https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/HardwareSerial.cpp#L9-L23

You are just defining the same thing, but instead you should be defining RX1 and TX1

**Comment by me-no-dev** [comment]
resolved here: https://github.com/espressif/arduino-esp32/commit/d922557e0183fcf5faf0e59c3e0f6dee52d091d4

Please test :)

**Pull request closed without merging**
