### PR TITLE
I2S - Revert espressif/esp-idf@73ca054 to fix I2S crackling

### LINKED ISSUE #8467: Crackling sound on i2s with internal DAC since 2.0.10
### Board

ESP32 dev board

### Device Description

DevKitC

### Hardware Configuration

Speaker on GPIO25 

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Linux and Windows

### Flash frequency

40Mhz

### PSRAM enabled

no

### Upload speed

921000

### Description

This demo sketch used to play a rectangle wave form on GPIO25 it works on 2.0.6 to 2.0.9

Since 2.0.10 sound is distorted and has a crackling noise overlaid. Oscilloscope shows short spikes in the rectangle signal.

### Sketch

```cpp
#include "driver/i2s.h"

unsigned short snd_buffer[64];

void setup() {
    static const i2s_config_t i2s_config = {
    .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX | I2S_MODE_DAC_BUILT_IN),
    .sample_rate = 24000,
    .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,

    .channel_format = I2S_CHANNEL_FMT_ONLY_RIGHT,
    .intr_alloc_flags = 0,
    .dma_buf_count = 4,
    .dma_buf_len = 64,   // 64 samples
    .use_apll = true
  };
  i2s_driver_install(I2S_NUM_0, &i2s_config, 0, NULL);
  i2s_set_dac_mode(I2S_DAC_CHANNEL_RIGHT_EN);
}

void loop() {
  // generate square wave
  for(int i=0;i<32;i++)  snd_buffer[i] = 0x0000;
  for(int i=32;i<64;i++) snd_buffer[i] = 0x1000;

  size_t bytesOut = 0;
  i2s_write(I2S_NUM_0, snd_buffer, sizeof(snd_buffer), &bytesOut, 0);
  printf("BytesOut: %d\n", bytesOut);
}
```

### Debug Message

```plain
Endless sequence of
BytesOut: 128
BytesOut: 0

No difference in output between 2.0.9 and 2.0.10
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by lucasssvaz**
## Description of Change
Commit https://github.com/espressif/esp-idf/commit/73ca054 introduced crackling in the I2S communication (as discussed in #8467). This PR aims to revert the changes by replacing the `libdriver.a` file for each board with one the reverted changes.

Each `libdriver.a` file was generated by the following steps:

1 - Cloned ESP-IDF and checked out tag v4.4.5;
2 - Reverted commit;
3 - Added [Arduino as an ESP-IDF component](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/esp-idf_component.html);
4 - Copied `tools/sdk/<CHIP>/sdkconfig` to IDF project folder;
5 - Compiled using `idf.py build`;
6 - Copied `<PROJECT_FOLDER>/build/esp-idf/driver/libdriver.a` to `tools/sdk/<CHIP>/lib/libdriver.a`.

## Tests scenarios

Tested by @harbaum on ESP32-DevKitC on #8467.

## Related links

Closes #8467.

### CODE REVIEW

**Comment by lucasssvaz** [comment]
@harbaum Could you please double-check if this is working as expected ? Thanks in advance!

**Comment by lucasssvaz** [comment]
Ehh, the CI is failing. I probably did something wrong when building the libs 😴

**Comment by me-no-dev** [comment]
you targeted the wrong branch as beginning. Start clean from branch `release/v2.x`, overwrite the libs and submit another PR

**Comment by Jason2866** [comment]
Mhh, imho a dirty way to fix and should not be Merged! It is not working when compiling Arduino as component of IDF. The revert of IDF commit https://github.com/espressif/esp-idf/commit/73ca054 is nowhere in an official source / branch.
There is no possibility to do a reproducible build of the Arduino libs!

**Comment by lucasssvaz** [comment]
@me-no-dev I forgot I could've just fixed the commit and reopened it. I ended up creating another PR (#8583). My bad 😞

**Pull request closed without merging**
