### PR TITLE
Fix BluetoothSerial thinking it's disconnected

### PR DESCRIPTION
**Pull request by aridet**
Currently, if a second connection occur in Bluetooth, this second connection is automatically disconnected (line 284). This disconnection trigger the ESP_SPP_CLOSE_EVT, which clear the bit SPP_CONNECTED. But the first connection remain active, and this flag shouldn't be cleared.

This fix the issue, by clearing the flag only if the last connection is closed

*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

### Checklist
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [ ] Please **update relevant Documentation** if applicable
4. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
Please describe your proposed Pull Request and it's impact.

## Tests scenarios
Please describe on what Hardware and Software combinations you have tested this Pull Request and how.

(*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with ESP32 and ESP32-S2 Board with this scenario*)

## Related links
Please provide links to related issue, PRs etc.

(*eg. Closes #number of issue*)

### CODE REVIEW

**Comment by me-no-dev** [comment]
Shouldn't similar thing be necessary for line 286 and 287? They would also alter the bits, regardless if connection is first or second.

**Comment by VojtechBartoska** [comment]
First of all, thank you for the PR. Any updates on this @aridet?

**Comment by aridet** [comment]
Hi,

I don't think lines 286 and 287 are affected by this as we are in the case ESP_SPP_SRV_OPEN_EVT. It is fired when a connection successfully occur. This disable SPP_DISCONNECTED (xEventGroupClearBits disable the flag) and enable SPP_CONNECTED (xEventGroupSetBits set the flag). This seems correct to me.
If we are first or second connection, the result is always the same, there is an active connection, so the flags are correct for me.

Regards.

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Comment by P-R-O-C-H-Y** [comment]
> Hi,
> 
> I don't think lines 286 and 287 are affected by this as we are in the case ESP_SPP_SRV_OPEN_EVT. It is fired when a connection successfully occur. This disable SPP_DISCONNECTED (xEventGroupClearBits disable the flag) and enable SPP_CONNECTED (xEventGroupSetBits set the flag). This seems correct to me. If we are first or second connection, the result is always the same, there is an active connection, so the flags are correct for me.
> 
> Regards.

Make sense, thanks for this PR. Approved 👍

**Pull request merged**
