### PR TITLE
Fix incorrect definition of FPSTR() macro and move it from pgmspace.h to WString.h (#1371)

### PR DESCRIPTION
**Pull request by bxparks**

### CODE REVIEW

**Comment by me-no-dev** [comment]
what have you tested this with?

**Comment by bxparks** [comment]
I'm not sure what kind of testing you are looking for, but the following compiles and prints "Hello PROGMEM" on the ESP8266. It fails to compile on the ESP32:
```C++
#include <pgmspace.h>

// Cannot use F() macro outside of a function, use PROGMEM directly.
static const char HELLO_PROGMEM[] PROGMEM = "Hello PROGMEM";

void printFlashString(const __FlashStringHelper* s) {
  Serial.println(s);
}

void setup() {
  delay(1000);
  Serial.begin(115200);
  while(!Serial); // for Arduino Leonardo/Micro

  printFlashString(FPSTR(HELLO_PROGMEM));
}

void loop() {
}
```

The error is:
```
.../FlashMemory.ino: In function 'void setup()':
FlashMemory:21:35: error: cannot convert 'const char*' to 'const __FlashStringHelper*' for argument '1' to 'void printString(const __FlashStringHelper*)'
   printString(FPSTR(HELLO_PROGMEM));
                                   ^
exit status 1
```

**Comment by bxparks** [comment]
If I apply this PR to my ESP32 core on my Arduino IDE 1.8.9 `.../packages/esp32/hardware/esp32/1.0.2/cores/esp32/{WString.h,prgmspace.h}`, the same program compiles, and prints the correct output on the ESP32.

**Comment by me-no-dev** [comment]
OK it's not a big deal :) let's merge and see if we get any issues before we cut 1.0.3 final

**Pull request merged**
