### PR TITLE
Add "M5Stack-Core-ESP32" boards support

### PR DESCRIPTION
**Pull request by m5stack**
Add "M5Stack-Core-ESP32" boards support.
http://www.m5stack.com/
Thank you.

### CODE REVIEW

**Comment by me-no-dev** [comment]
Nice! Do you have those kits available?

**Comment by m5stack** [comment]
Yeah, we finished the mass manufacture! Can ship right now.


来自阿里邮箱 iPhone版 ------------------原始邮件 ------------------发件人：Me No Dev <notifications@github.com>日期：2017-08-17 21:17:19收件人：espressif/arduino-esp32 <arduino-esp32@noreply.github.com>抄送：M5Stack <JimmyLai@M5Stack.com>, Author <author@noreply.github.com>主题：Re: [espressif/arduino-esp32] Add "M5Stack-Core-ESP32" boards support (#579)Nice! Do you have those kits available?

**Comment by me-no-dev** [comment]
Ok, how can I order a couple? That form on the website looks sketchy ;)

**Comment by m5stack** [comment]
Please tell me the address and phone number by email to JimmyLai@M5Stack.com.We will ship right now.


来自阿里邮箱 iPhone版 ------------------原始邮件 ------------------发件人：Me No Dev <notifications@github.com>日期：2017-08-17 22:11:09收件人：espressif/arduino-esp32 <arduino-esp32@noreply.github.com>抄送：M5Stack <JimmyLai@M5Stack.com>, Author <author@noreply.github.com>主题：Re: [espressif/arduino-esp32] Add "M5Stack-Core-ESP32" boards support (#579)Ok, how can I order a couple? That form on the website looks sketchy ;)

**Comment by me-no-dev** [comment]
Sent!

**Pull request merged**
