### PR TITLE
Fixes issue-3153 - Allocating enough memory to construct the entire UUID as a String

### PR DESCRIPTION
**Pull request by william-ferguson-au**
Fix for https://github.com/espressif/arduino-esp32/issues/3153

### CODE REVIEW

**Comment by me-no-dev** [comment]
thanks!

**Comment by william-ferguson-au** [comment]
Any time.

@me-no-dev I would have solved this 3 days earlier, except I became derailed by either a subtle bug or my misunderstanding of the way that CString#c_str() is working. Would you mind jumping on https://www.esp32.com/viewtopic.php?f=19&t=12529 and explaining what I'm not understanding?

**Comment by ufanders** [comment]
Did this fix get merged into ESP32 Arduino Core library v1.0.4? I'm still seeing this problem.

**Comment by william-ferguson-au** [comment]
Appears to be on the 1.0.4 and 1.0.4-rc1 tags
https://github.com/espressif/arduino-esp32/commit/5bff89f0be51da3a6306a342e75517f861ba61c9

**Comment by ufanders** [comment]
Maybe so, but I had updated to v1.0.4 via the Arduino board manager and the issue persisted. I patched the code myself and it now works well.

**Comment by william-ferguson-au** [comment]
So it sounds like a problem with the Arduino board manager.

**Pull request merged**
