### PR TITLE
Add XinaBox CW02 to supported boards

### PR DESCRIPTION
**Pull request by brendanvanbreda**
We have a product based off the ESP32 WROOM-32 module.  
Information of the product can be found on our [store](https://xinabox.cc/products/cw02).
Additional info can be found on our [wiki](https://wiki.xinabox.cc/CW02_-_Wi-Fi_%26_Bluetooth_Core).

### CODE REVIEW

**Comment by me-no-dev** [comment]
great :) merged :) now you can update the WiKi to select the proper board for Arduino

**Comment by brendanvanbreda** [comment]
@me-no-dev thanx

**Comment by beegee-tokyo** [comment]
@me-no-dev 
What Wiki? Aee you talking about this [Wiki](https://desire.giesecke.tk/index.php/2018/01/30/esp32-wiki-entries/)?

**Comment by me-no-dev** [comment]
@beegee-tokyo I am talking about the [wiki](https://wiki.xinabox.cc/CW02_-_Wi-Fi_%26_Bluetooth_Core) that is linked in the PR description

**Pull request merged**
