### PR TITLE
fix(esp32): ESP32-U4WDH chip detection by ESP.getChipModel()

### PR DESCRIPTION
**Pull request by mstegen**
The ESP.getChipModel() function does not correctly identify the ESP32-U4WDH chip as used in the ESP32-MINI-1 module.
It's currently identified as a ESP32-PICO-D2 chip.

This PR fixes that by changing the name from the PICO-D2 (which was supposedly never mass produced) to the ESP32-U4WDH chip.
This closes https://github.com/espressif/arduino-esp32/issues/10683

### CODE REVIEW

**Review by me-no-dev — APPROVED** [review]

**Review by SuGlider — APPROVED** [review]
LGTM. Thank you, @mstegen !

**Comment by mstegen** [comment]
Thanks @SuGlider and @me-no-dev

**Comment by SuGlider** [comment]
> Thanks @SuGlider and @me-no-dev

wait... it was not merged.

**Comment by mstegen** [comment]
Yes, sorry about that...

**Pull request merged**
