### PR TITLE
Heltec boards defintion and update board menu chooices

### PR DESCRIPTION
**Pull request by Heltec-Aaron-Lee**
- Added Heltec Automation(TM) newest boards defintion, include WiFi_Kit_32, WiFi_LoRa_32, WiFi_LoRa_32_V2, Wireless_Stick defintions;

- Added 8MB SPI FLASH partition map;

- Update board menu chooices.

### CODE REVIEW

**Comment by me-no-dev** [comment]
is this the final one now? :)

**Comment by Heltec-Aaron-Lee** [comment]
@me-no-dev yes :D

**Comment by Heltec-Aaron-Lee** [comment]
@me-no-dev Hi, can you merge it now? :)

**Comment by me-no-dev** [comment]
Done :)

**Pull request merged**
