### PR TITLE
Fixed instances where qspi has been renamed to qio in boards.txt

### LINKED ISSUE #6958: v2.0.4 - Compilation Error
### Board

UM Feather S3

### Device Description

BME280 Module

### Hardware Configuration

N/A. Compilation error

### Version

2.04

### IDE Name

Arduino IDE and Arduino via vs.code

### Operating System

Linux (Mint 20.03)

### Flash frequency

N/A

### PSRAM enabled

yes

### Upload speed

N/A

### Description

Cannot compile sketch under 2.04 which is fine under 2.03.
Expected behavior is for the code to compile under 2.04 in the same way it does under 2.03.
`
In file included from /home/john/.arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/gcc8_4_0-esp-2021r2-patch3/xtensa-esp32s3-elf/sys-include/sys/reent.h:503,
                 from /home/john/.arduino15/packages/esp32/hardware/esp32/2.0.4/tools/sdk/esp32s3/include/newlib/platform_include/sys/reent.h:17,
                 from /home/john/.arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/gcc8_4_0-esp-2021r2-patch3/xtensa-esp32s3-elf/sys-include/stdio.h:60,
                 from /home/john/.arduino15/packages/esp32/hardware/esp32/2.0.4/cores/esp32/Arduino.h:27,
                 from /home/john/Arduino/libraries/Adafruit_IO_Arduino/src/AdafruitIO_Dashboard.h:19,
                 from /home/john/Arduino/libraries/Adafruit_IO_Arduino/src/AdafruitIO.h:19,
                 from /home/john/code/ard_OutdoorMonitor/ard_OutdoorMonitor.ino:1:
/home/john/.arduino15/packages/esp32/hardware/esp32/2.0.4/tools/sdk/esp32s3/include/newlib/platform_include/assert.h:20:10: fatal error: sdkconfig.h: No such file or directory
 #include <sdkconfig.h>
          ^~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board UM FeatherS3.
`

### Sketch

```cpp
#include <AdafruitIO.h>
#include <Adafruit_BME280.h>
#include <Adafruit_NeoPixel.h>
#include <Adafruit_Sensor.h>
#include <Arduino.h>

#include "config.h"
#include <SPI.h>
#include <Wire.h>
//#include <cmath>

#define SEALEVELPRESSURE_HPA (1018.11) // Not really used

#define UPDATETIME 1000000 * 145 // 150 seconds between updates
#define TEMPOFFSET -1.0

#define LED_BUILTIN 13

#define NUMPIXELS 1
#define PIN_NEOPIXEL 40
#define PIN_LDO2_POWER 39

Adafruit_NeoPixel strip(NUMPIXELS, PIN_NEOPIXEL, NEO_GRB + NEO_KHZ800);

Adafruit_BME280 bme; // I2C

// set up the 'temperature' and 'humidity' feeds
AdafruitIO_Feed *temperature = io.feed("xxxx");
AdafruitIO_Feed *humidity = io.feed("xxxx");
AdafruitIO_Feed *pressure = io.feed("xxxx");

void setup() {
  float temp, pres, hum;

  strip.begin(); // Initialize pins for output
  strip.setBrightness(255);
  strip.show(); // Turn all LEDs off ASAP

  pinMode(PIN_LDO2_POWER, OUTPUT);
  digitalWrite(PIN_LDO2_POWER, HIGH);

  if (!bme.begin(0x76)) {
    strip.setPixelColor(0, 0x00FF0000);
    strip.show();
    while (1)
      ;
  }

  bme.setTemperatureCompensation(TEMPOFFSET);

  io.connect();

  // wait for a connection
  while (io.status() < AIO_CONNECTED) {
  }
  if (io.status() >= AIO_NET_CONNECTED) {
    io.run();

    temp = bme.readTemperature();
    hum = bme.readHumidity();
    pres = bme.readPressure() / 100;

    temperature->save(temp);
    humidity->save(hum);
    pressure->save(pres);

    strip.setPixelColor(0, 0x0000FF00);
    strip.show();
    delay(50); // wait for a second
    strip.clear();
    strip.show();

    digitalWrite(PIN_LDO2_POWER, LOW);

    esp_sleep_enable_timer_wakeup(UPDATETIME);
    esp_deep_sleep_start();
  }

  else {
    esp_restart();
  }
}
```

### Debug Message

```plain
N/A
```

### Other Steps to Reproduce

It compiles under 2.03.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by lbernstone**
## Description of Change
bootloader naming was changed in 2.0.4.  This matches the S3 boards up with the name change.

## Tests scenarios
Untested, but should work.  Please look over to make sure I didn't completely overshoot the issue.

## Related links
Fixes #6958

### CODE REVIEW

**Comment by brentru** [comment]
@lbernstone @P-R-O-C-H-Y I tested this on the `adafruit_feather_esp32s3` with the same sketch as mentioned in https://github.com/espressif/arduino-esp32/issues/6958 and did not have compilation errors.

**Comment by SuGlider** [comment]
LGTM
I'm not sure why this memory/flash mode is in the file. 
I guess that @me-no-dev was working on getting this mode to work and left it there. 
We may want to hear from him about it before merging this PR.

**Review by SuGlider — APPROVED** [review]

**Comment by SuGlider** [comment]
Confirmed that just reverting changes to `board.txt` from last commit https://github.com/espressif/arduino-esp32/commit/666c66d3d1c7437aaebaaadf2084927b7fc476c4 has been enough to solve this issue.

I'll change this PR to reflect it. This is the minimum necessary change and it will keep @me-no-dev work at a good state.

**Comment by SuGlider** [comment]
@brentru - please apply the latest commit to this PR to your repository and let me know if everything is OK. Thanks!

**Comment by SuGlider** [comment]
OK. Just reverting  https://github.com/espressif/arduino-esp32/commit/666c66d3d1c7437aaebaaadf2084927b7fc476c4 doesn't solve the issue for other boards that are not espressif. 
Rolling back to the original PR commit.

**Comment by SuGlider** [comment]
@lbernstone first Commit solves all the issues for good. Thanks!
We shall go with it.

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Review by SuGlider — APPROVED** [review]
All fine, Retested it again compiling with: 

- ESP32S3-Dev-Module,
- ESP32S3-Box, 
- ESP32-S3-USB-OTG
- ESP32S3-CAM-LCD, 
- UM tinyS3, 
- UM FeatherS3, 
- DFRobot Firebeetle 2 ESP32-S3,
- Adafruit Feather ESP32-S3 2MB PSRAM,
- Adafruit Feather ESP32-S3 No PSRAM,
- Adafruit Feather ESP32-S3 TFT,
- Adafruit QT Py ESP32-S3 No PSRAM.

All set!

**Comment by VojtechBartoska** [comment]
Perfect, thank you @SuGlider!

**Pull request merged**
