### PR TITLE
Introduce SSLClient library based on WiFiClientSecure and rework WiFiClientSecure to use it

### PR DESCRIPTION
**Pull request by sgalabov**
## Summary
This PR reworks WiFiClientSecure into SSLClient so that it can be used with any Client-derived class.
Then it goes on to modify WiFiClientSecure to work with SSLClient in conjunction with a normal WiFiClient.
The PR was tested with ESP32 WiFi as well as with a GSM module supported by [TinyGSM](https://github.com/vshymanskyy/TinyGSM).

## Impact
Any Client-derived class can get SSL applied to it, e.g. WiFiClient, but also TinyGsmClient and any other clients.
Protocol Clients can then be put on top of SSL, e.g. [PubSubClient](https://github.com/knolleary/pubsubclient) or [ArduinoHttpClient](https://github.com/arduino-libraries/ArduinoHttpClient).
This may also allow for DTLS to be supported as well in the same style in the future, e.g. [CoAP](https://github.com/hirotakaster/CoAP-simple-library) over both WiFi and GSM, etc.

### CODE REVIEW

**Comment by me-no-dev** [comment]
Amazing work! Please allow some time to review and test :)

**Comment by me-no-dev** [comment]
You will need to edit `CMakeLists.txt` to fix the build error: https://github.com/espressif/arduino-esp32/runs/4608114525?check_suite_focus=true#step:4:41

**Comment by sgalabov** [comment]
> You will need to edit `CMakeLists.txt` to fix the build error: https://github.com/espressif/arduino-esp32/runs/4608114525?check_suite_focus=true#step:4:41

I think it's done now, sorry.

**Comment by sgalabov** [comment]
I will close and reopen a new PR with just the inclusion of SSLClient lib for now, I will see if I can deal with the rest of the errors later...

**Comment by sgalabov** [comment]
Opened https://github.com/espressif/arduino-esp32/pull/6055 instead.

**Pull request closed without merging**
