### PR TITLE
Add TXD2 and RXD2 pin definitions

### PR DESCRIPTION
**Pull request by Tinyu-Zhao**
## Related links
https://docs.m5stack.com/en/core/fire

### CODE REVIEW

**Comment by pedrominatel** [comment]
Hi @Tinyu-Zhao, 

Why don't you join all the changes into a single PR?

**Comment by SuGlider** [comment]
@Tinyu-Zhao - In order to move forward, it necessary that you agree to the terms of the CLA 
https://github.com/espressif/arduino-esp32/pull/6951#issuecomment-1176979393

**Comment by Tinyu-Zhao** [comment]
> @Tinyu-Zhao - In order to move forward, it necessary that you agree to the terms of the CLA
> [#6951 (comment)](https://github.com/espressif/arduino-esp32/pull/6951#issuecomment-1176979393)

Thank you for reminding me. I have signed the CLA.

**Comment by Tinyu-Zhao** [comment]
Combined submission to #6989

**Pull request closed without merging**
