### PR TITLE
Close files in SD manipulation functions

### PR DESCRIPTION
**Pull request by dstoiko**

### CODE REVIEW

**Comment by me-no-dev** [comment]
Thanks :)

**Comment by APokorny** [comment]
That should not be necessary unless there is a leak in the abstraction. According to my understanding VFSFileImpl runs "close" within its destructor. The compiler supplied implementation of fs::File destructor will reduce the refcount of the shared_ptr<FileImpl> which should be zero then. So that should trigger the vritual destructor of FileImpl which is implemented as close() within VFSFileImpl.

So the effect should be the same, and this change will at best only confuse users or lead to odd user code.

**Comment by APokorny** [comment]
On a second look the close method should not even exist..

**Comment by me-no-dev** [comment]
It is part of the standard Arduino API ;)

**Comment by APokorny** [comment]
make a new one :)

But is my observation correct that the change does not fix a problem?

**Comment by me-no-dev** [comment]
Could be, maybe that's why I did not add it to the samples, but then I did not have this issue at all... so... SD seems weird at times depending on the card and others

**Comment by APokorny** [comment]
One thing to note with the API is that:
```
File a  = fs.open("foo", "w");
a.write(...);
a = fs.open("foo", "r");
// Now a.read() && a.size() will return weird infrormation/behavior 
```
because the file stream for writing will be closed after another stream was opened. Maybe thats the reason why File::close exists..

**Comment by dstoiko** [comment]
@APokorny problems as reported in #272

**Pull request merged**
