### PR TITLE
Add Adafruit new board feather esp32s2 reserve tft

### PR DESCRIPTION
**Pull request by hathach**
## Description of Change
This PR add new board from Adafruit: Feather ESP32-S2 Reverse TFT https://www.adafruit.com/product/5345 . This should have no impact to other core and other boards functionality.

## Tests scenarios
Tested with master commit of arduino-esp32 and new board

@ladyada

### CODE REVIEW

**Comment by ladyada** [comment]
thanks! :)

**Review by SuGlider — APPROVED** [review]
LGTM

**Review by P-R-O-C-H-Y — APPROVED** [review]
LGTM!

**Comment by hathach** [comment]
thank you for the quick merge

**Pull request merged**
