### PR TITLE
Create WiFiClientEnterprise.ino

### PR DESCRIPTION
**Pull request by martinius96**
Sketch for ESP32 boards that allow them to connect to WPA/WPA2 Enterprise Networks.

Sketch was tested under ESP32 Devkit v1 board with Arduino Core (From May), tested Eduroam network, local RADIUS powered WPA2 Enterprise network. Connection to both networks was sucessful.

Sketch is working for WPA/WPA2 Enterprise protected networks under protocol 802.1x with methods: 
PEAP + MsCHAPv2 (another weren't tested).  Sketch working under RADIUS servers, under TACACS not.

### CODE REVIEW

**Comment by me-no-dev** [comment]
have you tested this with current Arduino?

**Comment by martinius96** [comment]
@me-no-dev I have tested it in May, when i was at University, where is Eduroam network and at school hostel, where was second Enterprise network, hosted on local RADIUS server. On both networks connections were sucessful. I have still ESP32 core build in ArduinoIDE from May. I will be back again at second half of September. Some users have problem with that sketch from USA and Russia. At us - Slovakia it was working on three tested Universities.

**Comment by me-no-dev** [comment]
I have a user who reported issue with WPA enterprise with current IDF/Arduino.

**Comment by martinius96** [comment]
I can make test. I have RADIUS server at home, i will configure it, also AP and i will try connection with my version of Arduino core and with latest and let you know.

**Comment by me-no-dev** [comment]
thank you :)

**Comment by martinius96** [comment]
Will this command:
`Serial.setDebugOutput(0);`
give me informations about authentization too?

**Comment by me-no-dev** [comment]
There is an option in the esp32 dev board menu to enable debug. set it to "info" to get logs on the WiFi/System status :)

screen shot 2018-07-15 at 11 14 03

**Comment by martinius96** [comment]
I have set it to info but i have no difference, only have my Serial.print texts, nothing else..

**Comment by martinius96** [comment]
I was unable to connect to RADIUS network with my Arduino core from June. 
I am using Linux Zeroshell 3.5.0 with RADIUS service. 
I am using also router - gateway TP-LINK WR741ND, where i have wifi security set to WPA/WPA2 Enterprise and with shared secret. I can connect with Windows 10, also with 7 (if i provide certificate manually to user connection), working with Android too. In school, where i tried sucessful connections, there were both networks under FreeRADIUS service.
Errors:
alt text
I will update to latest Arduino core and let you know.

**Comment by martinius96** [comment]
@me-no-dev suggestion?

**Comment by me-no-dev** [comment]
It tells you right up there :) HANDSHAKE_TIMEOUT

**Comment by me-no-dev** [comment]
Also!! Method private structure allocated failure :) not good!

**Comment by martinius96** [comment]
Tell me then, how was possible to join Eduroam network in my school? What was difference there, methods were same: PEAP + MsCHAPv2... Isn't there any fix for that?

**Comment by martinius96** [comment]
Set up RADIUS server isn't hard. 
I am using Linux Zeroshell = really zero shell :-) You set everything from web interface, nothing for code, etc.
 
I can send you guide for instance on e-mail, i can write it to some .pdf file. I am using older Zeroshell - version 3.5.0, i had school project on it 3 years ago. 
You need for it only standard wifi router and old pc, or... You can run your RADIUS server in VirtualBox too. Linux Zeroshell need 200MHz CPU + 80MB of RAM, 200MB of HDD space, it is very lightweight linux software.

RADIUS service is one from many that Zeroshell can run. It can work like router, or DHCP server, webserver etc too.

Download at: https://zeroshell.org/download/

**Comment by martinius96** [comment]
@me-no-dev Hey there, one Github user was trying my sketch and he successfully connected to Eduroam network in Spain. I asked him for serial monitor screenshot with Core Debug Level: Info.

Will it be helpful for you devs? It printed only sucessful methods during connection.
alt text

**Comment by me-no-dev** [comment]
looks good :) merging!

**Comment by martinius96** [comment]
Thanks a lot!

**Comment by martinius96** [comment]
Hello everyone. I got edited sketch from a researcher from a Belgian university.
Can someone test it too? He was unable to connect with original sketch but with this one he was sucessful.
`Sketch provided by: Thijs VANDENRYT
#include "esp_wpa2.h"
#include <WiFi.h>
String line; //variable for response
const char* ssid = "eduroam"; // Eduroam SSID
const char* host = "arduino.php5.sk"; //external server domain
#define EAP_IDENTITY "login@university.domain" //identity@youruniversity.domain
#define EAP_PASSWORD "password" //your Eduroam password
void setup() {
	byte error = 0;
	Serial.begin(115200);
	delay(10);
	Serial.println("Connecting to: ");
	Serial.println(ssid);
	WiFi.disconnect(true);  //disconnect from wifi to set new wifi connection

	error += esp_wifi_sta_wpa2_ent_set_identity((uint8_t *)EAP_IDENTITY, strlen(EAP_IDENTITY));
	error += esp_wifi_sta_wpa2_ent_set_username((uint8_t *)EAP_IDENTITY, strlen(EAP_IDENTITY));
	//error += esp_wifi_sta_wpa2_ent_set_new_password((uint8_t *)EAP_PASSWORD, strlen(EAP_PASSWORD));  //First time running, i think i needed to set this, although i received an error from the server, claiming the password was not set?
	error += esp_wifi_sta_wpa2_ent_set_password((uint8_t *)EAP_PASSWORD, strlen(EAP_PASSWORD)); //Following times, it ran fine with just this line (connects very fast).
	if (error != 0) {
		Serial.println("Error setting WPA properties.");
	}
	WiFi.enableSTA(true);
	
	esp_wpa2_config_t config = WPA2_CONFIG_INIT_DEFAULT();
	if (esp_wifi_sta_wpa2_ent_enable(&config) != ESP_OK) { /
		Serial.println("WPA2 Settings Not OK");
	}
	
	WiFi.begin(ssid); //connect to Eduroam function
	WiFi.setHostname("RandomHostname"); //set Hostname for your device - not neccesary
	while (WiFi.status() != WL_CONNECTED) {
		delay(500);
		Serial.print(".");
	}
	Serial.println("");
	Serial.println("WiFi connected");
	Serial.println("IP address set: ");
	Serial.println(WiFi.localIP()); //print LAN IP
}
void loop() {
    delay(5000);
 if (WiFi.status() != WL_CONNECTED) { //if we lost connection, retry
        WiFi.begin(ssid);
        delay(500);        
    }
    Serial.print("Connecting to website: ");
    Serial.println(host);
    WiFiClient client;
    if (!client.connect(host, 80)) { // HTTP connection on port 80
        Serial.println("Connection lost! - Failed response");
    }
    String url = "/rele/rele1.txt"; //read .txt file    
    Serial.print("Requesting URL: ");
    Serial.println(url);

    // This will send the request to the server
    client.print(String("GET ") + url + " HTTP/1.1\r\n" +
                 "Host: " + host + "\r\n" +
                 "Connection: close\r\n\r\n");
    unsigned long timeout = millis();
    while (client.available() == 0) {
        if (millis() - timeout > 5000) {
            Serial.println("Client timed out! - retry");
            client.stop();
        }
    }
    while(client.available()) {
         line = client.readStringUntil('\n');
        Serial.println(line);  
    }
    Serial.println();
    Serial.println("End connection");
}`

**Pull request merged**
