### PR TITLE
Added variant for Waveshare ESP32-S3-Touch-AMOLED-1.8

### PR DESCRIPTION
**Pull request by Y1hsiaochunnn**
## Description of Change
Adding variant for Waveshare ESP32-S3-Touch-AMOLED-1.8 board containing MCU, AMOLED, RTC, and IMU.

## Tests scenarios
Untested,Pre-publisher board definition

## Related links

processed USB VID PR: [espressif/usb-pids/pull/194](https://github.com/espressif/usb-pids/pull/194)

### CODE REVIEW

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Comment by Y1hsiaochunnn** [comment]
Hi, @P-R-O-C-H-Y .
I would like to know when arduino-esp32 v3.0.6 will be released, I am working on the product wiki and as mentioned before I can specify this 3rd party board with v3.0.6

**Comment by P-R-O-C-H-Y** [comment]
> Hi, @P-R-O-C-H-Y . I would like to know when arduino-esp32 v3.0.6 will be released, I am working on the product wiki and as mentioned before I can specify this 3rd party board with v3.0.6

Hi @Y1hsiaochunnn, the v3.0.6 should be released this week :)

**Comment by BitCircuit** [comment]
@Y1hsiaochunnn Hi, is the board Waveshare ESP32-S3-Touch-AMOLED-**1.75** compatible with this?

**Comment by Y1hsiaochunnn** [comment]
Hi @BitCircuit ,
I think you can use Waveshare ESP32-S3-Touch-AMOLED-1.75 as the development board option for now.

Because of the change of the i2c driver of the new version of Arduino-esp32 core, I need to debug the driver code of the hardware. Don't worry, after I debug successfully, I will push 1.75 third-party board support to arduino-esp32

**Pull request merged**
