### PR TITLE
Add ALKS board variant

### PR DESCRIPTION
**Pull request by CornyjK**
We have our own [board](https://github.com/RoboticsBrno/ArduinoLearningKitStarter), which collides with esp32 devkit pin mapping.

### CODE REVIEW

**Comment by me-no-dev** [comment]
Are you in Brno?

**Comment by CornyjK** [comment]
@me-no-dev 
Organisation @RoboticsBrno is located in Brno. I am personally not in Brno.

**Comment by CornyjK** [comment]
@me-no-dev 
You just made me curious why you ask :P

**Comment by me-no-dev** [comment]
I am in Brno :) Espressif have an office on Holandska :)

**Comment by CornyjK** [comment]
Ah, your profile states Bulgaria, I couldn't figure it out. I hope you like it here 🙂.

**Comment by me-no-dev** [comment]
love it :) what's there not to like?

**Comment by CornyjK** [comment]
Traffic situation with reconstructions :P

**Comment by me-no-dev** [comment]
I live 10 minutes from the office ;) do not get to mess with much traffic :D

**Comment by CornyjK** [comment]
You're good then, these days it would take me minimally a hour to school, fortunately it's school holidays… I am glad that I don't have to Brno those two months (although high school is more pleasant that job 😁), I bet every bus and tram has different timetables...

**Comment by me-no-dev** [comment]
you guys should ping us when you are back to Brno ;) maybe we can collaborate on some cool project :)

**Comment by CornyjK** [comment]
Sure! I am looking forward for any collaboration. If you want know our latest project (I didn't work on this one, I just helped making prototype iirc), Image of board
[there is website with images](https://mickoflus.cz/). Guess what chip it uses.

**Pull request merged**
