### PR TITLE
PeriMan: Improve log messages

### PR DESCRIPTION
**Pull request by lucasssvaz**
## Description of Change
This PR aims to improve the Peripheral Manager log messages to help debugging processes.

### CODE REVIEW

**Comment by lucasssvaz** [comment]
@SuGlider Please check if you want any other log messages for the PeriMan.

**Comment by lucasssvaz** [comment]
Further investigation shows that the CPU hangs waiting for an interrupt. The following sketch with debug level set to verbose produces this misbehavior (tested on ESP32-S3-DevKitC):

```
void setup() {
  Serial.begin(115200);
  while(!Serial) { delay(10); }

  pinMode(SOC_RX0, OUTPUT);
  pinMode(SOC_TX0, INPUT);

  delay(100);
  Serial.println("test: This should not be printed");
  Serial.flush();

  Serial.setPins(SOC_RX0, SOC_TX0);
  delay(100);
  Serial.println("test: This should be printed");
  Serial.flush();
}

void loop() {
#ifdef RGB_BUILTIN
  neopixelWrite(RGB_BUILTIN,4,0,0); // Red
  delay(1000);
  neopixelWrite(RGB_BUILTIN,0,4,0); // Green
  delay(1000);
  neopixelWrite(RGB_BUILTIN,0,0,4); // Blue
  delay(1000);
  neopixelWrite(RGB_BUILTIN,0,0,0); // Off / black
  delay(1000);
#endif
}
```

The backtrace of when the processor hangs:

```
#0  0x4037972e in esp_cpu_wait_for_intr () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_hw_support/cpu.c:121
#1  0x4200c6d8 in esp_vApplicationIdleHook () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/freertos_hooks.c:59
#2  0x4037c456 in prvIdleTask (pvParameters=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:4327
(gdb) 
```

@SuGlider Might this be related to the issue you are seeing in #8809 ?

**Comment by me-no-dev** [comment]
maybe the fact that you are modifying the default UART pins, without deinitializing the UART first, is the problem :)

**Comment by SuGlider** [comment]
these issues that Lucas has reported are solved with #8820 - including hanging while using logging.

**Comment by SuGlider** [comment]
> Further investigation shows that the CPU hangs waiting for an interrupt. The following sketch with debug level set to verbose produces this misbehavior (tested on ESP32-S3-DevKitC):
> 
> ```
> void setup() {
>   Serial.begin(115200);
>   while(!Serial) { delay(10); }
> 
>   pinMode(SOC_RX0, OUTPUT);
>   pinMode(SOC_TX0, INPUT);
> 
>   delay(100);
>   Serial.println("test: This should not be printed");
>   Serial.flush();
> 
>   Serial.setPins(SOC_RX0, SOC_TX0);
>   delay(100);
>   Serial.println("test: This should be printed");
>   Serial.flush();
> }
> 
> void loop() {
> #ifdef RGB_BUILTIN
>   neopixelWrite(RGB_BUILTIN,4,0,0); // Red
>   delay(1000);
>   neopixelWrite(RGB_BUILTIN,0,4,0); // Green
>   delay(1000);
>   neopixelWrite(RGB_BUILTIN,0,0,4); // Blue
>   delay(1000);
>   neopixelWrite(RGB_BUILTIN,0,0,0); // Off / black
>   delay(1000);
> #endif
> }
> ```
> 
> The backtrace of when the processor hangs:
> 
> ```
> #0  0x4037972e in esp_cpu_wait_for_intr () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_hw_support/cpu.c:121
> #1  0x4200c6d8 in esp_vApplicationIdleHook () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/freertos_hooks.c:59
> #2  0x4037c456 in prvIdleTask (pvParameters=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:4327
> (gdb) 
> ```
> 
> @SuGlider Might this be related to the issue you are seeing in #8809 ?

The issue with verbose was related to dead lock. Solved with #8820

**Review by P-R-O-C-H-Y — APPROVED** [review]
LGTM

**Pull request merged**
