### PR TITLE
Added ESPNow basic example

### PR DESCRIPTION
**Pull request by arvindr21**
Added a basic example for ESPNow, where a master discovers a slave dynamically and send data without connecting to it using ESPNow Technology.

Example Gist
```
ESPNOW - Basic communication - Master/Slave
   Date: 26th September 2017
   Author: Arvind Ravulavaru <https://github.com/arvindr21>
   Purpose: ESPNow Communication between a Master ESP32 and a Slave ESP32
   Description: This sketch consists of the code for the Master/Slave module.
   Resources: (A bit outdated)
   a. https://espressif.com/sites/default/files/documentation/esp-now_user_guide_en.pdf
   b. http://www.esploradores.com/practica-6-conexion-esp-now/

   Flow: Master
   Step 1 : ESPNow Init on Master and set it in STA mode
   Step 2 : Start scanning for Slave ESP32 (we have added a prefix of `slave` to the SSID of slave for an easy setup)
   Step 3 : Once found, add Slave as peer
   Step 4 : Register for send callback
   Step 5 : Start Transmitting data from Master to Slave

   Flow: Slave
   Step 1 : ESPNow Init on Slave
   Step 2 : Update the SSID of Slave with a prefix of `slave`
   Step 3 : Set Slave in AP mode
   Step 4 : Register for receive callback and wait for data
   Step 5 : Once data arrives, print it in the serial monitor

   Note: Master and Slave have been defined to easily understand the setup.
         Based on the ESPNOW API, there is no concept of Master and Slave.
         Any devices can act as master or salve.
```

### CODE REVIEW

**Comment by me-no-dev** [comment]
Please add those examples to libraries/ESP32/examples/ESPNOW/Master and Slave instead ;)

**Comment by arvindr21** [comment]
@me-no-dev Do you want them to be directly under ESPNow folder? I was planning to add more examples with multi-device communication, encryption etc. So thought sub-folder for examples would make sense?

What do you think?

**Comment by me-no-dev** [comment]
libraries/ESP32/examples/ESPNOW/Master
libraries/ESP32/examples/ESPNOW/Slave
libraries/ESP32/examples/ESPNOW/SomethingElse

or maybe even 

libraries/ESP32/examples/ESPNOW/Basic/Master
libraries/ESP32/examples/ESPNOW/Basic/Slave 

Should work ;) check in ArduinoIDE though

**Comment by arvindr21** [comment]
Presently this is the structure, similar to

> libraries/ESP32/examples/ESPNOW/Basic/Master
> libraries/ESP32/examples/ESPNOW/Basic/Slave

```
./ESPNow
├── examples
│   └── Basic
│       ├── Master
│       │   └── Master.ino
│       └── Slave
│           └── Slave.ino
├── library.properties
└── src
    └── ESPNow.h
```

And this is how it appears in ArduinoIDE: 
espnow_arduino_ide_menu

Is this okay?

**Comment by me-no-dev** [comment]
Yup :) looks great!

**Comment by me-no-dev** [comment]
Please read my comment carefully! Not in it's own library folder! ESPNOW is not Arduino library!

**Comment by me-no-dev** [comment]
screen shot 2017-09-26 at 16 04 01

**Comment by arvindr21** [comment]
Got it. Making the change now.

**Comment by arvindr21** [comment]
Not sure what I am doing wrong. Moved ESPNow to `/arduino-esp32/libraries/ESP32/examples/ESPNow/Basic/Master` and `/arduino-esp32/libraries/ESP32/examples/ESPNow/Basic/Slave`, deleted the ESPNow `library.properties` and `src`, but the files do not appear in the menu. Restarted the IDE as well. :/

**Comment by arvindr21** [comment]
NVM, working in the wrong repo, fixed it.
espnow_arduino_ide_menu v2

**Comment by arvindr21** [comment]
NVM, working in the wrong repo, fixed it.
espnow_arduino_ide_menu v2

**Comment by me-no-dev** [comment]
done :)

**Comment by arvindr21** [comment]
Thanks! Appreciate it.

**Comment by huyhl248** [comment]
Hi @arvindr21 and @me-no-dev ,
I want to communicate with ESP32 from an Android/IOS application via ESP NOW (ESP32 is a slave). How should I implement?
Thanks a lot!
Best regards,
Huy.

**Comment by arvindr21** [comment]
Hey @huyhl248 I am still figuring out the same. Do let me know if you find any leads to that. I am presently working around the smart config API and see if I can use any methods from that to initiate and maintain communication.

**Comment by me-no-dev** [comment]
there is now this example in IDF: https://github.com/espressif/esp-idf/tree/master/examples/wifi/espnow maybe will help

**Pull request merged**
