### PR TITLE
Add I2S examples and documentation

### PR DESCRIPTION
**Pull request by lucasssvaz**
## Description of Change
Adds examples and documentation for the new I2S library.

## Tests scenarios
Tested loopback example on the ESP32-LyraT and the WAV recorder example on the ESP32-S3-EYE.

### CODE REVIEW

**Comment by VojtechBartoska** [comment]
Closes https://github.com/espressif/arduino-esp32/issues/8993

**Comment by lucasssvaz** [comment]
Both examples work, just need to add the documentation and refactor the code a bit.

**Comment by me-no-dev** [comment]
@lucasssvaz please fix the conflict

**Comment by lucasssvaz** [comment]
> @lucasssvaz please fix the conflict

Done

**Pull request merged**
