### PR TITLE
add LittleFS as partition type to debug report

### PR DESCRIPTION
**Pull request by Jason2866**
LittleFS has its own Partition Sub Type. Follow up of #9340

### CODE REVIEW

**Comment by VojtechBartoska** [comment]
Thanks @Jason2866 for PR, CI does not like this proposal so far 😃

**Comment by Jason2866** [comment]
@VojtechBartoska  Yes, since the actual compiled libs are based on not actual IDF 5.1
It will compile if the are getting updated :-)

**Comment by Jason2866** [comment]
Closing since we latest changes the LittleFS support in IDF has been removed
https://github.com/tasmota/esp-idf/commit/0cbe0e0e5f0aa57a137e60b07e05566068d5cd12

**Comment by Jason2866** [comment]
Reopened since LittleFS is back in IDF5.1 https://github.com/espressif/esp-idf/commit/f21038666a531e7eb73ecc6e16cc66a4a2a0daae

**Review by lucasssvaz — APPROVED** [review]

**Pull request merged**
