### PR TITLE
Create S.ODI_Ultra_v1.0/pins_arduino.h for new board s.odi Ultra v1

### PR DESCRIPTION
**Pull request by SPELECautomations**
S.ODI Ultra v1 @MySPELEC, a new dev board based on esp32 with multiple onboard sensors.

### CODE REVIEW

**Comment by atanisoft** [comment]
@SPELECautomations Can you submit a single PR that has both boards.txt and pins_arduino.h in it? This will save @me-no-dev a bit of hassle in merging both in the right order.

**Comment by SPELECautomations** [comment]
yeah..! here's it in txt format
[S.ODI Ultra v1 board & IO Config.txt](https://github.com/espressif/arduino-esp32/files/5299509/S.ODI.Ultra.v1.board.IO.Config.txt)

**Comment by atanisoft** [comment]
> yeah..! here's it in txt format
> [S.ODI Ultra v1 board & IO Config.txt](https://github.com/espressif/arduino-esp32/files/5299509/S.ODI.Ultra.v1.board.IO.Config.txt)

I think you misunderstood... Instead of submitting both PR #4370 and PR #4369 submit just one that has both changes in it.

**Comment by SPELECautomations** [comment]
ok

**Pull request closed without merging**
