### PR TITLE
fix can not connect to empty password wifi with MultiWiFi lib

### PR DESCRIPTION
**Pull request by acevest**
1. if the passphrase is NULL, it should be initialized
```WiFiMulti.cpp:188```

2. if esp32 connected to WiFi A, and the WiFi A is turned off, the esp32 will send 
```SYSTEM_EVENT_STA_DISCONNECTED  ---reason: BEACON_TIMEOUT``` event

then, the lib will try to reconnect to WiFi A, again and again ...

so, in this case, it's better not to reconnect the original WiFi A.
```WiFiGeneric.cpp:370```

this is the test code.

```
#include <Arduino.h>
#include <WiFi.h>
#include <WiFiMulti.h>

WiFiMulti wifiMulti;

typedef struct {
  const char *name;
  const char *pwd;
} WiFiItem_t;

WiFiItem_t WiFiTable[] = {
  { "iPhone", "12345678"},
  { "Company-StaffWiFi", NULL}
};
const unsigned int WiFiCnt = sizeof(WiFiTable)/sizeof(WiFiItem_t);

void setup() {
    Serial.begin(115200);
    for(uint8_t t = 3; t > 0; t--) {
        Serial.printf("[SETUP] WAIT %d...\n", t);
        Serial.flush();
        delay(1000);
    }

    for(uint8_t i=0; i<WiFiCnt; i++) {
      //Serial.printf("Add AP %s %s\n", WiFiTable[i].name, WiFiTable[i].pwd);
      wifiMulti.addAP(WiFiTable[i].name, WiFiTable[i].pwd);
    }
}

void loop() {
    uint8_t wifi_status = wifiMulti.run();

    if((wifi_status == WL_CONNECTED)) {
      Serial.printf("WiFi connected!\n");
    } else {
      Serial.printf("WiFi not connected! wifi status %u\n", wifi_status);
    }
    delay(1000);
}
```
this is the log
```
[SETUP] WAIT 3...
[SETUP] WAIT 2...
[SETUP] WAIT 1...
[I][WiFiMulti.cpp:195] APlistAdd(): [WIFI][APlistAdd] add SSID: iPhone
[I][WiFiMulti.cpp:195] APlistAdd(): [WIFI][APlistAdd] add SSID: Company-StaffWiFi
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 1 - SCAN_DONE
[I][WiFiMulti.cpp:65] run(): [WIFI] scan done
[I][WiFiMulti.cpp:70] run(): [WIFI] 14 networks found
[D][WiFiMulti.cpp:100] run():  --->   0: [1][3E:36:BB:C7:2E:D8] iPhone (-34) *
[D][WiFiMulti.cpp:100] run():  --->   1: [11][70:10:5C:7C:57:D2] Company-StaffWiFi (-63)  
[D][WiFiMulti.cpp:102] run():        2: [11][70:10:5C:7C:57:D1] Company-LabWiFi (-63) *
[D][WiFiMulti.cpp:102] run():        3: [11][70:10:5C:7C:57:D3] Company-GuestWiFi (-63)  
[D][WiFiMulti.cpp:100] run():  --->   4: [6][70:10:5C:F2:0B:92] Company-StaffWiFi (-83)  
[D][WiFiMulti.cpp:102] run():        5: [6][70:10:5C:F2:0B:93] Company-GuestWiFi (-83)  
[D][WiFiMulti.cpp:102] run():        6: [13][30:B4:9E:6D:63:EF] L-0257 (-83) *
[D][WiFiMulti.cpp:102] run():        7: [6][70:10:5C:F2:0B:91] Company-LabWiFi (-84) *
[D][WiFiMulti.cpp:100] run():  --->   8: [6][70:10:5C:7D:EE:62] Company-StaffWiFi (-84)  
[D][WiFiMulti.cpp:102] run():        9: [6][70:10:5C:7D:EE:61] Company-LabWiFi (-84) *
[D][WiFiMulti.cpp:102] run():        10: [6][70:10:5C:7D:EE:63] Company-GuestWiFi (-84)  
[D][WiFiMulti.cpp:100] run():  --->   11: [6][70:10:5C:F2:0D:12] Company-StaffWiFi (-84)  
[D][WiFiMulti.cpp:102] run():        12: [6][70:10:5C:F2:0D:13] Company-GuestWiFi (-85)  
[D][WiFiMulti.cpp:102] run():        13: [6][70:10:5C:F2:0D:11] Company-LabWiFi (-86) *
[I][WiFiMulti.cpp:111] run(): [WIFI] Connecting BSSID: 3E:36:BB:C7:2E:D8 SSID: iPhone Channal: 1 (-34)
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:383] _eventCallback(): STA IP: 172.20.10.14, MASK: 255.255.255.240, GW: 172.20.10.1
[I][WiFiMulti.cpp:125] run(): [WIFI] Connecting done.
[D][WiFiMulti.cpp:126] run(): [WIFI] SSID: iPhone
[D][WiFiMulti.cpp:127] run(): [WIFI] IP: 172.20.10.14
[D][WiFiMulti.cpp:128] run(): [WIFI] MAC: 3E:36:BB:C7:2E:D8
[D][WiFiMulti.cpp:129] run(): [WIFI] Channel: 1
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!
WiFi connected!

// WIFI A was turned off

[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:357] _eventCallback(): Reason: 200 - BEACON_TIMEOUT   // DISCONNECTED because BEACON_TIMEOUT
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:357] _eventCallback(): Reason: 201 - NO_AP_FOUND
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:357] _eventCallback(): Reason: 201 - NO_AP_FOUND
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:357] _eventCallback(): Reason: 201 - NO_AP_FOUND
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiGeneric.cpp:342] _eventCallback(): Event: 2 - STA_START
[D][WiFiMulti.cpp:146] run(): [WIFI] delete old wifi config...
[D][WiFiMulti.cpp:149] run(): [WIFI] start scan
WiFi not connected! wifi status 6
WiFi not connected! wifi status 1
WiFi not connected! wifi status 1
WiFi not connected! wifi status 1
WiFi not connected! wifi status 1
WiFi not connected! wifi status 1
WiFi not connected! wifi status 1
WiFi not connected! wifi status 1
WiFi not connected! wifi status 1
.....
// can not reconnected anymore
```

issue id https://github.com/espressif/arduino-esp32/issues/2374

### CODE REVIEW

**Comment by acevest** [comment]
https://github.com/espressif/arduino-esp32/issues/2374

**Comment by 1TekPro** [comment]
The "NULL" requirement is not broken. BUT, I do agree there should be a handoff built into the core to handle unavailable aps.

**Comment by acevest** [comment]
> The "NULL" requirement is not broken. BUT, I do agree there should be a handoff built into the core to handle unavailable aps.

yes, it will not broken, but it should be initialized.

**Comment by me-no-dev** [comment]
so the empty passphrase I can agree on, but changing the event handler needs discussion. I think we need to rework it so this case can be handled with an argument, rather than disabling autoconnect for everyone.

**Comment by me-no-dev** [comment]
password fixed here: https://github.com/espressif/arduino-esp32/commit/ea043cdb1440f8c26147cf8a63ba8b2c13e0a47c

**Pull request closed without merging**
