### PR TITLE
Add v6 support to IPAddress to match ArduinoCore-API

### LINKED ISSUE #6600: Add localIPv6 IPv6Address.toShortString()
### Related area

WIFI IPv6Address

### Hardware specification

ESP32

### Is your feature request related to a problem?

**Feature request**

Most OLED/LCD/TFT have small width, as IPv6 can be shorted/abreviated, so its usefull to display it short as possible.

Normal IPv6 Address: 
    fe80:0000:0000:0000:32ae:a4ff:fe02:e488
    
It can be short as:
    fe80::32ae:a4ff:fe02:e488

### Describe the solution you'd like

I have implemented it at IPv6Address.h/cpp but it is overrited every time i update sdk, so i will apreciate if this feature can be part of SDK.

### Describe alternatives you've considered

I have change IPv6Address class, includding this function, that work as expected, im a beginner, so this function can be better writed.
```
String IPv6Address::toShortString() const {
	unsigned short val;
	std::stringstream stream;
	bool skip;
		
	for(int i = 0; i < 16; i+=2) {
		val = ((_address.bytes[i] << 8) | _address.bytes[i+1]);
		
		if ( val == 0 ) {
			if ( ! skip ) {
				skip = true; 
				stream << ":"; 
			}
		} else {
			if ( skip ) skip = false;
			
			stream << std::right << std::setfill('0') << std::setw(4) << std::hex << static_cast<int>(val);
			
			if ( i < 14 ) stream << ":";
		}
	}
	
	return String( stream.str().c_str() );
}
```

### Additional context

_No response_

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

### PR DESCRIPTION
**Pull request by sgryphon**
*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

### Checklist
1. [X] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [X] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [X] Please **update relevant Documentation** if applicable
4. [X] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
Please describe your proposed Pull Request and it's impact.

Update the IPAddress class to support v6 addresses, using the same interface changes as ArduinoCore-API (and thus compatible with other Arduino based platforms).

Note that the actual API changes are minimal:
* add a type() getter and corresponding enum
* add three new constructors: one for 16 octets, empty with type specifier, and byte pointer with type specifier
* add constant for IP6ADDR_ANY (similar function as IPADDR_NONE)

The changes are backward compatible, i.e. any IPv4 code will continue to get the same outputs for a given inputs. (There are extensive unit test cases in ArduinoCore-API).

Note: Whilst backwards compatible, this change does increase the memory footprint from 4 bytes to 20 bytes (assuming the enum compiles as an underlying int32_t). 

## Tests scenarios
Please describe on what Hardware and Software combinations you have tested this Pull Request and how.

(*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with ESP32 and ESP32-S2 Board with this scenario*)

**NOTE:** I am not sure how to build and test the project as I can't find instructions in the readme or contributing files. I can see the github actions scripts, but they are a bit more complicated that the ArduinoCore-API project, so I haven't reverse engineered out the steps to run all the tests yet (or the dependencies what is needed).

I am putting this code up for review while I figure this out (and maybe GitHub can run the tests).

Note that the code is mostly cut and paste from ArduinoCore-API project, which has unit tests, so should work. (The only bit not directly copied was the toString() function changes).

## Related links
Please provide links to related issue, PRs etc.

(*eg. Closes #number of issue*)

Related to #7114, although it doesn't make it directly compatible with ESP8266 but with ArduinoCore, but does close off the issue.

Essentially fixes #6600 as it uses the RFC 5952 canonical format, which includes shortening of the left-most largest group of two or more zero fields. (The simple example in #6600 simply did the first zero fields). Note that the fromString() function parses all IPv6 representations, not just the canonical one. (There are extensive unit tests in the ArduinoCore-API project)

It is related to #6242 as it provides core support for the IPAddress class to have both v4 and v6 addresses, enabling support to be added (internally) to other classes (such as WiFi, Ethernet, etc) to handle IPv6 (without having to complicate their interfaces).

### CODE REVIEW

**Comment by sgryphon** [comment]
I have not been able to run the tests locally, but did get them running (and now all successful / green) in my GitHub repo. Link to the successful run is here: https://github.com/sgryphon/arduino-esp32/actions/runs/2931290749

This PR says it needs a contributor to approve first-time running of the workflows.

**Comment by sgryphon** [comment]
Concern: Regarding the != operator. 

* Usually the == and != operators should be specified together, as often they are used interchangeably, e.g. I would expect "!(a == b)" to give the same result as "a != b" (although not always the case, e.g. nullability in SQL).
* The != operator does not exist in the current IPAddress.
* When I add it, it fails some tests where the is ambiguity of "ip != 0" between implicit conversion of IPAddress to int, and then compare two int, vs conversion of 0 to IPAddress, and then comparison of IP address.
* To fix this, I think that the conversions could be marked explicit.

While adding the != operator is backwards compatible (it adds more), changing the existing conversion to be explicit would be a (fairly small) change in existing functionality.

Personally I think the missing != is a bug, that needs to be fixed, even if it breaks existing implicit conversion.

**Comment by mrengineer7777** [comment]
I see ArduinoCore does not have an IPv6 library.  Opinion: If we are added v6 support to IPAddress, we should delete IPv6Address library.

**Comment by sgryphon** [comment]
> Opinion: If we are adding v6 support to IPAddress, we should delete IPv6Address

That would be a breaking change. It is okay to do this for a major version, but usually you would want to have the replacement already added (i.e. add this backwards compatible change first), then foreshadow & let people know (mark the old code deprecated, if the language supports this, and tell them to use the new). 

Then a future version would remove the code.

e.g. a plan could be to add the IPv6 support first; if that is going to be release v3.0.0, then add a comment that IPv6Address will be removed in v4.0.0 and to use IPAddress instead (and then remove it in v4).

**Comment by me-no-dev** [comment]
@sgryphon are you around to rebase this? And if possible, update it to the latest API from Arduino? We would like to merge it now :)

**Comment by sgryphon** [comment]
> @sgryphon are you around to rebase this? And if possible, update it to the latest API from Arduino? We would like to merge it now :)

Thanks for the ping. I will have a look, but shouldn't take too long.

**Comment by me-no-dev** [comment]
>  I will have a look, but shouldn't take too long.

Just copying the latest IPAddress from ArduinoCore-API should be sufficient :) there are a couple changes since you submitted this PR.

**Comment by sgryphon** [comment]
I have rebased, and added the recent (minor) changes from ArduinoCore... but I see you now have a commit message linter, so will also need to clean them up (I may get time over the weekend, let me see).

**Comment by me-no-dev** [comment]
> but I see you now have a commit message linter

Don't worry, we are still experimenting with it :) Thanks for updating the files!

**Comment by sgryphon** [comment]
I've updated the commit messages to match the linter format.
BTW when I did the initial rebase I also squashed.
Before merging I did do a three-way compare and nothing had changed in arduino-esp32 since; and then I applied the changes from arduinocore api (some, e.g. toString) already existed in -esp32

**Comment by me-no-dev** [comment]
@sgryphon could you please sign the CLA (second message in the thread)

**Comment by sgryphon** [comment]
> @sgryphon could you please sign the CLA (second message in the thread)

CLA is signed.

**Comment by sgryphon** [comment]
If anyone wants to have a discussion on wider IPv6 (not just IPAddress, which should be aligned with ArduinoCore), I created a general IPv6 discussion that can be used: https://github.com/espressif/arduino-esp32/discussions/9009

**Comment by s-hadinger** [comment]
Let me explain more for those who are not familiar with link-local IPv6. Link-local addressed are used extensively by Matter protocol.

If you have multiple network interfaces, there is no way to for sure which network interface is used by which link-local addresses. Hence an additional information `zone` is used to track which interface must be used.

In text representation, they are separate with `%`, example: `fe80::86cc:a8ff:fe64:b768%st1` is a link-local address on wifi `st1`, `fe80::86cc:a8ff:fe64:c768%en2` is on Ethernet

**Comment by me-no-dev** [comment]
@s-hadinger check and comment https://github.com/espressif/arduino-esp32/pull/9016 please

**Comment by TD-er** [comment]
There is something still wrong with the implementation of this code.

When I try to get the client IP (`webserver.client().remoteIP()`)  I now only get the last byte.
Thus 192.168.10.129 is now shown as 129.0.0.0

Looks like an alignment issue, so maybe on another build with only minor changes it might be shifted differently?

**Comment by sgryphon** [comment]
> PR that doesn't take into account

Small steps.

That PR was mostly written 1 year ago, to align with ArduinoCore (which does not have zone ID). ArduinoCore in turn was actually focussed for mobile (4G) devices, with a single interface assigned a global address, because carriers are moving to IPv6 only networks... so quite a different case that Matter / Thread.

The new PR (linked) integrates in the zone ID ... and I suggesting contributing it back to ArduinoCore, for consistency between platforms.

I also added a section to the discussion I created https://github.com/espressif/arduino-esp32/discussions/9009

Because yes, people misunderstand things like link-local, e.g. confusing it with local, as opposed to remote (the ends of a connection) and link-local vs global (different scopes).

**Pull request merged**
