### PR TITLE
Added 2 ffat partition schemes for 4MB modules + improved descriptions.

### PR DESCRIPTION
**Pull request by marcmerlin**
Existing format options were unclear on how much spiffs you were
getting. Also add missing 1MB App/3MB Spiffs split.
This addresses https://github.com/espressif/arduino-esp32/issues/1799

This makes it very clear what each option gives you, and also adds 2 options
to get ffat on 4MB chips..

### CODE REVIEW

**Comment by marcmerlin** [comment]
This gives more details on how to create FFat and flash it from a computer: http://marc.merlins.org/perso/arduino/post_2019-03-30_Using-FatFS-FFat-on-ESP32-Flash-With-Arduino.html

**Comment by marcmerlin** [comment]
Hi @me-no-dev @CelliesProjects you just committed https://github.com/espressif/arduino-esp32/commit/4930853edb94313b1078dd2a01a3f8568d46f707 which caused a conflict with this PR which offers more and better descriptions.
I just resolved it, but can you please consider this change this does more than what you just merged?

**Comment by me-no-dev** [comment]
alright @marcmerlin :D I am on merging spree so no worries :) this is next!!

**Comment by marcmerlin** [comment]
Thanks @me-no-dev . I sent you a small tweak to extend the space allocation to the default partitions too (including the ffat one you just added)
https://github.com/espressif/arduino-esp32/pull/2649

**Comment by FrenchLab47** [comment]
Hello,
I'm doing tests with the new ffat partitions and I noticed an error on the default_ffat.csv partition.
This new partition causes a permanent reset.
I did not have this problem with the previous partition that contained an EEPROM partition.
It works when I replace the line:
`ffat,     data, fat,     0x291000,0x170000,`
by :
`ffat,     data, fat,     0x290000,0x170000,`

**Pull request merged**
