### PR TITLE
Quote {build.source.path} to allow spaces in path

### PR DESCRIPTION
**Pull request by tttapa**
Previously sketches or examples that had spaces anywhere in their absolute path caused a total build failure. By adding quotes around the path in `platform.txt`, they now build correctly.

Consider a “bare minimum” sketch in `/home/pieter/Arduino/folder with spaces/Sketch/Sketch.ino`. Previously, the bash command generated for copying the `partitions.csv` file was:
```sh
bash -c "[ ! -f /home/pieter/Arduino/folder with spaces/Sketch/partitions.csv ] || cp -f /home/pieter/Arduino/folder with spaces/Sketch/partitions.csv /tmp/arduino_build_324565/partitions.csv"
bash: line 0: [: too many arguments
cp: target '/tmp/arduino_build_324565/partitions.csv' is not a directory
exit status 1
```
With the proposed changes, the path in the bash command is now correctly quoted, and the build succeeds:
```sh
bash -c "[ ! -f \"/home/pieter/Arduino/folder with spaces/Sketch\"/partitions.csv ] || cp -f \"/home/pieter/Arduino/folder with spaces/Sketch\"/partitions.csv /tmp/arduino_build_324565/partitions.csv"
```

This pull request addresses issues #4579 and #4640.

People use spaces in folder names, and this works correctly in version 1.0.4 of this ESP32 core and all other Arduino cores I've tried. It no longer works in version 1.0.5 (after commit 9ef3e2d2a6b79c951f894dba1dd71c811317ca6e), so I believe this is well worth fixing, especially since it's such a simple change.

### CODE REVIEW

**Comment by me-no-dev** [comment]
quotation does not look alright. this needs testing :)

**Comment by tttapa** [comment]
The confusing thing about the quotation is that the Arduino IDE seems to handle quotes differently when they are next to a placeholder:

```
"outer string "inner string {placeholder} more inner string" more outer string"
```
gets converted into 
```
"outer string "inner string value more inner string" more outer string"
```
which is obviously incorrect. On the other hand,
```
"outer string "{placeholder}" more outer string"
```
becomes 
```
"outer string \"value\" more outer string"
```
which is correct in this case.

This is kind of uncommon, though, and I couldn't find any mention of this behavior in the [platform specification docs](https://arduino.github.io/arduino-cli/platform-specification/).

I've tested this using the Arduino IDE v1.8.9 and 1.8.13 on Ubuntu 20.04, as well as with the `arduino-cli` directly for my CI builds and it works correctly. The bash commands it generates look correct to me (enable verbose output in the preferences to see them, the output is also in my previous message) and the `partitions.csv` file gets copied to the build folder if it exists, no matter if the sketch path contains spaces or not.

**Comment by me-no-dev** [comment]
what if we pre-escape the whole paths so that `partitions.csv` is also escaped. I also need to test this with Sloeber and make sure that paths expand as they should

**Comment by tttapa** [comment]
Why does `partitions.csv` need to be escaped? It doesn't contain any spaces or special characters.

Bash should handle this correctly, multiple strings (quoted or not quoted) that are right next to each other are combined into a single string.

For example:
```
$ echo "quoted&:'string"suffix
> quoted&:'stringsuffix
$ ls "$HOME"/.profile
> /home/pieter/.profile
```

**Comment by me-no-dev** [comment]
because the commands are used by other builders and IDEs. It makes most sense that the full path is escaped, not just part of it.

**Pull request merged**
