### PR TITLE
Ticker fix solving #6155

### PR DESCRIPTION
**Pull request by PilnyTomas**
EDIT: The example Arguments was written incorrectly and it is now fixed.

~~In `Ticker.h` the functions using `template<typename TArg>` are now wrapped with `#pragma GCC diagnostic ignored "-Wcast-function-type"` to suppress Warning messages related to the `reinterpret_cast` such as `warning: cast between incompatible function types from 'void (*)(int)' to 'Ticker::callback_with_arg_t' {aka 'void (*)(void*)'} [-Wcast-function-type]`~~

Solving https://github.com/espressif/arduino-esp32/issues/6155

### CODE REVIEW

**Comment by PilnyTomas** [comment]
Changed edits from previously ignoring `-Wcast-function-type` to fixing example Arguments which was written incorrectly.

**Review by pedrominatel — COMMENTED** [review]
I was not able to reproduce this example.

Here is my working sketch:

```
#include <Arduino.h>
#include <Ticker.h>

// attach a LED to GPIO 5
#define LED_PIN 5

Ticker tickerSetHigh;
Ticker tickerSetLow;

// Argument to callback must always be passed a reference
void setPin(uint32_t state) {
  digitalWrite(LED_PIN, state);
}

void setup() {
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, HIGH);
  
  // every 25 ms, call setPin(0) 
  uint32_t state = 0;
  tickerSetLow.attach_ms(25, setPin, state);
  
  // every 26 ms, call setPin(1)
  state = 1;
  tickerSetHigh.attach_ms(26, setPin, state);
}

void loop() {

}
```

**Review by P-R-O-C-H-Y — APPROVED** [review]
I confirm this fixes the compiler warning. 
@pedrominatel Did you set `Compiler warnings -> All` in Arduino IDE?

**Comment by VojtechBartoska** [comment]
@me-no-dev This is ready to be merged.

**Pull request merged**
