### PR TITLE
LILYGO T-Display S3 has 512kb SRAM

### PR DESCRIPTION
**Pull request by Eistee82**

### CODE REVIEW

**Comment by Jason2866** [comment]
The SRAM is memory mapped and usable is the actual value.

**Comment by me-no-dev** [comment]
I will close this for now and investigate later if numbers needs adjusting

**Comment by Randomblock1** [comment]
Yep, look at the datasheet: ["512 KB on-chip SRAM"](https://www.espressif.com/sites/default/files/documentation/esp32-s3_datasheet_en.pdf#subsubsection.3.1.2) 
Meanwhile the ESP32-S2 [has 320Kb SRAM](https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf#e)
This should definitely be reopened, it seems like a pretty big issue to me.

**Comment by me-no-dev** [comment]
@Randomblock1 yet, when you flash the chip, you do not have access to the full amount of SRAM. 512KB is not the amount that should be put in the board config.

**Pull request closed without merging**
