### PR TITLE
Add support for ffat on 4MB ESP32 Dev Module and mhetesp32minikit board.

### PR DESCRIPTION
**Pull request by CelliesProjects**

### CODE REVIEW

**Comment by lbernstone** [comment]
Seems like this should probably go on esp32-dev for testing before a variant....

**Comment by CelliesProjects** [comment]
Will do.

**Comment by CelliesProjects** [comment]
@lbernstone  Commit 59355f9 should add ffat to the dev module.
Or should I make a separate PR for both boards?

**Comment by CelliesProjects** [comment]
@me-no-dev @lbernstone Bump.
I would really like to be able to use FFAT with the Arduino IDE.

**Comment by marcmerlin** [comment]
@lbernstone @me-no-dev if you'd like an alternate option for esp32-dev that adds multiple ffat options as well as much clearer split of app vs spiffs/ffat space allocation, please have a look at https://github.com/espressif/arduino-esp32/pull/2623

**Comment by me-no-dev** [comment]
hey guys sorry for the delay :) nice to see you around!

**Pull request merged**
