### PR TITLE
Avoid global defines for default ETH configs

### PR DESCRIPTION
**Pull request by antlanc7**
I just moved the default values directly into the prototype, in order to delete the defines that are visible to the whole user project.

### CODE REVIEW

**Comment by mrengineer7777** [comment]
This appears to reduce flexibility.  What issue does this solve?

**Comment by mrengineer7777** [comment]
The whole point of those defines is so you can define them previously (e.g. in sdkconfig.h) and then they will be automatically included.  Put your defines in a .h file and include it before including ETH.h.

**Comment by mrengineer7777** [comment]
Or use your custom defines (use different names) directly in the function call:
```
if(!ETH.begin(EC_PHY_ADDR, EC_PHY_RST, EC_PHY_MDC, EC_PHY_MDIO, ETH_PHY_KSZ8081, ETH_CLOCK_GPIO0_IN, false)) {
        log_e("ETH failed to start");
    }
```

**Comment by antlanc7** [comment]
Ok so I'm supposed to use the same names in a previously included header file in order to call ETH.begin with redefined default values. Thank you for the clarification

**Pull request closed without merging**
