### PR TITLE
Update espota.py with utf-8

### PR DESCRIPTION
**Pull request by Timmmy001**
Add 'utf-8' option for correct password-handling with special character ä,ü,ö,ß, etc.
See [Python info](https://coderwall.com/p/mvwzcw/python-hashlib-and-unicode)
Fix: #3615

### CODE REVIEW

**Comment by Wolftronics-SBC** [comment]
hi please modified uft-8 to utf-8-sig working "uft16 languages"

**Comment by Timmmy001** [comment]
@Wolftronics-SBC : I do it. But beware: This is now a breaking change!
I think this is not a very good idea:
Password | code : hash
admin |               :  21232f297a57a5a743894a0e4a801fc3
admin | utf-8       :  21232f297a57a5a743894a0e4a801fc3
admin | utf-8-sig :  dad6faebab54e34a71faee9455e78a61
admin | utf-16     :  2e05d1660c002f82c6100cac1eda1235

**Comment by Wolftronics-SBC** [comment]
string.encode() python default option utf-8 what you sent in modification is practically doing nothing... but we need to analyze the code better... returns to utf-8 in this row "sock2.sendto(message.encode(), remote_address)" in principle, encode() should not be here, because the variables have already been assigned the character encoding...

**Comment by Timmmy001** [comment]
Yeah, you're right.
The espota.pl file also works without modifications. :-|
But the compiled exe differs from the behaviour.
I have compiled the file myself as .exe and it now works with special characters.

Can someone trigger the recompilation in GitHub?

**Comment by lbernstone** [comment]
This should be submitted and vetted at [esp8266/arduino](https://github.com/esp8266/Arduino/blob/master/tools/espota.py) first.

**Pull request closed without merging**
