### PR TITLE
Removed use of TAG from logging

### PR DESCRIPTION
**Pull request by Bascy**
Arduino implementation of LOG_x doesnt use TAG parameter, so it can be removed from LOG_x statements

### CODE REVIEW

**Comment by me-no-dev** [comment]
oh noo :D you must have missread my comments. Arduino's log is NOT `ESP_LOGX(` it is `log_x(...`

**Comment by me-no-dev** [comment]
you know what... I will just accept your previous PR and batch replace those myself :)

**Comment by Bascy** [comment]
Oh sorry, my bad, will try again and await the completing of the build process this time :(

**Comment by Bascy** [comment]
Hmmmm, it will not work anymore if `CONFIG_ARDUHAL_ESP_LOG` is not defined ...
Is that possible?

#if defined(ARDUINO_ARCH_ESP32) && defined(CONFIG_ARDUHAL_ESP_LOG)
#include "esp32-hal-log.h"
#else
#include "esp_log.h"
static const char* LOG_TAG = "BLEAdvertising";
#endif

**Comment by me-no-dev** [comment]
you can remove that whole if/else thing and replace it with only `#include "esp32-hal-log.h"`

**Comment by me-no-dev** [comment]
code was intended to detect if Arduino is installed and forward the log to it

**Pull request closed without merging**
