### PR TITLE
Add Core Debug Level for WeMosBat

### PR DESCRIPTION
**Pull request by stickbreaker**
Should we add this declaration option for all boards?

### CODE REVIEW

**Comment by JamesGKent** [comment]
adding it for all boards would simplify asking people to turn on logging for debug purposes...
i'd vote in favour of adding it, even though same thing can be achieved by using the ESP Dev module board option...

**Comment by stickbreaker** [comment]
@JamesGKent As long as the pin definitions and Flash speeds are the same.

Chuck.

**Comment by JamesGKent** [comment]
@stickbreaker i hadn't considered that, in which case i'd definitely advocate that the debug menu should be added to all boards

**Comment by me-no-dev** [comment]
I think that a better way should be found to organize the boards better. the config file is a zoo of boards that are actually all the same...

**Pull request merged**
