### PR TITLE
enable and fix core compiler warnings

### PR DESCRIPTION
**Pull request by liebman**
Enable compiler warnings in platform.txt and fix warnings found in core and core libs. (See #3647)

Some notes:
- No files under `tools/sdk` were modified
- warnings from files located under `tools/sdk` were ignored by protecting the include of such files with:
```c
#pragma GCC diagnostic push 
#pragma GCC diagnostic ignored "-Wsign-compare"
#include "freertos/FreeRTOS.h"
#pragma GCC diagnostic pop
```
- CI tests compiling examples in AzureIoT were disabled as this is from a seperate repo and can't be fixed directly here.

### CODE REVIEW

**Comment by me-no-dev** [comment]
build is failing :) plus I am not sure that the math there will help if you just cast like that ;)

**Comment by liebman** [comment]
> build is failing :) plus I am not sure that the math there will help if you just cast like that ;)

If you talking about the signed vs unsigned comparisons it should be the same as what the compiler would do anyway (cast the signed value to unsigned) but without the warnings.

Build failing I expected, and why I marked it as a WIP.

**Comment by liebman** [comment]
@me-no-dev I don't understand why this error happens on CI but not (and not even a warning) compiling with Arduino IDE (or platformio). Do you know where/how `cpu.h` is included? I can't find anything including it using `grep -r`.
```
Compiling 'WiFiClient.ino' ...
In file included from /Users/runner/Documents/Arduino/hardware/espressif/esp32/tools/sdk/include/freertos/freertos/portable.h:89:0,
                 from /Users/runner/Documents/Arduino/hardware/espressif/esp32/tools/sdk/include/freertos/freertos/FreeRTOS.h:105,
                 from /Users/runner/Documents/Arduino/hardware/espressif/esp32/cores/esp32/Arduino.h:32,
                 from /Users/runner/.arduino/build.tmp/sketch/WiFiClient.ino.cpp:1:
/Users/runner/Documents/Arduino/hardware/espressif/esp32/tools/sdk/include/soc/soc/cpu.h: In function 'void cpu_configure_region_protection()':
/Users/runner/Documents/Arduino/hardware/espressif/esp32/tools/sdk/include/soc/soc/cpu.h:77:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     for (int i = 0; i < sizeof(pages_to_protect)/sizeof(pages_to_protect[0]); ++i) {
                       ^
cc1plus: some warnings being treated as errors
```

**Comment by me-no-dev** [comment]
```cpp
for (size_t i = 0; i < sizeof(pages_to_protect)/sizeof(pages_to_protect[0]); ++i) {}
```

**Comment by me-no-dev** [comment]
CI builds with all warnings and errors ON

**Comment by liebman** [comment]
> CI builds with all warnings and errors ON

Passing now!

**Comment by liebman** [comment]
Closing

**Pull request closed without merging**
