### PR TITLE
WiFiSTA - method setDNS as in WiFi libraries by Arduino

### PR DESCRIPTION
**Pull request by JAndrassy**
Arduino doc: https://www.arduino.cc/reference/en/libraries/wifi/wifi.setdns/

I write about the motivation for this in the other [PR](https://github.com/espressif/arduino-esp32/pull/8853)

### CODE REVIEW

**Comment by me-no-dev** [comment]
Thanks for the PR, but we will probably go another way. On our platform, the DNS servers are set for all client interfaces and are not specific to a given one, meaning, if you have ETH and WiFi together, they will use the same DNS servers for both connections. The API as such is and will be misleading.

**Comment by JAndrassy** [comment]
the reason to do Arduino platform and libraries is not because it has good, clear and not confusing API

**Comment by me-no-dev** [comment]
yes, now go explain that to the users who complain that we allow setting DNS to interfaces, while it actually sets it globally.

**Comment by me-no-dev** [comment]
merging now, will add notes about compatibility as part of the rework

**Comment by JAndrassy** [comment]
> On our platform, the DNS servers are set for all client interfaces and are not specific to a given one

so the DNS server returned with DHCP on some interface is added to global registry of DNS servers? even if it is 192.168.0.1 which is not valid for network interfaces connected to a different LAN?

**Comment by me-no-dev** [comment]
I'm not sure I understood your question clearly, but to explain slightly better:

DNS and interface addresses are not necessarily connected. DNS servers only resolve names to addresses and are expected to always return the same addresses, regardless of your local network address. Google.com will always resolve to google's servers for example. From then on, it's up to your network routing to figure out which interface to use and how to get to the resolver IP address from DNS and reach the target server. So having the same DNS is nothing bad or wrong, as long as your ESP has a way to reach the DNS IP and then the resolved IPs

**Pull request merged**
