### PR TITLE
Add platform specific flash speed to magicFlashChipSpeed

### PR DESCRIPTION
**Pull request by TD-er**
## Description of Change

Various ESP32-variants like the C6, H2, etc. differ in their used flash frequencies.

Also the maximum possible flash size wasn't handled in `magicFlashChipSize`

## Related links

Used the info from [esptool.py](https://github.com/search?q=repo%3Aespressif%2Fesptool%20FLASH_FREQUENCY%20&type=code)

### CODE REVIEW

**Review by Jason2866 — APPROVED** [review]

**Comment by Jason2866** [comment]
@me-no-dev What do you think about adding C2 Arduino support? I have added in our fork and project Tasmota does run stable on the C2.
The needed changes are mostly just additional #ifdefs. The change in this PR is the only specific C2 related one and the changes are also needed for the H2 and the C6.

**Comment by me-no-dev** [comment]
@Jason2866 feel free to add the C2 changes. We do not promise that it will be available through the board manager, but nothing wrong in having it supported "as-component" and even as an option through the lib-builder. Just do not want to add additional megabytes to download for rarely used chip.

**Comment by TD-er** [comment]
Just curious, why do you think the C2 will only be used rarely?

It looks like it will be a preferred module/chip for those vendors of cheap "smart" devices, like the Sonoff Basic used to be back in the days.
It isn't the best ESP32 variant, but still it is quite capable and you really don't need lots of CPU power for switching simple stuff.

**Comment by me-no-dev** [comment]
@TD-er what I mean is that I do not see many development boards popping out and many of our users going for such a limited chip, when C3 and C6 could do so much more for the same money. Just that C2 is a bit too limited for the general public. I agree that specific optimized designs can be achieved and costs can be saved in mass production, just not the home user. That is why we can offer option for those that want to venture, but not load the 99% of the users with additional 100+ MB that they will never need. There is some initiative to split the core into separate chips and have the users install only what they have, but Arduino's platform is not yet supporting everything necessary for that to work. If/when that happens, we will surely add full support for C2 and maybe more future budget chips. Then even things like ESP32-Solo could be supported. I know there are some devices that use it.

**Comment by Jason2866** [comment]
@me-no-dev  I am perfectly fine with not adding to the boards manager, tbh i don't like it all. But that's not your thing, it is coming from ArduinoIDE. It would be a great step to have all needed C2 changes in source code. So everyone can build the framework with the Arduino Lib Builder (just a few changes there). BTW adding C2 does not add a lot of Mbytes. It is way less than Speech Recognition or Rainmaker does add. Our forked Framework with supporting additionally the C2 has 150Mbyte at all (stripped the fat SR and Rainmaker stuff).

Since extracting the C2 parts out of our Arduino fork is "some" work, i can and will only do a PR if it will be merged fast (with the things you mentioned) so that no rebase work needs to be done.

**Comment by me-no-dev** [comment]
@Jason2866 I don't see a problem to merge C2 support fast, as long as you cover it fast enough here.

**Pull request merged**
