### PR TITLE
Added ESP:: functions for sketch size

### PR DESCRIPTION
**Pull request by lbernstone**

### CODE REVIEW

**Comment by lbernstone** [comment]
Fixes #1707

**Comment by Jeroen88** [comment]
Nice, could you add getSketchMD5() too? Then I will incorprate these in my PR #1979 :)

**Comment by lbernstone** [comment]
Metadata for esp32 images includes SHA-256 hash.  Is that useful?

**Comment by Jeroen88** [comment]
@lbernstone Before updating, the ESP client adds a header for the server with the MD5 of the sketch _running_. I think this header is not used much by servers, but I think that the idea was to give the server the opportunity to match the sketch currently running with data on the server for some business logic. To keep it compatible with the ESP8266, I do not need the MD5 of the sketch being downloaded, but the MD5 of the present sketch. That function is not available yet, is it?

**Comment by lbernstone** [comment]
MD5 would have to be calculated, which would likely take a minute of 100% cpu and blocked SPI.  SHA256 is stored in the metadata, and is directly available through an [IDF function](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/storage/spi_flash.html#_CPPv224esp_partition_get_sha256PK15esp_partition_tP7uint8_t).

**Comment by Jeroen88** [comment]
I double checked ESP8266HTTPUpdate and EspClass::getSketchMD5, and for the ESP8266 indeed the MD5 of the running sketch is added to the request headers. Also, it is computed on the fly, and not stored in some flash header or so, so at least for the ESP8266 it is fast enough. 
To be compatible with the ESP8266 it would be better to add MD5, but my impression is that it is not used very often. A SHA-256 would be a good alternative then. 
When I have some time, I will add skech size and SHA-256 to the HTTPUpdate class of PR #1979

**Pull request merged**
