### PR TITLE
Porting ESP8266WebServer to ESP32 (Issue #425)

### PR DESCRIPTION
**Pull request by salqadri**
Solving issue #425 by porting ESP8266WebServer to ESP32. Also ported most examples, except WebUpdate, SDWebServer and FSBrowser.

### CODE REVIEW

**Comment by me-no-dev** [comment]
We are working on a different approach. It's pointless to support the same code on both places, so we will move libs like the WebServer to their separate repositories and make the code ESP8266 and ESP32 compatible.
I'll leave the PR open in case someone wants to run the WebServer while we are working on getting this resolved.

**Comment by yeralin** [comment]
@me-no-dev Please, notify when this will be done bc current SimpleWiFiServer implementation is crazy confusing 👎

**Comment by hallard** [comment]
@me-no-dev, are you talking about implementing the async version ?
I'm trying my first port to ESP32 and I'm facing the same problem with my code not using async.

**Comment by me-no-dev** [comment]
@hallard async is a complicated thing on ESP32 ;) you need to wait  for me to port it.

**Comment by hallard** [comment]
@me-no-dev 
thanks for the information, I though while getting things common, Web server for ESP32 and ESP8266 will be async, that was a wrong assumption, sorry for that.
Does this mean that ESP32 will also have WEBServer "classic" and "Async" ?
I'm now trying to migrate my project to ESP32 (need 2 real serials) but to be honest, with currently missing SPIFFS (official) and AsyncWebServer for now, I must postone all my PCB boards design with ESP32.
SPIFFS+AsyncWEB works so fine and so fast that it should be part of core and replace old WebServer (from my point of you) ;-)

**Comment by euquiq** [comment]
Hi!
 Hopefully I am posting this in the right place. I've been searching a bit on how to create a secure web server  ...

I could only find a  ESP32 TSL v1.2 Webserver for Espressif's ESP-IDF framework, but not for Arduino. 

I am hoping this is the right place to ask you guys to consider adding secure web server functionality into this porting of esp2866webserver into esp32webserver, since (if I correctly understand) the ESP32 includes the necessary hardware for doing the trick.

Maybe it is already done, by some other method, but I could not find anything over the web about it.

Thanks,

Enrique

**Comment by beegee-tokyo** [comment]
@euquiq 
I am using [WebServer-esp32](https://github.com/zhouhan0126/WebServer-esp32) until a web server is available here. Not sure if it fulfills your requirements though.

**Comment by euquiq** [comment]
@beegee-tokyo Hi! Yeps, I am using a variant, similar or identical as that library. But I would love to get my ESP32's serving their webpages through port 443 in a secure / encrypted way. I suspect it should be easy enough, since there are demos featuring such task for the IDF platform. I am trying to understand how are they accomplishing it in order to try and replicate something like that in ARDUINO platform, but I suspect some stuff might be missing at this time on the arduino side.

**Comment by henricazottes** [comment]
@euquiq  any progress on secured webserver ? I'm trying to achieve exactly the same but my research is not very successful :/

**Comment by copercini** [comment]
Will close this PR because now the main repo is supporting webserver =)
https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer

**Pull request closed without merging**
