### PR TITLE
add python3 support to gen_esp32part.py

### PR DESCRIPTION
**Pull request by briancappello**
Tested with Python 2.7 and Python 3.6; should work on 2.6+ (<2.6 does not support the b'' notation)

### CODE REVIEW

**Comment by me-no-dev** [comment]
great! let's give this a go :)

**Comment by me-no-dev** [comment]
Could I bother you to please create this PR in https://github.com/espressif/esp-idf ?
That way everyone will get that better code :)

**Comment by briancappello** [comment]
Hmm the `gen_esp32part.py` in that repo already works with Python 3! So I guess this PR is unnecessary; just this repo needs to be synced with "upstream"?

**Comment by me-no-dev** [comment]
oh... that must have changed recently :) it's due for resync anyway ;)

**Pull request closed without merging**
