### PR TITLE
M5CoreS3 board and partitions update

### PR DESCRIPTION
**Pull request by tobozo**
followup to #8161 

- adjusted default build values
    1) cdc default enabled
    2) 16MB flash + partition scheme copied from Core2 default selected
- added missing sections 
- added two custom partitions schemes to the variant folder

the new custom partitions layout is open for discussions.

[link to clean diff](https://github.com/espressif/arduino-esp32/pull/8274/files?w=1)

### CODE REVIEW

**Comment by imliubo** [comment]
LGTM :)

**Comment by me-no-dev** [comment]
boards.txt change went wrong... shows 23k lines changed

**Comment by tobozo** [comment]
@me-no-dev it's just github being github :-) [link to clean diff](https://github.com/espressif/arduino-esp32/pull/8274/files?w=1)

**Comment by me-no-dev** [comment]
my 2 cents: if you require more than 2 OTA partitions, you are a very special case and should have the partition scheme in your sketch folder. Our code assumes 2 such partitions and does not allow for APP switching for example

**Comment by tobozo** [comment]
The editor is github webapp, I edited the boards.txt from the browser and pasted the M5CoreS3 code block inside the existing flow. To my knowledge nothing else but the M5CoreS3 board block was modified in the file.

I've repeated the operation on the [patch-6](https://github.com/tobozo/arduino-esp32/commit/0a29f54473ef0d4306bd41f9d0c5c7b83c4867af) branch but I can't edit the source branch for this PR, can someone with admin permissions do it, or should I close and submit a new PR from that branch?

**Comment by tobozo** [comment]
resubmitted as #8276

**Pull request closed without merging**
