### PR TITLE
Implement Timer based on ESP-IDF API

### PR DESCRIPTION
**Pull request by P-R-O-C-H-Y**
## Summary
This PR is refactoring of TIMER HAL in order to use IDF instead of current Register manipulation approach.

I will do more tests, but everything seems to be working on all chips.

## Impact
None.

### CODE REVIEW

**Comment by PaintYourDragon** [comment]
Noticed that the RepeatTimer example doesn’t work on ESP32-S2 (works OK on ESP-WROOM-32). Before I open a new issue…looks like it might be related & addressed by this PR? If so, will just keep an eye on the status here. Thx.

**Comment by PaintYourDragon** [comment]
Answering my own question (and for author’s and maintainers’ edification): can confirm this fixes the RepeatTimer example, correctly runs on both WROOM and S2 after this. Looks like it gets Adafruit_Protomatter working again as well. Thx!

**Comment by PaintYourDragon** [comment]
Tagging @ladyada on this to follow along on current status.

**Comment by AkiHigashi** [comment]
Timer1 and Timer2 can't be used at the same time since 2.0.2. I believe this is because...

// Works for all chips
static hw_timer_t timer_dev[4] = {
    {0,0}, {1,0},  {1,0},  {1,1}
};

right ?

**Comment by P-R-O-C-H-Y** [comment]
Hi @AkiHigashi, All timers work at the same time. Tested on 2.0.3 :)

**Comment by AkiHigashi** [comment]
In the function
  hw_timer_t * timerBegin(uint8_t num, uint16_t divider, bool countUp)

timer_dev[] is used as
  hw_timer_t * timer = &timer_dev[num];   //Get Timer group/num from 0-3 number

So I think in the cases num=1 and num=2 result in the same [hw_timer_t * timer].

How?

**Comment by P-R-O-C-H-Y** [comment]
```
typedef struct hw_timer_s
{
    uint8_t group;
    uint8_t num;
} hw_timer_t;

// Works for all chips
static hw_timer_t timer_dev[4] = {
    {0,0}, {1,0},  {1,0},  {1,1}
};

```
The 1st number is GROUP, 2nd number is TIMER NUMBER.

> timer_dev[] is used as
> hw_timer_t * timer = &timer_dev[num]; //Get Timer group/num from 0-3 number

Read the comment on that line, it will get the combination of group/number from the num passed to the begin function.

Then it will configure the timers by group/num.

`timer_init(timer->group, timer->num, &config);`

If you call timerBegin() with 0 / 1 / 2 or 3 you will always get different group/timer_num :)

**Comment by AkiHigashi** [comment]
Last comment.

timerBegin(0, uint16_t divider, bool countUp) 
hw_timer_t * timer = &timer_dev[num] ------>  timer->group=0; timer->num=0;

timerBegin(1, uint16_t divider, bool countUp) 
hw_timer_t * timer = &timer_dev[num] ------>  timer->**group=1**; timer->num=0;

timerBegin(2, uint16_t divider, bool countUp) 
hw_timer_t * timer = &timer_dev[num] ------>  timer->group=1; timer->num=0;

timerBegin(3, uint16_t divider, bool countUp) 
hw_timer_t * timer = &timer_dev[num] ------>  timer->group=1; timer->num=1;

static hw_timer_t timer_dev[4] = {
    {0,0}, {1,0},  {1,0},  {1,1}
};

should be

static hw_timer_t timer_dev[4] = {
    {0,0}, **{0,1}**,  {1,0},  {1,1}
};


In esp32-hal-timer.c (2.0.1)

typedef struct hw_timer_s {
        hw_timer_reg_t * dev;
        uint8_t num;
        uint8_t group;
        uint8_t timer;
        portMUX_TYPE lock;
} hw_timer_t;

static hw_timer_t hw_timer[4] = {
        {(hw_timer_reg_t *)(DR_REG_TIMERGROUP0_BASE),0,0,0,portMUX_INITIALIZER_UNLOCKED},
        {(hw_timer_reg_t *)(DR_REG_TIMERGROUP0_BASE + 0x0024),1,**0,1,**portMUX_INITIALIZER_UNLOCKED},
        {(hw_timer_reg_t *)(DR_REG_TIMERGROUP0_BASE + 0x1000),2,1,0,portMUX_INITIALIZER_UNLOCKED},
        {(hw_timer_reg_t *)(DR_REG_TIMERGROUP0_BASE + 0x1024),3,1,1,portMUX_INITIALIZER_UNLOCKED}
};

bye

**Comment by AkiHigashi** [comment]
Tnx!

**Comment by mrengineer7777** [comment]
@P-R-O-C-H-Y The PR changes the definition of `static hw_timer_t timer_dev[4]` but the bytes are swapped compared to what @AkiHigashi posted. Impact: Timers 1 & 2 might be swapped, but they will be unique.

**Comment by P-R-O-C-H-Y** [comment]
> @P-R-O-C-H-Y The PR changes the definition of `static hw_timer_t timer_dev[4]` but the bytes are swapped compared to what @AkiHigashi posted. Impact: Timers 1 & 2 might be swapped, but they will be unique.

@mrengineer7777 
They need to be swaped, because esp32-C3 has 2 timer groups with 1 timer in each group. So you have availible timer 0 and 1. If swaped, there will be timer 0 and 2 which makes no sense ;)

**Pull request merged**
