### PR TITLE
Fix boards.txt options for atmegazero_esp32s2 deneyapmini

### PR DESCRIPTION
**Pull request by manchoz**
## Summary

Fixes https://github.com/espressif/arduino-esp32/issues/5618

## Impact

None

### CODE REVIEW

**Comment by vedantroy** [comment]
I'm blocked on this for a class I'm taking.
Is there a way to use this PR now (w/o it being merged in)?

**Comment by eddieespinal** [comment]
Thanks @manchoz for putting this PR. I had this fix locally and was waiting to put a PR until I fix the other issue I'm facing compiling with Arduino.  I just opened a bug to see if someone can help with that.  https://github.com/espressif/arduino-esp32/issues/5671

**Comment by eddieespinal** [comment]
@manchoz I created a new PR to fix the issue, the changes you made won't work as I've tested it.  Please see my PR and let me know if you have any questions.

https://github.com/espressif/arduino-esp32/pull/5673

**Comment by manchoz** [comment]
@eddieespinal yes, please, go ahead with your PR!

**Comment by me-no-dev** [comment]
closing in favor of #5673

**Pull request closed without merging**
