### PR TITLE
Add WiFiAccessPoint Example

### PR DESCRIPTION
**Pull request by fedy0**
@me-no-dev 
I've rebased, resolved conflicts and reverted changes to enable this PR to be merged

I hope it will work this time.
#Smiles

### CODE REVIEW

**Comment by me-no-dev** [comment]
please remove references to `LED_BUILTIN` from the sketch. not all boards have it.

**Comment by fedy0** [comment]
@me-no-dev 
I adjusted the reference to LED_BUILTIN to ease the use/testing of the example.

**Comment by me-no-dev** [comment]
there are 3 files that should not have been edited. Please restore them back

**Comment by fedy0** [comment]
@me-no-dev 

I have edited as you requested.
I still need advice from you concerning my forked messy master.

Thanks in advance

**Comment by me-no-dev** [comment]
maybe copy the sketch, clone the repo clean and then make the PR?

**Pull request closed without merging**
