### PR TITLE
fix(ssl): Add size arg to NetworkClientSecure::setCACertBundle

### PR DESCRIPTION
**Pull request by me-no-dev**
Fixes: https://github.com/espressif/arduino-esp32/issues/10099

### CODE REVIEW

**Comment by sidwarkd** [comment]
This is the change I made to get the bundle working :+1:

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Comment by waymond91** [comment]
Hey I know this is off topic, but Im really struggling to include <NetworkClientSecure.h> in my platformio project with the esp32s3. I figured I would post here as this seems to be where a lot of the activity surrounding that particular library is...
```
#include <NetworkClientSecure.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio/build/adafruit_feather_esp32s3_nopsram/FrameworkArduino/esp32-hal-matrix.c.o
*** [.pio/build/adafruit_feather_esp32s3_nopsram/src/main.cpp.o] Error 1
=============================== [FAILED] Took 2.52 seconds ===============================

 *  The terminal process "platformio 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
I assume this is because platformio is using a version of arduino-esp32 from before the release of NetworkClientSecure in version 3.

But Im not sure how to check the arduino-esp32 release version used, and have been unable to set it.

Or I must be fundamentally misunderstanding how to include this library in my project.

**platformio.ini**
```
[env:adafruit_feather_esp32s3_nopsram]
platform = espressif32
board = adafruit_feather_esp32s3_nopsram
framework = arduino
```
Trying to get some info on the package doesnt seem to give me the release version
```
➜  EthernetESP32 pio pkg show framework-arduinoespressif32


platformio/framework-arduinoespressif32
Tool • 3.20017.0 • Public • Published on Thu Jun  6 12:59:43 2024

Arduino Wiring-based Framework for the Espressif ESP32, ESP32-S and ESP32-C series of SoCs

--------------  -----------------------------------------------------------------------------
Registry        https://registry.platformio.org/tools/platformio/framework-arduinoespressif32
Repository      https://github.com/espressif/arduino-esp32.git
License         LGPL-2.1-or-later
Popularity      4
Stars           12810
Installed Size  735.92MB
Used By         1
Keywords        framework, arduino, espressif, esp32
--------------  -----------------------------------------------------------------------------

Version         Size      Published
--------------  --------  -------------------
3.20017.0       234.94MB  2024-06-06 12:59:43
3.20016.0       234.88MB  2024-05-03 12:56:33
3.20015.0       234.91MB  2024-04-24 16:04:36
3.20014.231204  232.70MB  2023-12-05 13:53:42
3.20011.230801  230.78MB  2023-08-01 16:20:44
3.20009.0       258.04MB  2023-05-09 09:50:22
3.20008.0       258.04MB  2023-04-21 09:27:00
3.20007.0       258.02MB  2023-02-24 14:02:47
3.20006.221224  244.29MB  2022-12-24 16:18:14
3.20005.220925  240.61MB  2022-09-26 12:49:21
3.20004.0       239.64MB  2022-07-19 10:35:53
3.20003.220626  227.20MB  2022-06-27 07:53:21
3.20002.220503  139.04MB  2022-05-03 11:58:35
3.20001.0       136.34MB  2022-04-20 10:38:15
3.20000.220418  127.40MB  2022-04-20 10:25:09
3.10006.210326  46.77MB   2021-03-26 11:55:41
3.10004.210126  33.32MB   2021-01-26 14:17:52
 ```

**main.cpp**
```
#include <Arduino.h>
#include <NetworkClientSecure.h>

// put function declarations here:
int myFunction(int, int);

void setup() {
  // put your setup code here, to run once:
  int result = myFunction(2, 3);
}

void loop() {
  // put your main code here, to run repeatedly:
}

// put function definitions here:
int myFunction(int x, int y) {
  return x + y;
}
```

**Comment by me-no-dev** [comment]
@waymond91 NetworkClientSecure requires Arduino v3.x, but PlatformIO officially supports up to 2.0.17 (that you are on).
@Jason2866 can help you with your config to get the latest version in PlatformIO

**Comment by Jason2866** [comment]
@waymond91 Core 3.0.x is not supported from Platformio. There is the community version `pioarduino` to support espressif Arduino core 3.0.4. You can use with Platformio with this setting for the platform.
```
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
```

**Comment by waymond91** [comment]
Thank you so much both! You deserve about half my weeks wages 😆

**Pull request merged**
