### PR TITLE
Handle large octet-stream

### PR DESCRIPTION
**Pull request by nathannau**
When body of request is too large (like many application/octet-stream), RAM is too small and malloc fail.

Body can be handle by many callback call like with upload file.

### CODE REVIEW

**Comment by lucasssvaz** [comment]
please remove the formatting changes of the PR

**Comment by nathannau** [comment]
> please remove the formatting changes of the PR

Sorry, I couldn't find the clear rules for formatting as a Prettier.
Where can I find them, please ?

**Comment by me-no-dev** [comment]
@nathannau even if you do not find rules, that does not mean that it's OK to change the formatting of multiple files. Now we can not even see what your real changes are. Please re-submit the PR with only the changes you need to have this feature implemented.

**Comment by nathannau** [comment]
Sorry about that. My IDE hides indentation changes. 
I'll clean it up.

**Pull request closed without merging**
