### PR TITLE
Docs/create docs structure using sphinx

### PR DESCRIPTION
**Pull request by pedrominatel**
Documentation structure using sphinx.

@VojtechBartoska please test in the ReadTheDocs side.

### CODE REVIEW

**Comment by VojtechBartoska** [comment]
@igrr PTAL

**Comment by igrr** [comment]
@pedrominatel could you please push this branch to https://github.com/espressif/arduino-esp32 repository? Currently the branch is in your fork, so Readthedocs won't build it. Once you push the branch to this repository, i can set up readthedocs to build your branch.

**Comment by pedrominatel** [comment]
Here it is @igrr: https://github.com/espressif/arduino-esp32/tree/docs/structure

**Comment by me-no-dev** [comment]
@pedrominatel please open a new pull request from that branch to master :)

**Pull request closed without merging**
