### PR TITLE
update Adafruit boards

### PR DESCRIPTION
**Pull request by hathach**
## Description of Change
- Update Adafruit definitions in boards.txt, use correct partition scheme for 8MB variants
- Update tinyuf2 for Adafruit from 0.9.2 to 0.10.2 version

## Tests scenarios
- Tested with all the boards from Adafruit (esp32, s2, s3, c3) with WiFIClient & I2C_scan sketch. Everything works well.

@ladyada

### CODE REVIEW

**Review by SuGlider — COMMENTED** [review]
LGTM

**Comment by SuGlider** [comment]
@hathach - 
Please update this PR with the base branch in order to proceed with merging. 
I can't rebase your GH branch as it seems to be blocked for me.

**Comment by hathach** [comment]
> @hathach - Please update this PR with the base branch in order to proceed with merging. I can't rebase your GH branch as it seems to be blocked for me.
Thanks for the review. Just done, I tried to find option to allow changes for upstream maintainer. But didn't quite figure where it is. Will try to do that in all of next PRs.

**Comment by SuGlider** [comment]
thanks @hathach - Merged.

**Pull request merged**
