### PR TITLE
HTTPClient Library - Fix on response headers handling

### PR DESCRIPTION
**Pull request by marciopamplona**
## Description of Change
The library wasn't dealing correctly with the response headers. The function collectHeaders wasn't even used.
I rewrote with vector and a class to store the values.

## Tests scenarios
Tested on ESP32-PICO-D4, Arduino core v2.0.6

### CODE REVIEW

**Comment by PilnyTomas** [comment]
@marciopamplona thank you for your contribution.
Could you please help us? How did you test it? Could you please provide an example that would demonstrate the broken and fixed behavior?

**Comment by marciopamplona** [comment]
Hello @PilnyTomas, sure.

**How to test it:**
```C++
HTTPClient http;
String queryURL = "http://ip-api.com/json";
http.begin(queryURL.c_str());
int httpResponseCode = http.GET();

if (httpResponseCode == 200) {  
  int numberOfHeaders = http.headers();
  String date = http.header("Date");
  Serial.printf("Number of headers: %d\nDate header: %s\n\n", numberOfHeaders, date.c_str());
}
```

**Expected result:**
```
Number of headers: 6
Date header: Wed, 25 Jan 2023 21:11:46 GMT
```

**Actual result:**
```

Number of headers: 0
Date header: 
```

**Code analysis:**

LINE 1093, function `HTTPClient::headers()` returns `_headerKeysCount`, but this variable is not being set nowhere in the code, except for the LINE 1057 on function `HTTPClient::collectHeaders()` which is NOT BEING USED.
The headers are NOT BEING STORED anywhere, so the function http.header(const char* name) can't return anything.

**Review by PilnyTomas — APPROVED** [review]
Thanks for the explanation.
LGTM

**Review by P-R-O-C-H-Y — CHANGES_REQUESTED** [review]
@marciopamplona Code looks overall good, thanks for the fix :)
As it is a change in API, I suggest to milestone it for version 3.0.0.

But `HTTPUpdate` library used `HTTPClients collectHeaders` function. Please adjust the `HTTPUpdate` code there to match your changes? Compiling HTTPUpdate example cast this error:
```
Users/prochy/Documents/Arduino/hardware/espressif/esp32/libraries/HTTPUpdate/src/HTTPUpdate.cpp: In member function 'HTTPUpdateResult HTTPUpdate::handleUpdate(HTTPClient&, const String&, bool)':
/Users/prochy/Documents/Arduino/hardware/espressif/esp32/libraries/HTTPUpdate/src/HTTPUpdate.cpp:224:10: error: 'class HTTPClient' has no member named 'collectHeaders'; did you mean 'connected'?
     http.collectHeaders(headerkeys, headerkeyssize);
```

The same collectHeaders function is used in WebServer. As for now, both function were the same (Server / Client). I think it would be great, if you made the changes in the WebServer side too, to it will be the same again for both libs.

@me-no-dev Do you agree?

**Comment by me-no-dev** [comment]
This change is in effect removing functionality and allowing for using more memory than required.

Correct me if I am wrong, but this change collects all received headers and stores them in memory, until the request is destroyed. The point of `collectHeaders` was to limit the number of headers to only the ones that we need in our code, which saves an unknown amount of memory (because some sites return HUGE headers).

If I am correct, then this is actually a regression which also points to missing proper documentation on how to use `collectHeaders`

**Comment by me-no-dev** [comment]
Thanks for confirming @marciopamplona ! @pedrominatel PTAL on adding docs for this

**Pull request closed without merging**
