### PR TITLE
ESP32 Arduino v3.1.x

### PR DESCRIPTION
**Pull request by me-no-dev**
This PR is to be used for development and testing Arduino v3.1 based on IDF v5.3

### ESP32-P4 tasks

- [x] Make RMII Ethernet work
- [x] Define and test the HP SPI ports
- [x] Implement Touch driver V3
- [ ] Fix `getFlashChipMode`
- [x] Fix PSRAM
- [x] Make WiFi work with ESP32C6 over SDIO
- [ ] Fix I2C Slave
- [x] HighSpeed USB Host (TinyUSB)
- [x] SDMMC Power support

### CODE REVIEW

**Comment by me-no-dev** [comment]
@lucasssvaz please fix the conflicts with the jsons :)

**Comment by me-no-dev** [comment]
@P-R-O-C-H-Y please change ZigBee sketches to not run on P4

**Comment by P-R-O-C-H-Y** [comment]
> @P-R-O-C-H-Y please change ZigBee sketches to not run on P4

@me-no-dev done

**Comment by lucasssvaz** [comment]
@P-R-O-C-H-Y Maybe we can replace the skips with:
```
"require": [
  "SOC_IEEE802154_SUPPORTED=y"
]
```

**Comment by me-no-dev** [comment]
> Maybe we can replace the skips with:

@P-R-O-C-H-Y please do. And also note this nice new feature for sketch filtering :)

**Comment by me-no-dev** [comment]
@lucasssvaz shouldn't it be `CONFIG_SOC_IEEE802154_SUPPORTED=y` ?

**Comment by lucasssvaz** [comment]
> @lucasssvaz shouldn't it be `CONFIG_SOC_IEEE802154_SUPPORTED=y` ?

Yeah, my mistake.

**Comment by P-R-O-C-H-Y** [comment]
Changed to "requires" instead of "targets". But if we add new chip which supports `IEEE802154`, the CI will fail as it will use default FQBN without setting the ZigbeeMode and correct partition scheme. 

Future task: Add option to specify also a common FQBN in ci.json, to avoid specifying the same thing for all supported SoCs.

**Pull request merged**
