### PR TITLE
feat: Print chip features bitfield

### PR DESCRIPTION
**Pull request by Xylopyrographer**
## Description of Change
Adds printing the value of the chip features bitfield to printChipInfo() to facilitate debugging.

## Tests scenarios
Tested with:

- Arduino IDE v2.3.2
- arduino-esp32 core v3.0.3
- Debian GNU/Linux 12
- Waveshare ESP32-S3-Matrix dev board

## Related links
None

### CODE REVIEW

**Comment by VojtechBartoska** [comment]
thanks for the PR @Xylopyrographer, we will review it soon.

**Comment by me-no-dev** [comment]
Question is what does this help if the bits are examined in the following lines? This will just print a meaningless (to the users and us) hex, that we would need to examine anyway. Do you mean that there might be bits not documented?

**Comment by VojtechBartoska** [comment]
@Xylopyrographer any comments? Thanks

**Comment by Xylopyrographer** [comment]
@me-no-dev, @VojtechBartoska 

> Question is what does this help if the bits are examined in the following lines? This will just print a meaningless (to the users and us) hex, that we would need to examine anyway. Do you mean that there might be bits not documented?

So this stems from #9974 where the chip report from a board using an ESP32-S3FH4R2 fails to report that the chip has both on-board flash and PSRAM. To help diagnose further, I had to add the raw chip features dump.

Debugging and diagnostic tools should report accurately, this demonstrates a case where something is amiss. It would also be useful should new silicon be ahead of the chip report as it could be used as a check and yes, show undocumented features.

As for interpretation, the bits are enumerated and can be checked (albeit with a bit more digging) but at least the base information is there to investigate further if needed.

FWIW, haven't yet carried the investigation into the above error further. Not reported in IDF 4.4? Definition of "embedded" means something else? Does it show only foe ESP32 modules?

**Pull request merged**
