### PR TITLE
Update PlatformIO integration scripts

### LINKED ISSUE #7572: Platformio broken with actual master
### Board

every

### Device Description

not relevant

### Hardware Configuration

not relevant

### Version

latest master (checkout manually)

### IDE Name

Platformio (custom self build)

### Operating System

macOS 12.3

### Flash frequency

40 Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

@me-no-dev 
Compile fails with Platformio at the stage where esptool.py merge command is done.
https://github.com/espressif/arduino-esp32/blob/master/tools/platformio-build.py#L91 

There are no `bootloader*.bin` files anymore in folder `sdk/esp*/bin` just `*.elf` files

### Sketch

```cpp
Every sketch
```

### Debug Message

```plain
none
```

### Other Steps to Reproduce

none

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by valeros**
This PR brings updates according to the latest changes in the Arduino core:
- Bootloader binaries are now generated from elf files
- Updated CI scripts
- Updated esptoolpy to v4.2.1
- Minor clean-up by removing obsolete code

Resolves #7572

### CODE REVIEW

**Comment by me-no-dev** [comment]
@valeros ESP32-S3 does not have DIO 40MHz bootloader. It does have DIO 80MHz. In reality, default should be QIO@80MHz for all chips

**Comment by valeros** [comment]
Hi @me-no-dev, I'm not sure where this DIO 40MHz is coming from, we don't have any preconfigured S3-based board manifests with the `DIO` mode. I guess it should be fixed here https://github.com/espressif/arduino-esp32/blob/master/.github/scripts/on-push.sh#L115 with additional `--project-option="board_build.flash_mode= qio"` ?

**Comment by me-no-dev** [comment]
@valeros it must be coming somewhere from your board definitions or build scripts, because I do not see it defined on our side as well. You can add the changes to `on-push.sh` for QIO and 80MHz, but it would still cause issue for users (I guess)

**Comment by Jason2866** [comment]
@valeros @me-no-dev I think this is the place where the issue is coming from https://github.com/tasmota/arduino-esp32/blob/master/.github/scripts/on-push.sh#L88
Imho a valid real boards.json should be used for the S3.

**Comment by me-no-dev** [comment]
Looks good :)

**Comment by Jason2866** [comment]
@valeros Thx! Just works ;-)

**Pull request merged**
