### PR TITLE
Added partition menu for OROCA EduBot board.

### PR DESCRIPTION
**Pull request by chcbaram**

### CODE REVIEW

**Comment by me-no-dev** [comment]
do you really need that large of partitions?

**Comment by chcbaram** [comment]
> do you really need that large of partitions?

Yes. it uses BLE so takes large memory and there are lots of images and audio data for lcd and audio.

**Comment by me-no-dev** [comment]
how much flash do you have on-board? if more than 4, we can add custom scheme for it.

**Comment by chcbaram** [comment]
> how much flash do you have on-board? if more than 4, we can add custom scheme for it.

Thank you for your kindness. It has 4MB Flash so it's possible to select the partition in the default options. If I need custom partition, I will ask . Thanks again.

**Pull request merged**
