### PR TITLE
added Nano32 Development Board for Arduino

### PR DESCRIPTION
**Pull request by ESP32DE**
attached is the Nano32 Development Board with Pin Description
- changed Readme
- added Board Pic

### CODE REVIEW

**Comment by AdySan** [comment]
@ESP32DE did you see the commnt on the other PR regarding Nano32? https://github.com/espressif/arduino-esp32/pull/8#issuecomment-252181783

**Comment by me-no-dev** [comment]
pinout image is fine :) I mind merging board configurations if they are the same as the regular nodemcu-like dev board. And I don't really mind them, just want to prevent hiccups while we are rapidly adding to the repository.
@ESP32DE maybe we should make separate page for board pinouts?

**Comment by ESP32DE** [comment]
maybe :)
did you merge the Nano32 to the Doc Repo 
thanks

**Comment by ESP32DE** [comment]
@AdySan yes have seen just in time.
btw: have you seen on your profile the wrong twitter link?
;-)
i do a pull request for this ? ;-)

unbenannt

**Pull request closed without merging**
