### PR TITLE
Change some WiFi buffer settings to match esp-idf.  See #2899

### PR DESCRIPTION
**Pull request by lbernstone**
Buffer mismatches appear to be causing WiFi communications to halt.  See #2899 for more details.

### CODE REVIEW

**Comment by stickbreaker** [comment]
@lbernstone since you found these relationships between buffer configurations, why don't you add some error checking for the values. added these compiler checks would prohibit this error from happening again.

This is just an example, You will have to figure out the correct rules to test.
```c++
#if (CONFIG_ESP32_WIFI_RX_BA_WIN > CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM )
# error buffer config mismatch
#endif 
```

Do you know the limit values?  Are the current values in your PR "empirical" or calculated?

Chuck.

**Comment by lbernstone** [comment]
They are taken from the default sdkconfig in esp-idf, so not really even empirically derived.  They are compiled into the libraries, so I'm not sure what an error check would do for anybody but travis.  The error check really ought to be upstream in LWiP, where the mismatch is actually causing the problem.

**Comment by atanisoft** [comment]
> They are compiled into the libraries, so I'm not sure what an error check would do for anybody but travis.

These are in fact compiled at the time of compiling arduino-esp32 code and not IDF. This is not always the case though. The WiFi library itself uses these values when it initializes the wifi stack.

**Comment by r1dd1ck** [comment]
These checks will be implemented @ ESP-IDF sooner or later, so I would stay with just fixing the values in the current sdkconfig now & let the checks come in later with an IDF update.

**Comment by lbernstone** [comment]
@atanisoft 
> 
> These are in fact compiled at the time of compiling arduino-esp32 code and not IDF. This is not always the case though. The WiFi library itself uses these values when it initializes the wifi stack.

Doh, you are right.  Only used in headers.

**Comment by atanisoft** [comment]
> Doh, you are right. Only used in headers.

@r1dd1ck is the one he who pointed this out. Almost all settings are precompiled in but there seem to be a handful that are adjustable at the app level.

It would be really nice to be able to override these defaults in our app code without modifying core headers but that isn't possible or maintainable.

**Comment by lbernstone** [comment]
@atanisoft : Copy the header into your sketch folder.  Arduino will use the local copy instead of the include folder version.

**Comment by atanisoft** [comment]
@lbernstone now that is an awesome find!

**Comment by Daemach** [comment]
Does this benefit wifi in general?  If so can you provide a link to the
header that should be copied?

**Comment by atanisoft** [comment]
@Daemach sdkconfig.h I believe

**Comment by stickbreaker** [comment]
@Daemach [tools/sdk/include/config/sdkconfig.h](https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/include/config/sdkconfig.h) The other is file is used for the build config.

Chuck.

**Comment by me-no-dev** [comment]
how does the heap look when you increase the static buffers?

**Comment by r1dd1ck** [comment]
@me-no-dev 
If I remember correctly, it takes about 3-4kB more than with the current arduino defaults (8).
Raising it to the `iperf` example defaults (16) had a 13-14kB impact.

Maybe it could survive even without the static buffer raise, as I suppose the most crucial part was the `RX_BA_WIN` adjustment (16 → 6). Haven't played around with the numbers since then, but the values from this PR have proven to be quite solid, and they are also the defaults for ESP-IDF.

**Comment by lbernstone** [comment]
Those static buffers should be 1K each. In practice, I see a difference of 3120 bytes between the two configs.

**Comment by me-no-dev** [comment]
alright... I'm merging this to include it in the new build

**Pull request merged**
