### PR TITLE
Fix for confusing overload of Wire::begin

### LINKED ISSUE #6616: Confusing overload of `Wire::begin`
### Board

Any

### Device Description

Not specific to a device.

### Hardware Configuration

Any I2C device connected

### Version

v2.0.2

### IDE Name

CLion + platformio

### Operating System

Linux

### Flash frequency

N/A

### PSRAM enabled

no

### Upload speed

N/A

### Description

The `Wire::begin` method has confusing overload:
```
    bool begin(int sda=-1, int scl=-1, uint32_t frequency=0); // returns true, if successful init of i2c bus
    bool begin(uint8_t slaveAddr, int sda=-1, int scl=-1, uint32_t frequency=0);
```
The `sda` and `scl` arguments are of type `int`, while the `SDA` and `SCL` constants from `d32_core.h` have type `uint8_t`. A "naive" user might try to call `begin(SDA, SCL)` and get mysterious `"could not acquire lock"` error on first attempt to use the bus.

To make the problem worse, this code worked fine before the "slave" overload was introduced.

As a solution I want to propose renaming the "slave" function to something like `begin_slave`.

### Sketch

```cpp
int setup(){
    // have to explicitly specify the pins to provide the frequency
    Wire.begin(SDA, SCL, 4000);
    Wire.beginTransmission();
}
```

### Debug Message

```plain
[   238][E][Wire.cpp:319] beginTransmission(): could not acquire lock
[   239][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
```
```


### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by bato3**
Closes #6616

SDA and SCL are defined as `uint8_t`, and when it is used, library try initialize itself in slave mode

*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

### Checklist
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [ ] Please **update relevant Documentation** if applicable
4. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
Please describe your proposed Pull Request and it's impact.

## Tests scenarios
Please describe on what Hardware and Software combinations you have tested this Pull Request and how.

(*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with ESP32 and ESP32-S2 Board with this scenario*)

## Related links
Please provide links to related issue, PRs etc.

(*eg. Closes #number of issue*)

### CODE REVIEW

**Comment by SuGlider** [comment]
@bato3 

When compilling it I got this message in the console: 
```
In file included from C:\Users\SuGlider\Documents\Arduino\issue_6616_wire_slave_begin_int8\issue_6616_wire_slave_begin_int8.ino:1:
C:\Users\SuGlider\Documents\Arduino\hardware\espressif\esp32\libraries\Wire\src/Wire.h: In function 'void setup()':
C:\Users\SuGlider\Documents\Arduino\hardware\espressif\esp32\libraries\Wire\src/Wire.h:84:10: note: candidate 1: 'bool TwoWire::begin(uint8_t, int, int, uint32_t)'
     bool begin(uint8_t slaveAddr, int sda=-1, int scl=-1, uint32_t frequency=0);
          ^~~~~
C:\Users\SuGlider\Documents\Arduino\hardware\espressif\esp32\libraries\Wire\src/Wire.h:80:17: note: candidate 2: 'bool TwoWire::begin(uint8_t, uint8_t, uint32_t)'
     inline bool begin(uint8_t sda, uint8_t scl, uint32_t frequency=0)
                 ^~~~~

```

**Comment by SuGlider** [comment]
I see other considerations as exposed in https://github.com/espressif/arduino-esp32/issues/6616#issuecomment-1186270656

**Review by SuGlider — COMMENTED** [review]
Please detail which Use Cases are covered by this PR.

**Comment by SuGlider** [comment]
@bato3  - Please evaluate this other PR  #7000 to solve the issue.

**Comment by bato3** [comment]
@SuGlider #7000 has case
```cpp
Wire.begin(SDA, SCL);
```
so, it can be OK. 
I don't have the skills to test it properly.

**Pull request closed without merging**
