### PR TITLE
fix(client): Implement readBytes in NetworkClient for faster downloads

### PR DESCRIPTION
**Pull request by me-no-dev**
Fixes: https://github.com/espressif/arduino-esp32/issues/9822

## Test downloading 22MB zip and using `readBytes` with ESP32-S3

Test results are relative and actual speeds will vary based on the environment. 

### Download from HTTP server (no SSL):
```cpp
// python3 -m http.server 8080 -d .
const char *fileDownloadUrl = "http://192.168.254.91:8080/esp32-3.0.1.zip";
```

New Method:
```
Download completed!
Total download time: 40.714000 s
Average download speed: 573.149578 Kb/s
```

Old Method:
```
Download completed!
Total download time: 63.890000 s
Average download speed: 365.240443 Kb/s
```

### Download from HTTPS server (with SSL):
```cpp
const char *fileDownloadUrl = "https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-3.0.1.zip";
```

New Method:
```
Download completed!
Total download time: 80.371000 s
Average download speed: 290.343680 Kb/s
```

Old Method:
```
Download completed!
Total download time: 162.368000 s
Average download speed: 143.718047 Kb/s
```

### CODE REVIEW

**Comment by JAndrassy** [comment]
readBytes is a function fo Stream class and should wait Stream's timeout for next byte
https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadbytes/

**Comment by me-no-dev** [comment]
@JAndrassy then maybe different solution is needed. reading network streams byte by byte is never a good idea

**Comment by me-no-dev** [comment]
@JAndrassy I got it, but readBytes reads byte by byte and that is also not good for Network, is what I meant

**Comment by me-no-dev** [comment]
So you suggest to leave Client to read byte by byte and waste a lot of time doing it?

**Comment by JAndrassy** [comment]
> So you suggest to leave Client to read byte by byte and waste a lot of time doing it?

there is `read)buffer, size)`. that should be used.

**Comment by me-no-dev** [comment]
`Stream.readBytes` says nowhere that we should be waiting for every single byte, therefore we can wait when there are no bytes. Do you get this, or are we just arguing for no reason?

**Comment by SuGlider** [comment]
This may affect OTA and designed time out...

**Comment by SuGlider** [comment]
About `Stream::readBytes()` --> it uses `Stream::timedRead()`. Setting timeout to Zero using `Stream::setTimeout(0)` may help WiFi streams using such function.

This PR should created some other Function Name... Or at least, test timeout for Zero and in case it is not zero, use the Stream Class original function. 

This PR implementation is equivalent to ignoring Timeout setup.

**Comment by SuGlider** [comment]
Please check https://github.com/espressif/arduino-esp32/issues/9823#issuecomment-2160705738
This is why timeout is important for certain Network operations.

**Comment by me-no-dev** [comment]
@SuGlider yes. It should wait the timeout, but should not read a byte by byte with timeout. Nobody said this is final implementation. 

This is network client, it gets many bytes. Currently the code that triggered this was downloading a large file from internet. Now imagine reading this file byte by byte and every time checking if more are available, if it got that single byte before that timeout and so on. Result is that you can not handle anything with speeds above 1Mbps on an S3 (I imagine much less on single core and slow RV chips). If we instead grab all bytes that are available at once and wait up to the timeout for more, then we can achieve speeds 3 times higher. I hope this makes it a bit more clear for you @SuGlider and @JAndrassy

**Comment by hitecSmartHome** [comment]
I'm more than happy to test if it will be compatible with arduino 2.0.17

**Comment by me-no-dev** [comment]
@hitecSmartHome you can try the current changes on top of WiFiClient

**Comment by JAndrassy** [comment]
so the now updated implementation in this PR should use `getTimeout()`, not `_timeout;`.

this implementation of readBytes will be used only if invoked on pointer of reference of type NetworkClient. if the pointer is  ESPLwIPClient, Client or Stream type then the reaBytes from Stream will be executed.

**Comment by me-no-dev** [comment]
>  if the pointer is ESPLwIPClient, Client or Stream type then the reaBytes from Stream will be executed.

That is correct. Stream implementation works fine. This is to fix it for NetworkClient and NetworkClientSecure (and HTTPClient)

**Pull request merged**
