### PR TITLE
Add auto reset support to Nano32

### PR DESCRIPTION
**Pull request by MakerAsia**
Board Nano32 has auto flash. This pull request is to add auto reset to Nano32 after write flash. This will make users of Nano32 more convenient and do not need to reset by manual after flash.

### CODE REVIEW

**Comment by tuanpmt** [comment]
I would like to reset with this option `--reset-after-flash` 😋

**Comment by MakerAsia** [comment]
Which repository is an upstream for esptool using in this project?

**Comment by projectgus** [comment]
Hi,

Upstream esptool.py maintainer here. :) The ESP32 support work-in-progress is housed here at the moment:
https://github.com/themadinventor/esptool/pull/121

Supporting "exit flashing mode" is on the list to support but not yet implemented, sorry! I plan to finish it very soon though.

**Comment by igrr** [comment]
ESP32 support for esptool is being developed here:
https://github.com/themadinventor/esptool/pull/121
Both ESP-IDF and this project get esptool there.

**Comment by projectgus** [comment]
Thanks for being patient as we added this feature. As of about a day ago esp-idf has support to configure reset after flash (defaults to enabled). Once Arduino's copy of esptool.py is updated then it will also have this feature.

**Pull request closed without merging**
