### PR TITLE
BluetoothSerial: check return value and return number of bytes written

### PR DESCRIPTION
**Pull request by gohai**

### CODE REVIEW

**Comment by gohai** [comment]
Pinging @copercini

**Comment by me-no-dev** [comment]
please rebase to the latest master. I introduced some changes that break your PR

**Comment by copercini** [comment]
@gohai Looks nice, just rebase it (adapt the code as it had a major update today that is causing some minor conflicts with your pull request)

**Comment by gohai** [comment]
Rebased

**Comment by me-no-dev** [comment]
please rebase once again, hopefully the CI build will pass :)

**Comment by me-no-dev** [comment]
Thanks @gohai :)

**Pull request merged**
