### PR TITLE
Adds HW Serial CDC as IDF component example

### PR DESCRIPTION
**Pull request by SuGlider**
## Description of Change
Adds a new example for building Arduino project as IDF component using the native HW CDC port.

## Tests scenarios
Tested using ESP32-C3, ESP32-C6 and ESP32-S3 - building it using Arduino as IDF Component.

## Related links
None

### CODE REVIEW

**Review by me-no-dev — APPROVED** [review]

**Review by lucasssvaz — APPROVED** [review]

**Comment by me-no-dev** [comment]
One more thing. The example should be added [here](https://github.com/espressif/arduino-esp32/blob/master/idf_component.yml#L97) so it shows on the component page

**Comment by SuGlider** [comment]
> One more thing. The example should be added [here](https://github.com/espressif/arduino-esp32/blob/master/idf_component.yml#L97) so it shows on the component page

done.

**Comment by me-no-dev** [comment]
@SuGlider some misspelled words: https://github.com/espressif/arduino-esp32/actions/runs/10646370640/job/29513128732?pr=10262#step:8:25

**Comment by SuGlider** [comment]
> @SuGlider some misspelled words: https://github.com/espressif/arduino-esp32/actions/runs/10646370640/job/29513128732?pr=10262#step:8:25

Both typos are now fixed.

**Pull request merged**
