### PR TITLE
Fixes DHCP Server Lease Range for any AP Server Static IP Address

### LINKED ISSUE #6270: ESP32 AP Mode Local IP
### Board

ESP32

### Device Description

Custom Board

### Hardware Configuration

not relevant

### Version

v1.0.6

### IDE Name

Arduino

### Operating System

Windows 10

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

921600

### Description

Hello all,

I got a Problem Setting up an Access Point. there seems to be an DHCP server starting at Address x.x.x.241. This will cause an Problem if setting up the local IP in this range, like the example below.
Is there a option that this would be possible?
For my actual project the local IP Address could be changed by an user, and so this could cause problems.
Actual it works if I limit the local IP to x.x.x.240 But it would me more flexible if this isn't necessarry

### Sketch

```cpp
#include <WiFi.h>

IPAddress local_IP(192,168,1,254);
IPAddress gateway(192,168,1,9);
IPAddress subnet(255,255,255,0);

void setup()
{
  Serial.begin(115200);
  Serial.println();

  Serial.print("Setting soft-AP configuration ... ");
  Serial.println(WiFi.softAPConfig(local_IP, gateway, subnet) ? "Ready" : "Failed!");

  Serial.print("Setting soft-AP ... ");
  Serial.println(WiFi.softAP("ESPsoftAP_01") ? "Ready" : "Failed!");

  Serial.print("Soft-AP IP address = ");
  Serial.println(WiFi.softAPIP());
}

void loop() {}
```

### Debug Message

```plain
Setting soft-AP configuration ... Failed!
Setting soft-AP ... Ready
Soft-AP IP address = 192.168.1.254
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Summary
There is an issue that prevents DHCP server to start if WiFi AP Mode is used with Static IP that is too close to the end of subnet range. Lease adresses range will overflow NetMask preventing DHCP Server to start, issuing error message ```DHCPS Set Lease Failed! 0x5001```.

This PR fixes it and continues to consider the same previously coded assumptions about netmasking and DHCP leasing range size for AP mode.

## Impact
None.

## Related links
Fixes #6270

### CODE REVIEW

**Comment by me-no-dev** [comment]
@SuGlider since it's already merged, please adjust the code and remove it here.

**Comment by me-no-dev** [comment]
@SuGlider will you finish this please?

**Comment by SuGlider** [comment]
> @SuGlider will you finish this please?

@me-no-dev - PR is finished for Arduino Core 2.0.3.

I'll work on a separated PR that will allow the user to set IPV4 Range for DHCP. 
At this time this PR fixes #6270 and helps on #6271

**Comment by ch-fb** [comment]
Thanks a bunch!

**Pull request merged**
