### PR TITLE
Add ESP.getChipId() function to get ESP32's ChipID.

### PR DESCRIPTION
**Pull request by wemos**
@me-no-dev 
Add ESP.getChipId() function to get ESP32's ChipID.

### CODE REVIEW

**Comment by wemos** [comment]
@me-no-dev
This is new pull request, could it be merge?

**Comment by me-no-dev** [comment]
@wemos will you do what I asked?

**Comment by wemos** [comment]
@me-no-dev
yes, just add getChipId() without board update.

**Comment by me-no-dev** [comment]
@wemos did you miss my review?

I would like you to rename the method to getEfuseMac() because the name is misleading :) I get that ESP8266 has this method and that the result could be interpreted as unique id of the chip, but still this is not the chip id that ESP8266 have.

**Comment by wemos** [comment]
ok

**Comment by me-no-dev** [comment]
why did you close the pull request?

**Comment by wemos** [comment]
I will make new

**Comment by wemos** [comment]
@me-no-dev 
I change getChipId() to getEfuseMac().

**Pull request merged**
