### PR TITLE
Added NVS test sketch + test script

### PR DESCRIPTION
**Pull request by P-R-O-C-H-Y**
## Description of Change
Added simple NVS test.

## Related links
#6884 

## Important
Before each release, this NVS test needs to be locally builded + run on ESP32S3 with Octal Flash.

Command to build with custom FQBN (cfg.json will be excluded from building):
`./.github/scripts/tests_build.sh -s nvs -t esp32s3 -fqbn espressif:esp32:esp32s3:PSRAM=opi,USBMode=default,PartitionScheme=huge_app,FlashMode=opi`

Command to run:
`./.github/scripts/tests_run.sh -s nvs -t esp32s3 -e -o`

### CODE REVIEW

**Comment by me-no-dev** [comment]
@P-R-O-C-H-Y flash modes are working now in the 4.4 branch. You can test against that and master if you want to verify that it fails on one, but not the other. cc: @Ouss4

**Comment by P-R-O-C-H-Y** [comment]
@me-no-dev Can confirm that on C3 and S3 all modes are working on idd-release/v4.4 branch. Great job!

**Comment by me-no-dev** [comment]
FQBN Additions:
- ESP32-S3: FlashMode=[qio|qio120|dio|opi]
- Rest: FlashMode=[qio|qout|dio|dout],FlashFreq=[40|80]

**Comment by me-no-dev** [comment]
There is a problem with the test @P-R-O-C-H-Y . Since the value is in NVS, it is probably already set to something from previous run and will never again start from 0, so what the test expects will fail (as it did). Maybe you need to rethink the test or find a way to erase flash prior to running the test.

**Comment by P-R-O-C-H-Y** [comment]
We are waiting for @Ouss4 to make a PR with a few  CI changes. One will be the flash erase so the test will work after that PR ;)

**Comment by lbernstone** [comment]
Not to derail this pr, but is there actually eqpt out there that will only run on dout/qout?

**Comment by me-no-dev** [comment]
> Not to derail this pr, but is there actually eqpt out there that will only run on dout/qout?

yes. I have a board that has flash which can do only dout. It's very rare, but exists and also can free up some IO if you do not need the throughput.

**Comment by lbernstone** [comment]
> > Not to derail this pr, but is there actually eqpt out there that will only run on dout/qout?
> 
> yes. I have a board that has flash which can do only dout. It's very rare, but exists and also can free up some IO if you do not need the throughput.

Ok, just asking.  I have some cheap sh!t in my bin, and I've never seen it :smile:

**Comment by VojtechBartoska** [comment]
**Status update:** Blocked by missing HW on our runners.

**Comment by P-R-O-C-H-Y** [comment]
**Status update:** Hw will be installed tomorrow morning.

**Comment by VojtechBartoska** [comment]
**To-Do:**
- Write down internal Wiki page about "How to release"

**Pull request merged**
