### PR TITLE
Add Schedule and Functional/Scheduled Ticker

### PR DESCRIPTION
**Pull request by hreintke**
Identical implementation as in ESP8266

### CODE REVIEW

**Comment by me-no-dev** [comment]
How about this to get written in more ESP32 and RTOS style? Use a thread (start it on first call of `schedule`) instead of attaching always to the loop ;)

**Comment by me-no-dev** [comment]
I understand, but this is a dual-core chip which runs an actual OS, so let's make it run as it should. ESP8266 runs NonOS like most other MCUs.

**Comment by hreintke** [comment]
@me-no-dev See PR https://github.com/espressif/arduino-esp32/pull/1516

**Comment by fabiuz7** [comment]
no hope about this PR? It would be great porting some old esp8266 program without messing up with different "API"

**Pull request closed without merging**
