### PR TITLE
feat(3rd_party_board):Add GPIO pin mappings for M5Stack CamS3 Unit and select OPI PSRAM by default

### PR DESCRIPTION
**Pull request by tarosay**
### Checklist
1. [x] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [x] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [x] Please **update relevant Documentation** if applicable
4. [x] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)
5. [x] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
This pull request adds the GPIO pin mappings specific to the M5Stack CamS3 Unit in the CameraWebServer and updates the troubleshooting guide. These changes ensure that the M5Stack CamS3 Unit is properly supported and can be used without additional modifications. The troubleshooting guide now includes specific instructions for configuring the PSRAM settings for the M5UnitCamS3.

### Changes
- Added GPIO pin definitions for the M5Stack CamS3 Unit.
- Updated the configuration to include the new hardware mappings.
- Verified compatibility with existing functionalities to ensure no regressions.
- Updated the troubleshooting guide to include instructions for setting the PSRAM option for the M5UnitCamS3 in the Arduino IDE.

## Tests scenarios
Tested the changes on an M5Stack CamS3 Unit. To ensure proper functionality, select the board as "M5UnitCamS3" and set the PSRAM option to "OPI PSRAM" in the Arduino IDE.

*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with M5Stack CamS3 Unit using the CameraWebServer example*

## Related links
[M5Stack CamS3 Unit Documentation](https://docs.m5stack.com/en/unit/Unit-CamS3)

### CODE REVIEW

**Comment by P-R-O-C-H-Y** [comment]
@tarosay Is the board sold only with OPI PSRAM? If so, I recommend to remove the QSPI PSRAM option in boards.txt file for this board.

**Review by me-no-dev — APPROVED** [review]

**Comment by tarosay** [comment]
> @P-R-O-C-H-Y this change should come from M5 guys. We are not sure what they used in this case. There might be boards with QIO PSRAM

### Checklist
1. [x] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [x] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [x] Please **update relevant Documentation** if applicable
4. [x] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)
5. [x] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
This pull request adds the GPIO pin mappings specific to the M5Stack CamS3 Unit in the CameraWebServer and updates the troubleshooting guide. These changes ensure that the M5Stack CamS3 Unit is properly supported and can be used without additional modifications. The troubleshooting guide now includes specific instructions for configuring the PSRAM settings for the M5UnitCamS3.

Additionally, it removes the QSPI PSRAM option from the `boards.txt` file for the M5UnitCamS3, as the board is only sold with OPI PSRAM.

### Changes
- Added GPIO pin definitions for the M5Stack CamS3 Unit.
- Updated the configuration to include the new hardware mappings.
- Verified compatibility with existing functionalities to ensure no regressions.
- Updated the troubleshooting guide to include instructions for setting the PSRAM option for the M5UnitCamS3 in the Arduino IDE.
- Removed the QSPI PSRAM option for the M5UnitCamS3 in `boards.txt`.

### Justification
According to the [M5Stack CamS3 Unit Documentation](https://docs.m5stack.com/en/unit/Unit-CamS3), the ESP32-S3-WROOM-1-N16R8 module is used, which is confirmed to have 8MB Octal SPI (OPI PSRAM) as indicated in the [ESP32-S3-WROOM-1/WROOM-1U datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf).

## Tests scenarios
Tested the changes on an M5Stack CamS3 Unit. To ensure proper functionality, select the board as "M5UnitCamS3" and set the PSRAM option to "OPI PSRAM" in the Arduino IDE.

*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with M5Stack CamS3 Unit using the CameraWebServer example*

## Related links
[M5Stack CamS3 Unit Documentation](https://docs.m5stack.com/en/unit/Unit-CamS3)
[ESP32-S3-WROOM-1/WROOM-1U Datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf)

**Comment by P-R-O-C-H-Y** [comment]
> @P-R-O-C-H-Y this change should come from M5 guys. We are not sure what they used in this case. There might be boards with QIO PSRAM

@me-no-dev ok we can leave it, but according to the M5Stack CamS3 comes with OPI.

**Comment by me-no-dev** [comment]
@P-R-O-C-H-Y looks like @tarosay would like to add the change?

**Pull request merged**
