### PR TITLE
add mhetesp32devkit and mhetesp32minikit boards

### PR DESCRIPTION
**Pull request by reaper7**
because pull request #https://github.com/espressif/arduino-esp32/pull/482
is outdated and discussion in that request is very OT
I create new pull request based on latest changes.
Please add this boards.

### CODE REVIEW

**Comment by me-no-dev** [comment]
You missed to add the variants folders and pins-arduino.h :)

**Comment by reaper7** [comment]
mea culpa :)

**Comment by me-no-dev** [comment]
done :)

**Comment by reaper7** [comment]
👍

**Pull request merged**
