### PR TITLE
DOCUMENTATION: Moved installation instructions to separate page

### PR DESCRIPTION
**Pull request by Raienryu97**
* Added Fedora to contents table
* Added Issue/Bug Report section to README
* Some minor improvements

### CODE REVIEW

**Comment by copercini** [comment]
NICE!

Just an observation: If rename the folder "doc" to "docs" Github accept it's documentation (like ISSUE_TEMPLATE) inside this, cleaning the root folder

**Comment by Raienryu97** [comment]
Great idea @copercini . I've also linked all  links to local files wherever possible so it would be consistent and I felt it makes more sense than pointing to espressif/arduino-esp32 even in forks.

**Comment by me-no-dev** [comment]
is this ready for merging?

**Comment by Raienryu97** [comment]
Yep. I'm done.

**Comment by copercini** [comment]
Maybe the "Contents" summary and "Installation Instructions" can be suppressed in just one thing, because both have almost the same links

**Comment by Raienryu97** [comment]
How about the current one @copercini ? 
You can see it [here](https://github.com/Raienryu97/arduino-esp32/blob/upstream/README.md)

**Comment by copercini** [comment]
@Raienryu97 Awesome!

**Pull request merged**
