### PR TITLE
Add missing `import ssl`

### PR DESCRIPTION
**Pull request by rtwfroody**

### CODE REVIEW

**Comment by me-no-dev** [comment]
why is this? OS?

**Comment by rtwfroody** [comment]
For Windows, cygwin. On line 83 of the original the ssl module is used, but it is never imported.

**Comment by me-no-dev** [comment]
OK, but for Windows you have EXE to execute, and while I was compiling it on Windows, I had no issues or errors that class is not imported. Did you get errors?

**Comment by rtwfroody** [comment]
Yes. I got an error that the ssl module wasn't defined. I forget the exact
syntax. I ran get.py using python from a cygwin terminal. I'm not sure if
that's even supposed to work.

**Pull request closed without merging**
