### PR TITLE
Safely schedule functional ISRs: follow-up to Schedule and FunctionalInterrupt fix

### PR DESCRIPTION
**Pull request by dok-net**
This PR brings #2734 and #2743 full-circle:
Sketch-level support of only IRAM-safe ISRs as std::bind, std::function, or lambdas, plus regular C-style support for ISRs with void* argument.

### CODE REVIEW

**Comment by me-no-dev** [comment]
OMG 😮 I think all your PRs have intertwined. I would suggest you close them all and start again :)

**Comment by dok-net** [comment]
@me-no-dev  Not quite so, but not a completely wrong assessment of what's going on either ;-) ;-) ;-)
Issue #2734 still stands firmly.

**Comment by dok-net** [comment]
@me-no-dev  Not quite so, but not a completely wrong assessment of what's going on either ;-) ;-) ;-)
Issue #2748 still stands firmly.

**Comment by dok-net** [comment]
TBD... closing.

**Pull request closed without merging**
