### PR TITLE
Add `SYSTEM_EVENT_WIFI_READY` call back  + WiFiMode fixes

### PR DESCRIPTION
**Pull request by sticilface**
Add `SYSTEM_EVENT_WIFI_READY` call back: allows you to hook in, as the sdk does not generate this event for you for some reason. 

As it stands the SDK does not appear to set `WIFI_MODE_NULL` correctly.  if the wifi is initialised and set to `WIFI_MODE_NULL` it actually defaults to AP mode.  This fix keeps `WIFI_MODE_NULL` within the ESP class if the wifi has not been init yet, and works in my testing.  albeit a one sided conversation.
https://github.com/espressif/arduino-esp32/issues/1306

### CODE REVIEW

**Comment by reaper7** [comment]
this PR helps me. tnx!

**Comment by AGSPhoenix** [comment]
Fix working here too; thanks.

**Comment by petrkr** [comment]
+1 fixed, please merge

**Comment by me-no-dev** [comment]
@sticilface can you please adjust this to be inline with the latest code? we added a parameter to the low level functions in order to enable proper persistency

**Comment by me-no-dev** [comment]
pinging dr. @sticilface ! :)

**Comment by smacyas** [comment]
Does not work example WiFi Multi with the latest Arduino IDE:

#include <WiFi.h>
#include <WiFiMulti.h>

WiFiMulti wifiMulti;

void setup()
{
    Serial.begin(115200);
    delay(10);

    wifiMulti.addAP("ssid", "pswrd");
    
    Serial.println("Connecting Wifi...");
    if(wifiMulti.run() == WL_CONNECTED) {
        Serial.println("");
        Serial.println("WiFi connected");
        Serial.println("IP address: ");
        Serial.println(WiFi.localIP());
    }
}

void loop()
{
    if(wifiMulti.run() != WL_CONNECTED) {
        Serial.println("WiFi not connected!");
        delay(1000);
    }
}


Connecting Wifi...
E (300) wifi: esp_wifi_scan_start 967 wifi not start
WiFi not connected!
WiFi not connected!
WiFi not connected!
WiFi not connected!

**Comment by dsptech** [comment]
Hi,
I see that in the merging with master branch, the fix on WiFiGenericClass::getMode() was missed:
`
-    if(!wifiLowLevelInit()){
-        return WIFI_MODE_MAX;
+    if(!_esp_wifi_started){
+        return WIFI_MODE_NULL;
`

Without this fix, I experiencing that WiFi.scanComplete() will return WIFI_SCAN_RUNNING forewer.

**Pull request merged**
