### PR TITLE
fix components compile issues

### PR DESCRIPTION
**Pull request by Jason2866**
## Description of Change
Fix compile issues when Arduino is used as a component of IDF and files in managed components are changed

## Tests scenarios
Compile fail of example [idf_component_examples/hello_world](https://github.com/espressif/arduino-esp32/tree/master/idf_component_examples/hello_world)

## Related links
fix for https://github.com/espressif/arduino-esp32/issues/10167

@me-no-dev maybe there is a better fix for

### CODE REVIEW

**Comment by me-no-dev** [comment]
can you try building the libs with this change and [this](https://github.com/espressif/esp32-arduino-lib-builder/blob/master/build.sh#L118-L125) removed?

**Comment by Jason2866** [comment]
Yep, had this already in mind that this should be a solution for the issue.
Will test.

**Comment by Jason2866** [comment]
@me-no-dev No, does not solve the issue in Arduino Lib Builder. Still fails.

**Comment by me-no-dev** [comment]
ok then lets close this and add the fix to the lib builder
add `export IDF_COMPONENT_OVERWRITE_MANAGED_COMPONENTS=1` to the beginning of `build.sh`

**Comment by me-no-dev** [comment]
after all this is not Arduino's fault and does not need to be fixed here.

**Pull request closed without merging**
