### PR TITLE
[REDO] Update espota.py

### PR DESCRIPTION
**Pull request by me-no-dev**
This PR is a redo of https://github.com/espressif/arduino-esp32/pull/8239

Replaced the deprecated optparse module with argparse.
Adjusted the code style to conform to PEP 8 guidelines.
Used with statement for file handling to ensure proper resource cleanup.
Incorporated exception handling to catch and handle potential errors.
Made variable names more descriptive for better readability.
Introduced constants for better code maintainability.

### CODE REVIEW

**Comment by P-R-O-C-H-Y** [comment]
Tested on MacOS. Worked well.

**Comment by me-no-dev** [comment]
@SuGlider could you please test on Windows?

**Comment by SuGlider** [comment]
> @SuGlider could you please test on Windows?

Test done. All fine!

**Review by SuGlider — APPROVED** [review]
All Fine! Tested with Windows 11 / CMD.

**Pull request merged**
