### PR TITLE
ci(refactor): Refactor workflows and skip files

### PR DESCRIPTION
**Pull request by lucasssvaz**
## Description of Change
This PR refactors many things inside our tests and CI:

- Remove skip files and replace with `ci.json` to control how the CI will handle the sketch
- Change default flash mode for compiling tests to DIO (so it is QEMU compatible)
- Rework test workflows and scripts to use reusable workflows
- Fix Python tools upload and use `github-actions[bot]` to commit
- Cache libs to improve performance (only effective after #8720)
- Trigger workflows only when related files change
- Fix testing results publishing
- Make tests compile and run only when it is needed
- Lock python tools requirement versions so we can use pip caching
- Fix UART test for H2
- Recompile only necessary files for compilation testing

This PR will require changing the required checks for the branch protection rules.

> [!CAUTION]
> As the new `tests.yml` workflow uses `pull_request_target`, the default `GITHUB_TOKEN` permissions [are set only to `contents: read`](https://github.com/espressif/arduino-esp32/pull/9696/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR27-R28). Higher permissions are given in a per job basis. **PLEASE MAKE SURE TO PROPERLY REVIEW IF THERE IS NO POSSIBLE POINT OF VULNERABILITY**

## Tests scenarios
Tested in local fork

> [!NOTE]
> The PR CI will likely fail as the scripts changed but the workflow changes will only be effective after merging.

### CODE REVIEW

**Review by me-no-dev — APPROVED** [review]

**Review by P-R-O-C-H-Y — APPROVED** [review]
LGTM!

**Comment by P-R-O-C-H-Y** [comment]
@lucasssvaz Any link to some run on local fork to check? :)

**Comment by lucasssvaz** [comment]
@P-R-O-C-H-Y https://github.com/lucasssvaz/arduino-esp32/pull/16

**Comment by me-no-dev** [comment]
@lucasssvaz you can pull master to get the updated get.py

**Pull request merged**
