### PR TITLE
new variant LilyGO T-Display-S3

### PR DESCRIPTION
**Pull request by Eistee82**
## Description of Change
New variant LilyGO T-Display-S3.

## Related links
https://github.com/Xinyuan-LilyGO/T-Display-S3

### CODE REVIEW

**Comment by me-no-dev** [comment]
Seems you did not add a board definition in `boards.txt`?

**Comment by Eistee82** [comment]
someone can help with this?

**Comment by Eistee82** [comment]
This is my platformio /boards/lilygo_t_display_s3.json maybe someone can translate this to boards.txt

```{
    "build": {
        "arduino": {
            "ldscript": "esp32s3_out.ld",
            "memory_type": "qio_opi"
        },
        "core": "esp32",
        "extra_flags": [
            "-DBOARD_HAS_PSRAM",
            "-DARDUINO_LILYGO_T_DISPLAY_S3",
            "-DARDUINO_USB_MODE=1",
            "-DARDUINO_USB_CDC_ON_BOOT=1"
        ],
        "f_cpu": "240000000L",
        "f_flash": "80000000L",
        "flash_mode": "qio",
        "hwids": [
            [
                "0x303A",
                "0x1001"
            ]
        ],
        "mcu": "esp32s3",
        "variant": "lilygo_t_display_s3"
    },
    "connectivity": [
        "wifi",
        "bluetooth"
    ],
    "debug": {
        "default_tool": "esp-builtin",
        "onboard_tools": [
            "esp-builtin"
        ],
        "openocd_target": "esp32s3.cfg"
    },
    "frameworks": [
        "arduino",
        "espidf"
    ],
    "name": "LilyGO T-Display-S3",
    "upload": {
        "flash_size": "16MB",
        "maximum_ram_size": 327680,
        "maximum_size": 16777216,
        "require_upload_port": true,
        "speed": 921600
    },
    "url": "https://github.com/Xinyuan-LilyGO/T-Display-S3",
    "vendor": "LilyGO"
}

**Comment by me-no-dev** [comment]
You can have a look at any other ESP32-S3 based board and create a similar entry inside `boards.txt`. We fully support Arduino IDE and not PlatformIO

**Comment by me-no-dev** [comment]
@Eistee82 I have fixed your PR. Please sign the CLA above.

**Pull request merged**
