### PR TITLE
Parse the command line import of mbedtls/esp_config.h based on source

### PR DESCRIPTION
**Pull request by madhephaestus**
The arduino version of the define string looks like this
```
"-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\""
```
but the eclipse version looks like this:
```
-DMBEDTLS_CONFIG_FILE="mbedtls/esp_config.h"
```

### CODE REVIEW

**Comment by lbernstone** [comment]
This file comes from [upstream](https://github.com/espressif/esp-idf/tree/master/components/mbedtls).  It cannot be changed here.

**Comment by atanisoft** [comment]
This could also be considered a bug in how eclipse is generating the define content.

**Comment by madhephaestus** [comment]
This patch resolves the error when compiling the md5 stack in Sloeber.

```
Arduino/hardware/espressif/esp32/tools/sdk/include/mbedtls/mbedtls/md5.h:42:10: error: #include expects "FILENAME" or <FILENAME>
 #include MBEDTLS_CONFIG_FILE
```
While i understand this can not be changed here, it would be helpful for folks who get this error to have a known work around. This PR stands as documentation of a workaround then.

**Comment by lbernstone** [comment]
Either close it or move it to issues, since it will never be merged.

**Comment by madhephaestus** [comment]
This PR works around #1327

**Pull request closed without merging**
