### PR TITLE
Allow faster reuse of socket, to be able to restart WifiServer.

### PR DESCRIPTION
**Pull request by ahorn42**
See #3960 for more details of the problem and the solution. I only implemented what was proposed in this ticket, as it solves my problem, which was the same as in this ticket. Credits for the code going to @etrinh ;-)

This also is a more consistence behaviour compared to esp8266, where it also is possible to restart the wifiserver immediately on the same port.

### CODE REVIEW

**Comment by me-no-dev** [comment]
this should be optional, though I do not mind it being default

**Comment by ahorn42** [comment]
@me-no-dev what would be your suggestion to make it configurable? Would an additional overload for `begin` with a flag be an idea?  

like:
```c
void WiFiServer::begin(uint16_t port, bool socketReuse)
```

**Comment by everslick** [comment]
#1267

**Comment by everslick** [comment]
> ```void WiFiServer::begin(uint16_t port, bool socketReuse)```

how about using the same method, but with default parameter:

```void WiFiServer::begin(uint16_t port, bool socketReuse = true)```

**Comment by me-no-dev** [comment]
i agree with @everslick

**Comment by ahorn42** [comment]
@me-no-dev thanks for implementing/merging it! - you were faster than me, wanted to do this on the weekend ;D

**Comment by marioelectron** [comment]
setTimeout in ESP32 not work

**Pull request merged**
