### PR TITLE
Fix linking failure for space in path in PlatformIO builder scripts

### PR DESCRIPTION
**Pull request by maxgerhardt**
*By completing this PR sufficiently, you help us to improve the quality of Release Notes*

### Checklist
1. [x] Please provide specific title of the PR describing the change, including the component name (eg. *„Update of Documentation link on Readme.md“*)
2. [x] Please provide related links (eg. Issue, other Project, submodule PR..)
3. [x] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Summary

This PR modifies the linker flag that produces the `.map` file for the project. For projects which contain spaces, this previously resulted in an error (#6463).

## Impact

Fixes compilation for projects that contain spaces in their path or enviornment name (in `platformio.ini`, `[env:xxx]`). The `.map` file will however now be the default `firmware.map` (or whatever `PROGNAME` is set to if modified by custom scripts). 

The usage of `basename()` with environment subtition led to extremely weird bugs. This is fix here has been tested to work on both Windows on Linux. For the 'extreme case' of spaces in the project path and environment name, it correctly generates the flag on Windows
```
-Wl,-Map="C:\Users\Max\temp\Test Project With Spaces\.pio\build\esp32dev with spaces\firmware.map" 
```
and on Linux
```
-Wl,-Map="/home/max/Test Project with Spaces/.pio/build/esp32dev with spaces/firmware.map" 
```

Which would previously error out.

## Related links

See #6463.

### CODE REVIEW

**Comment by maxgerhardt** [comment]
P.S.: This is a hotfix intended to get it working / unblock people, a nicer fix would depend on https://github.com/platformio/platformio-core/issues/4205. 

Please wait a bit so that maybe a cleaner fix can be found there before merging.

**Comment by mcspr** [comment]
As mentioned in the https://github.com/platformio/platformio-core/issues/4205#issuecomment-1075640167
Have you tried
```python
    '-Wl,-Map',
    '-Wl,"${BUILD_DIR}/${PROGNAME}.map"'
```
in the `LINKFLAGS`?

**Comment by maxgerhardt** [comment]
This would likely be a cleaner and better fix, I will try in a moment.

**Comment by maxgerhardt** [comment]
Yes, this produces the correct flag

```
 -Wl,-Map -Wl,"C:\Users\Max\temp\Test Project With Spaces\.pio\build\esp32dev/firmware.map" 
```
and the file is created at the proper place.

Still a difference from the what the original script would do with `Test Project With Spaces.map` as filename, but I think this is way better..

**Comment by maxgerhardt** [comment]
Wow no, this actually *does not work*. On Linux where the path seperator is `/`, it produces

```
-Wl,-Map "-Wl, "/home/max/Test" Project with Spaces/.pio/build/esp32dev with spaces/firmware.map" 
```
there is that dead dreaded `"` in the middle of the path again and the whole quoting of the argument. This is more complicated than I thought.

**Comment by maxgerhardt** [comment]
The code `'-Wl,-Map="%s"' % join("${BUILD_DIR}", "${PROGNAME}.map")` works however.. I'll leave it at that.

**Comment by mcspr** [comment]
Strange, I was testing with the exact configuration where there were spaces in both project and env name :/

```
-Wl,-Map -Wl,"/home/max/dev/espurna test dir/code/.pio/build/esp8266 1m git base/firmware.map"
```
was created just fine in the wsl env

**Comment by maxgerhardt** [comment]
And that was with `pio upgrade --dev` latest core?

**Comment by mcspr** [comment]
Just made sure that I fetched all of the above and did a `pio upgrade --dev`
Plus, the change I mentioned for the `$framework/tools/platformio-build-esp32.py`
```
-Wl,-Map -Wl,"/home/max/dev/esp32 test dir/.pio/build/esp32dev with spaces/firmware.map"
```
:shrug:

**Comment by Jason2866** [comment]
I will do a build with this changes and update 
```
platform = https://github.com/Jason2866/platform-espressif32.git
```
So more people can test

**Comment by maxgerhardt** [comment]
This is too magical. Now I changed the line back to what @mcspr suggeted, did a `pio run -t clean && pio run` and now the code works too and generates

```
 -Wl,-Map -Wl,"/home/max/Test Project with Spaces/.pio/build/esp32dev with spaces/firmware.map"
```
Wow... I have really no idea now.

**Comment by Jason2866** [comment]
@maxgerhardt  The fix works fine. 👍 Our `map` move and naming Platformio script is still working 🤞

**Comment by me-no-dev** [comment]
@maxgerhardt can you please confirm that all is good?

**Comment by Jason2866** [comment]
@maxgerhardt @me-no-dev I have included this PR (with S3) 5 days ago and we have no negative feedback from users when compiling Tasmota with this change.
Tested with spaces in path. The error happend before is fixed.

**Review by Jason2866 — COMMENTED** [review]
Tested and verified

**Comment by me-no-dev** [comment]
Thanks guys :) Merged!

**Comment by Jason2866** [comment]
@me-no-dev Latest commit https://github.com/espressif/arduino-esp32/commit/31510f4e17a4948c005d9ad6633d53bf992189e0 did revert this PR

**Comment by me-no-dev** [comment]
the lib-builder must have grabbed arduino before merge. will reapply

**Comment by Jason2866** [comment]
@me-no-dev  No it is here https://github.com/espressif/esp32-arduino-lib-builder/blob/master/tools/copy-libs.sh#L310

**Comment by Jason2866** [comment]
Mhh, i have to look if this PR ever was in a build.

**Comment by me-no-dev** [comment]
> @me-no-dev No it is here https://github.com/espressif/esp32-arduino-lib-builder/blob/master/tools/copy-libs.sh#L310

yup that too

**Pull request merged**
