### PR TITLE
feat(boards): add Waveshare ESP32-S3-Touch-AMOLED boards

### PR DESCRIPTION
**Pull request by wurongmin**
1.I added four ESP32S3 products: ESP32-S3-Touch-AMOLED-1.43, ESP32-S3-Touch-AMOLED-1.64, ESP32-S3-Touch-AMOLED-1.91, and ESP32-S3-Touch-LCD-1.9.
2.Among them, the ESP32-S3-Touch-AMOLED-1.91 is already available online. The link is as follows: https://www.waveshare.net/shop/ESP32-S3-Touch-AMOLED-1.91.htm. The others will be available soon.
3.I believe many people will love our products for the ability to customize their own board names.This will further enhance our promotion.

### CODE REVIEW

**Comment by wurongmin** [comment]
Why can't the test board pass

**Comment by me-no-dev** [comment]
All 4 boards are the same. I suggest you combine them into 1 "ESP32-S3-Touch-AMOLED". Having multiple boards with the same VID and PID is also not a great idea. Please also look into why CI is failing for your boards

**Comment by me-no-dev** [comment]
You have not defined I2C pins: https://github.com/espressif/arduino-esp32/actions/runs/11515946102/job/32057623865?pr=10520#step:5:294

**Comment by wurongmin** [comment]
I'm sorry, they're not the same, PID's not the same

**Comment by wurongmin** [comment]
I'm sorry, they're not the same, PID's not the same

**Comment by me-no-dev** [comment]
@wurongmin why did you change the updated title?

**Comment by wurongmin** [comment]
Because I thought this description would be better, but of course I think it's better to use your previous description. If this description is necessary, I apologize for my behavior.

**Comment by wurongmin** [comment]
Hello, is there any issue here that I haven't handled well

**Comment by wurongmin** [comment]
@P-R-O-C-H-Y Hello, do you have a minute

**Comment by P-R-O-C-H-Y** [comment]
> @P-R-O-C-H-Y Hello, do you have a minute

Hi @wurongmin, how can I help?

**Comment by wurongmin** [comment]
Is there any problem in my pull request that needs to be modified? I see that the pull request has not been merged yet

**Comment by P-R-O-C-H-Y** [comment]
> Is there any problem in my pull request that needs to be modified? I see that the pull request has not been merged yet

Don't worry, we will process the PR as usual :) You have added the PR before the weekend so please be more patient.

**Comment by wurongmin** [comment]
Well.

**Comment by wurongmin** [comment]
I forgot about that, but it's fixed now.

**Comment by wurongmin** [comment]
What's the problem

**Comment by wurongmin** [comment]
Why did the motherboard test fail, what is the problem, and how to modify it

**Comment by wurongmin** [comment]
@P-R-O-C-H-Y  Hi, I was wondering, what's wrong with this

**Comment by wurongmin** [comment]
A message is displayed indicating that the mainboard test fails

**Pull request closed without merging**
