### PR TITLE
fix(net): Allow to compile without IPv6 enabled

### PR DESCRIPTION
**Pull request by me-no-dev**
cc: @Jason2866

### CODE REVIEW

**Comment by Jason2866** [comment]
@me-no-dev Great! Thx. Will test ASAP

**Comment by Jason2866** [comment]
Tested and build a framework without IPv6 support which worked to build an Arduino sketch with IPv4 only.

**Comment by Jason2866** [comment]
When IPv6 is disabled in IDF there is something broken. The example sketch https://github.com/espressif/arduino-esp32/blob/master/libraries/WebServer/examples/HelloServer/HelloServer.ino 
does compile connects to the AP but the WebServer is not reachable. Ping gets replys from the esp IP address.

**Comment by Jason2866** [comment]
@me-no-dev Webserver is now reachable with last commit. Build a small Tasmota Variant without IPv6 support. Looks like it is fully working.

**Review by SuGlider — APPROVED** [review]
All Good. Tested WiFi Server, Client and Scan.
No IPv6 saves about 28KB flash space.

**Review by P-R-O-C-H-Y — APPROVED** [review]
Tested WebServer + Client, both working.

**Pull request merged**
