### PR TITLE
change(esp_now_serial): No teardown on retry limit

### PR DESCRIPTION
**Pull request by ClockeNessMnstr**
## Description of Change

After max retries is met once the ESP_NOW_Serial_Class performs "end()" which removes the peer from ESP_NOW. 
Further messages to and from ESP_NOW_Serial are not received or sent. 
Peer should stay in ESP_NOW to re-establish connection even with data loss. 
This change will "retry and drop" the data piece by piece instead of aborting the connection.

ESP_NOW_Serial "Peer" will not remove itself from ESP_NOW_Peer list when data sent is not received by a peer. ESP_NOW_Serial::end() is still called when ESP_NOW::send() fails.

## Tests scenarios

Tested on a pair of M5Stack Stamp ESP32-C3.
Confirmed that transmission is able to continue after:  disconnecting the Receiving module from power.
Attempting to send data.
Restoring power to Receiving module.

Previously, transmission halts as the cleanup/teardown in ESP_NOW_Serial::end() is triggered. 

## Related links

I did not create an issue for this.
Issue was NowSerial had to be re-initialized essentially for every byte without knowing if the peer was present/restored.

Workaround was to use broadcast address for TX and a separate ESP_NOW_Serial peer with MAC address for RX.

### CODE REVIEW

**Comment by ClockeNessMnstr** [comment]
This seems to stop ESP_NOW_Serial::write from returning 0 although it returns "1" for the first attempt anyway. 
Going to make a couple issues instead.

**Comment by ClockeNessMnstr** [comment]
Actually it returns "1" until it does the "teardown" even though it did not succeed in sending the first byte(s). 

This is not due to my change.

**Comment by me-no-dev** [comment]
The idea makes sense, @P-R-O-C-H-Y please make sure it's implemented in the best way.

**Comment by P-R-O-C-H-Y** [comment]
@ClockeNessMnstr Hi, I did a small change to your PR so we are not bringing any breaking change and have this option as optional. Can you please test if it's ok for you? Thanks

**Review by me-no-dev — APPROVED** [review]

**Pull request merged**
