### PR TITLE
std::functioanl for WFIF event + Minor fix

### PR DESCRIPTION
**Pull request by timpur**
+ Fix for WiFi onEvent std::functional #1174
+ Minor fix for #1185 strcat_P

I couldnt work out how to remove the wifif event like how the other functions do, using a std::functional since i cant equate functionals as the same (ie the == operater doesnt work), thus i had to use an id work around, which IMHO isnt a bad thing, Please review and tell me how i can improve :) (my fist PR here....)

### CODE REVIEW

**Comment by me-no-dev** [comment]
Please add an example that would go with this :)

**Comment by timpur** [comment]
sorry @me-no-dev, somehow missed your comment, will do later today :)

**Comment by timpur** [comment]
@me-no-dev 

Anything else I need to do ?

**Comment by me-no-dev** [comment]
Nice :) Thanks! and sorry for the delay

**Comment by timpur** [comment]
no, thank you :)

**Pull request merged**
