### PR TITLE
Allow configuration of Ethernet PHY clock source

### PR DESCRIPTION
**Pull request by sauttefk**
Refer to https://github.com/espressif/esp-idf/pull/1127
The internal APLL can be used to generate the 50MHz clock for the internal EMAC and the external Ethernet PHY.
The clock can either be input on GPIO0 (as before) or output on GPIO0, GPIO16 or GPIO17 (only GPIO17 extensively tested).
New example available.

### CODE REVIEW

**Comment by sauttefk** [comment]
travis seems to be missing some configuration files?!?

**Comment by me-no-dev** [comment]
your sketch needs to be in it's own folder ;) currently Arduino will compile both sketches in that folder as one sketch.

**Comment by sauttefk** [comment]
ping. please merge.

**Comment by me-no-dev** [comment]
pong done :)

**Pull request merged**
