### PR TITLE
Add ATMegaZero ESP32-S2 microcontroller

### PR DESCRIPTION
**Pull request by eddieespinal**
## Summary
Adds support for the new ATMegaZero ESP32-S2 board. Adds the relevant section to `boards.txt` and adds the folder for the `atmegazero-esp32s2` with the proper `pins_arduino.h` to the `variants` folder.

## Impact
Allows users to compile code properly for the ATMegaZero ESP32-S2 without having to use a similar board and manually entering pin numbers.

## Links
[ATMegaZero ESP32-S2](https://atmegazero.com/#/atmegazero_esp32s2_overview)

Thanks!

### CODE REVIEW

**Comment by eddieespinal** [comment]
I signed the CLA but it still showing like I haven't. Did I miss anything?

**Comment by eddieespinal** [comment]
I can't get the first commit that has no email attached to my commit fixed.  Can anyone please tell me how I can remove this or is this a blocker to get my PR approved?  I already signed the CLA as instructed.

**Comment by pedrominatel** [comment]
Hi, @eddieespinal have you added your email to your GH account?

https://docs.github.com/en/github/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by eddieespinal** [comment]
> Hi, @eddieespinal have you added your email to your GH account?
> 
> https://docs.github.com/en/github/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

I did, the problem was that github made me use a personal token when I was pushing my changes, and I by mistake removed the local email before I pushed.  I commit again after adding my email locally and on github and that's why you see one in green. But the first commit doesn't have an email attached to it so I can't add anything.

**Comment by pedrominatel** [comment]
You can create a new PR with the same changes and we can close this one.

**Comment by eddieespinal** [comment]
> You can create a new PR with the same changes and we can close this one.

Sounds good. I'll do that now. Thanks for your help!

**Pull request closed without merging**
