### PR TITLE
Add BPI-Leaf-S3 board.

### PR DESCRIPTION
**Pull request by Wind-stormger**
## Description of Change
Add BPI-Leaf-S3 board.

## Tests scenarios
Can compile and build projects and run normally on this board, with Arduino-esp32 core v2.0.5.
The WS2812 LED can light up normally.

## Related links
[wiki page](https://wiki.banana-pi.org/BPI-Leaf-S3)

### CODE REVIEW

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Comment by P-R-O-C-H-Y** [comment]
Hi @Wind-stormger can you please update your branch with latest master of Arduino core? Than I will be able to merge your PR :)

**Comment by Wind-stormger** [comment]
@P-R-O-C-H-Y Oh~~，done.

**Comment by P-R-O-C-H-Y** [comment]
> @P-R-O-C-H-Y Oh~~，done.

@Wind-stormger Can you please update one more time? I did not see that and merged another PRs. I will now wait for your update. Thanks

**Comment by Wind-stormger** [comment]
@P-R-O-C-H-Y Done~

**Comment by P-R-O-C-H-Y** [comment]
Merged :)

**Pull request merged**
