### PR TITLE
UpdateClass - speedup flash erase/writes

### PR DESCRIPTION
**Pull request by vortigont**
This change seriously speeds up OTA image flashing process.
I was working on a [esp32-flashz](https://github.com/vortigont/esp32-flashz) lib implementing compressed OTA updates and found that UpdateClass is really slow on image writes. Even slower than esptool over serial. Looks like the main issue is in slow per-sector erase cycles.

This change implements the following:
 - on partition writes try to use large block erase
 - skip writing empty blocks of data after erase (makes sense for sparse FS images)

It gives 2-3 times speedup for raw image writes. Suppose it also depends on flash chip used.

Tested with FW/FS images

| OTA update            | Origin | This PR | This PR + zlib |
|-            |  -        |        -     |         -              |
| esp32, fw, ~1MiB                         |   23.6 s        | 9.8 s  |  10.1 s |
| esp32, fs, ~1.5MiB, 90% sparse       | 29.8 s        | 9 s  |  6 s |
| esp32-c3, fw, ~1MiB  | 15.2 s        | 9.2 s  |  9.1 s |
| esp32-c3, fs, ~1.5MiB, 90% sparse  | 10.2 s        | 4.1 s  |  2.5 s |
| esp32-s2, fw, ~1MiB  | 19.8 s        | 7.5 s  |  7.5 s |
| esp32-s2, fs, ~1.5MiB, 90% sparse  | 7.7 s          | 4.7 s  |  1.8 s |

### CODE REVIEW

**Comment by SuGlider** [comment]
Very nice optimization @vortigont, I really liked it! Thanks!

**Comment by Jason2866** [comment]
We use your PR in latest Tasmota Arduino esp32 framework. It does work well and we have got not a single issue regarding OTA since this change.
Well done and should be merged ASAP.

**Comment by vortigont** [comment]
Thanks @Jason2866. Having a positive tests feedback from a projects like Tasmota is really appreciated.
Cheers!

**Review by P-R-O-C-H-Y — APPROVED** [review]
Thanks @vortigont for the PR 👍 ! Really nice speed improvement. Tested on ESP32+ESP32S3 with smaller sketch, but got upload time 30-40% faster 🚀

**Pull request merged**
