### PR TITLE
Creat new variant for magicbit board

### PR DESCRIPTION
**Pull request by Magicblocks**
Magicbit is our new development board based on esp32 for STEM education.
DSC08788

### CODE REVIEW

**Comment by atanisoft** [comment]
This file isn't referenced by the boards.txt file, update the board.variant value to match this directory name. This should also be in the same PR as the boards.txt update.

**Comment by stickbreaker** [comment]
I would recommend you include defines for all the pins you have connected to dedicated hardware.  Buttons, OLED ...

Chuck.

**Comment by me-no-dev** [comment]
@Magicblocks please read my comments on the other PR, fix them and add them to this one if you want this merged.

**Comment by Magicblocks** [comment]
Thanks all, modified pull request according to your suggestions and updated.

**Comment by Magicblocks** [comment]
@me-no-dev hope now you can merge it. Thanks

**Comment by me-no-dev** [comment]
closing as duplicate :) I will merge your new PR (once you address the note I left there)

**Pull request closed without merging**
