### PR TITLE
added newly Deneyap Boards

### PR DESCRIPTION
**Pull request by zeynepdicle**
## Description of Change
Please describe your proposed Pull Request and it's impact.
- added newly Deneyap Mini v2 Board (ESP32S2)
- added newly Deneyap Kart 1A v2 Board (ESP32S3)
- updated Deneyap Development Boards pin_arduino.h files
## Tests scenarios
I have tested my Pull Request on Arduino-esp32 core v2.0.4, v2.0.3 and [deneyap-arduino-repo](https://github.com/deneyapkart/deneyapkart-arduino-core) v1.3.9

## Related links

Official website: https://deneyapkart.org/en/
Documentation: https://docs.deneyapkart.org/en/
Store: https://deneyapkart.org/en/magaza/ (Some products have not yet been released for sale, so they may not be on the sites.)

(*eg. Closes #number of issue*)

### CODE REVIEW

**Comment by zeynepdicle** [comment]
Hi @P-R-O-C-H-Y is it possible for my pull request to merge before the new version(v2.0.6) ?

**Comment by P-R-O-C-H-Y** [comment]
Hi @zeynepdicle, dont worry. Will try ti review ASAP.

**Comment by zeynepdicle** [comment]
Thank you @P-R-O-C-H-Y  :)

**Comment by zeynepdicle** [comment]
> Thank you @P-R-O-C-H-Y :)

Does it known when the new releases ? If it is know, which page should I look at ?

**Comment by zeynepdicle** [comment]
> @zeynepdicle New release should be somewhere in the middle of December :) Can you please provide links to the boards details? Thanks

in pins_arduino.h files ?

**Comment by zeynepdicle** [comment]
> @zeynepdicle New release should be somewhere in the middle of December :) Can you please provide links to the boards details? Thanks

@P-R-O-C-H-Y i did

**Comment by zeynepdicle** [comment]
@P-R-O-C-H-Y 
 I updated PIDs for Deneyap Development Boards

> Deneyap Mini (ESP32-S2)
> Deneyap Mini v2 (ESP32-S2)
> Deneyap Kart 1A v2 (ESP32-S3)
> Deneyap Kart G (ESP32-C3)

**Comment by zeynepdicle** [comment]
Hi again @P-R-O-C-H-Y :)
Is there a problem with my pull request? I will fix it if any.

**Pull request closed without merging**
