### PR TITLE
Disable SimpleBLE when BT not enabled

### PR DESCRIPTION
**Pull request by APokorny**
SimpleBLE would otherwise require a bt header file to be reachable in the include paths.
This forces people to enable bt even when not needed. Which is a pity because that also disables a memory region for BT exclusive use.

Signed-off-by: Andreas Pokorny <andreas.pokorny@siemens.com>

### CODE REVIEW

**Comment by copercini** [comment]
This is good but will cause issues when install external libraries like ESPWebServer, SPIFFS , Ethernet on ESP32 folder

**Comment by APokorny** [comment]
Issues like?

**Comment by APokorny** [comment]
Ah ok. So you are relying on the wildcard in the components.mk of arduino. So you are creating additional checkouts inside a project? That does not sound like a proper solution. 
I thought there is an EXTRA_COMPONENTS_DIR variable inside the build system to add stuff to your project

**Comment by me-no-dev** [comment]
There must be a better solution than listing all the libs manually ;) seems not right to edit this file each time a lib is added.

**Comment by APokorny** [comment]
Alternatively one could maintain something like that (incomplete example):
```
ARDUINO_CORE_LIBS := $(filter-out libraries/WiFiClientSecure/src,$(filter-out libraries/SimpleBLE/src,$(patsubst $(COMPONENT_PATH)/%,%,$(wildcard $(COMPONENT_PATH)/libraries/*/src))))
```

**Comment by APokorny** [comment]
Does that work for you now?

**Comment by me-no-dev** [comment]
OK, here is wat I will suggest: use ifdef in the source files, so source is not compiled.

**Comment by me-no-dev** [comment]
implemented here: https://github.com/espressif/arduino-esp32/commit/c66a020e8067f657e730d018700e7de5b23175d4

**Pull request closed without merging**
