### PR TITLE
bugfix(i2c): fix signal glitch on sda and scl  pin

### PR DESCRIPTION
**Pull request by ESP32DE**
see https://github.com/espressif/arduino-esp32/issues/1061
here a tested version and an optional suggestion

### CODE REVIEW

**Comment by ESP32DE** [comment]
note:
i tested the patch with an earlier version successful
if you use the actually version you must use the option 
to make the pin HIGH before you setup the pin as OPENDRAIN
( see the comment in the code ) 

so perhabs would be better, if we use the optional version then, 
cause i think, there is nobody using an earlier version ?

just in time tested with the actually version too now
i did use the optional and set Pin Level HIGH before i set it as OPENDRAIN
successful too.

**Comment by perkint4** [comment]
On 3 Feb 2018 19:19, "rudi ;-)" <notifications@github.com> wrote:

note:
i tested the patch with an earlier version successful
if you use the actually version you must use the option
to make the pin HIGH before you setup the pin as OPENDRAIN
( see the comment in the code )

so perhabs would be better, if we use the optional version then,
cause i think, there is nobody using an earlier version ?

just in time tested with the actually version too now
i did use the optional and set Pin Level HIGH before i set it as OPENDRAIN
successful too.

**Comment by ESP32DE** [comment]
i will close this PR cause this is only work in a prev version
we must use the optional in the actually version to kick the glitch on sda and scl on wire.begin().
so you will get asap the optional for better merging :)

**Comment by ESP32DE** [comment]
see PR https://github.com/espressif/arduino-esp32/pull/1065
i added the optional to this.

**Pull request closed without merging**
