### PR TITLE
backport: variants from 3.0.0 + fixes

### LINKED ISSUE #9037: Wrong PIN for RGB LED on board lolin_s3_mini
### Board

lolin_s3_mini

### Device Description

Its not possible to control the RGB led on this board with the neopixelWrite() function since the PIN number is wrong in the pins_arduino.h

The pin definition for this board is
``#define RGB_BUILTIN LED_BUILTIN``

In neopixelWrite the following operation is done
```
#ifdef RGB_BUILTIN
  if(pin == RGB_BUILTIN){
    _pin = RGB_BUILTIN-SOC_GPIO_PIN_COUNT;
  }
#endif
```

So the for this to work the definition for this board needs to be 
``#define RGB_BUILTIN LED_BUILTIN+SOC_GPIO_PIN_COUNT``

Not sure if the macro or the LED_BUILTIN constant should be changed so I put it as a bug report instead of PR.

If this is changed its possible to change the rgb led color on this board. 

### Hardware Configuration

Just plain board not connections

### Version

v2.0.14

### IDE Name

PlatformIO

### Operating System

Windows 11

### Flash frequency

40

### PSRAM enabled

yes

### Upload speed

115200

### Description

It should be possible to control the RGB led with neopixel on this board.

### Sketch

```cpp
#include <Arduino.h>

void setup() {
  neopixelWrite(RGB_BUILTIN, 255, 0, 0);
  delay(1000);
  neopixelWrite(RGB_BUILTIN, 0, 255, 0);
  delay(1000);
  neopixelWrite(RGB_BUILTIN, 0, 0, 255);
}

void loop() {
}
```

### Debug Message

```plain
E (240) rmt: rmt_set_gpio(526): RMT GPIO ERROR
E (240) rmt: rmt_config(686): set gpio for RMT driver failed
[   331][D][esp32-hal-rmt.c:615] rmtInit():  -- TX RMT - CH 0 - 1 RAM Blocks - pin 254
[   337][E][esp32-hal-rmt.c:631] rmtInit(): RMT failed to initilize.
[   343][E][esp32-hal-rgb-led.c:18] neopixelWrite(): RGB LED driver initialization failed!
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Description of Change

Backports changes from 3.0.0 to `variants` and fixes the "unphone8" wrong board definition.
Only changes boards that were already in 2.0.14. No new board is added.

RGB_LED is now fixed for all boards with NEO LED. 
The same for BUILTIN_LED. Both will work fine with `digitalWrite()` and `neo_pixel_write()`
Applied fixes done by the board makers in 3.0.0 based on PR #8726 

## Tests scenarios
Quick random testing with some boards.

## Related links

Closes #9037

### CODE REVIEW

**Review by P-R-O-C-H-Y — APPROVED** [review]
Looks good, lets run all boards test after merging this to catch if there is any issue :)

**Comment by P-R-O-C-H-Y** [comment]
Also we may include board fixes from PR: Heltec ESP32 Series boards update #9367

**Review by lucasssvaz — APPROVED** [review]
LGTM

**Comment by SuGlider** [comment]
> Also we may include board fixes from PR: Heltec ESP32 Series boards update #9367

From #9367, just `variants/heltec_wireless_stick_v3/pins_arduino.h` can be backported.
Done now in https://github.com/espressif/arduino-esp32/pull/9381/commits/f89d902028c4f407190f97585dfaa21e7b2898f3

**Pull request merged**
