### PR TITLE
feather variant

### PR DESCRIPTION
**Pull request by ladyada**
Hiya here is the Feather ESP32 variant details!

### CODE REVIEW

**Comment by me-no-dev** [comment]
I was just watching your video from earlier :D

**Comment by ladyada** [comment]
yay hopefully the fun one where i check out the first board, not the one where i spent 30 minutes fighting win 7 :)

**Comment by ladyada** [comment]
btw im still seeing some issues with SD cards using the built in library, perhaps. but i'll get you some hardware so you can have something to test against

**Comment by me-no-dev** [comment]
actually both :)

**Comment by me-no-dev** [comment]
Sure thing :) though I can check probably on the hardware I have as well. Now that I have your board definitions :)
Could you maybe describe the issues a bit more?

**Pull request merged**
