### PR TITLE
Board name change (ETBoard -> ET-Board)

### PR DESCRIPTION
**Pull request by ketri2484**
ETBoard -> ET-Board

### CODE REVIEW

**Comment by me-no-dev** [comment]
this looks like board was added, not changed

**Comment by ketri2484** [comment]
> this looks like board was added, not changed

I changed 'boards.txt' file. 
It changed ETBoard to ET-board. 
Check please.

**Comment by me-no-dev** [comment]
if you have changed the board, then the old one would have been shown as deleted. it seems you only added lines to the file, not deleting the old ones.

**Comment by me-no-dev** [comment]
now it looks proper. please check the pins for SDA and SCL. seems they have been changed

**Comment by ketri2484** [comment]
> now it looks proper. please check the pins for SDA and SCL. seems they have been changed

Thank you.
It is correct to change pins for SDA and SCL.

**Comment by me-no-dev** [comment]
what are the correct I2C pins though? 21 an 22?

**Comment by ketri2484** [comment]
> what are the correct I2C pins though? 21 an 22?

SDA = 21
SCL = 22

**Pull request merged**
