### PR TITLE
Add overloads to support __FlashStringHelper like ESP8266 has them.

### LINKED ISSUE #8108: Compile error under 2.0.8 if library function explicitly returns const __FlashStringHelper * from F() macro
### Board

ESP32

### Device Description

YUBOX-Node

### Hardware Configuration

No special hardware configuration needed.

### Version

v2.0.8

### IDE Name

Arduino IDE 2.1.0

### Operating System

Fedora Linux 38 x86_64

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

115200

### Description

After updating to Arduino-ESP32 2.0.8, the attached sketch will no longer compile, and displays the following error messages:
```
In file included from /home/alex/.arduino15/packages/esp32-alternatives/2.0.8/hardware/esp32/2.0.8/cores/esp32/Arduino.h:176,
                 from /home/alex/programa/practica/arduino/esp32/test-bug-compile-fail-flashstringhelper/test-bug-compile-fail-flashstringhelper.ino:1:
/home/alex/programa/practica/arduino/esp32/test-bug-compile-fail-flashstringhelper/test-bug-compile-fail-flashstringhelper.ino: In function 'const __FlashStringHelper* testfunc()':
/home/alex/.arduino15/packages/esp32-alternatives/2.0.8/hardware/esp32/2.0.8/cores/esp32/WString.h:38:42: error: cannot convert 'const char*' to 'const __FlashStringHelper*' in return
 #define F(string_literal) (string_literal)
                                          ^
/home/alex/programa/practica/arduino/esp32/test-bug-compile-fail-flashstringhelper/test-bug-compile-fail-flashstringhelper.ino:5:10: note: in expansion of macro 'F'
   return F("test");
          ^

exit status 1

Compilation error: exit status 1
```

The same sketch compiles correctly under previous 2.0.7.

### Sketch

```cpp
#include <Arduino.h>

const __FlashStringHelper * testfunc(void)
{
  return F("test");
}

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:
  delay(1000);
}
```

### Debug Message

```plain
In file included from /home/alex/.arduino15/packages/esp32-alternatives/2.0.8/hardware/esp32/2.0.8/cores/esp32/Arduino.h:176,
                 from /home/alex/programa/practica/arduino/esp32/test-bug-compile-fail-flashstringhelper/test-bug-compile-fail-flashstringhelper.ino:1:
/home/alex/programa/practica/arduino/esp32/test-bug-compile-fail-flashstringhelper/test-bug-compile-fail-flashstringhelper.ino: In function 'const __FlashStringHelper* testfunc()':
/home/alex/.arduino15/packages/esp32-alternatives/2.0.8/hardware/esp32/2.0.8/cores/esp32/WString.h:38:42: error: cannot convert 'const char*' to 'const __FlashStringHelper*' in return
 #define F(string_literal) (string_literal)
                                          ^
/home/alex/programa/practica/arduino/esp32/test-bug-compile-fail-flashstringhelper/test-bug-compile-fail-flashstringhelper.ino:5:10: note: in expansion of macro 'F'
   return F("test");
          ^

exit status 1

Compilation error: exit status 1
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by dok-net**
Fixes #8108

### CODE REVIEW

**Review by mrengineer7777 — COMMENTED** [review]
Restores previous definitions for `F` and `FPSTR` in Wstring.h.  This should fix breaking changes in other libraries.  I'm not sure about the other changes introduced by this PR.

**Comment by me-no-dev** [comment]
Can you pease split the changes into separate PRs. There seem to be three unrelated changes.
`F()` used to be `#define F(string_literal) (FPSTR(PSTR(string_literal)))`

**Comment by dok-net** [comment]
There seem to be three unrelated changes. `F()` used to be `#define F(string_literal) (FPSTR(PSTR(string_literal)))`

The reverted macros now just drop the PSTR, becauses it's a dummy on ESP32, and will always be (?):
`cores/esp32/pgmspace.h:#define PSTR(s)       (s)`

**Comment by tueddy** [comment]
Please add this to [2.0.9](https://github.com/espressif/arduino-esp32/milestone/11), it's a high visible show stopper

**Pull request merged**
