### PR TITLE
feat:增加t2项目外设驱动代码！

### PR DESCRIPTION
**Pull request by ligping**
*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

### Checklist
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [ ] Please **update relevant Documentation** if applicable
4. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
Please describe your proposed Pull Request and it's impact.

## Tests scenarios
Please describe on what Hardware and Software combinations you have tested this Pull Request and how.

(*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with ESP32 and ESP32-S2 Board with this scenario*)

## Related links
Please provide links to related issue, PRs etc.

(*eg. Closes #number of issue*)

### CODE REVIEW

**Comment by lbernstone** [comment]
This repository provides compatibility with the Arduino API.  It has some drivers to support the built-in devices of esp32.  External drivers belong in external repositories.

**Comment by SuGlider** [comment]
No PR description.
CLA not signed.
Too many changes in a single PR.

I don't see way to move forward with it...

**Comment by VojtechBartoska** [comment]
@ligping Please provide mor info about this PR otherwise it will be closed. 

Also keep in mind that main language of this repository is English.

Thanks!

**Comment by SuGlider** [comment]
Closing it.... This PR sounds like it is creating a new package as seen in:
```
OUTPUT_DIR="$GITHUB_WORKSPACE/build"
PACKAGE_NAME="ticos-kit-$RELEASE_TAG"
PACKAGE_JSON_MERGE="$GITHUB_WORKSPACE/.github/scripts/merge_packages.py"
PACKAGE_JSON_TEMPLATE="$GITHUB_WORKSPACE/package/package_esp32_index.template.json"
PACKAGE_JSON_DEV="package_ticos_kit_dev_index.json"
PACKAGE_JSON_REL="package_ticos_kit_index.json"
```

[package/package_esp32_index.template.json](https://github.com/espressif/arduino-esp32/pull/6956/files#diff-5cc2de46219528ecaffa00a28b18719ca62cbebebe50bfbee8d49c98cee14fa6)
https://github.com/espressif/arduino-esp32/pull/6956/files#diff-5cc2de46219528ecaffa00a28b18719ca62cbebebe50bfbee8d49c98cee14fa6R1-R17

**Pull request closed without merging**
