### PR TITLE
Add 16MB partition large APPS w/ OTA & SPIFFS

### PR DESCRIPTION
**Pull request by Kadah**
* 7.25MB APPS partitions w/OTA
* Same SPIFFS partition size as default

### CODE REVIEW

**Comment by Kadah** [comment]
I attempted to make the menu option brief but also convey the increased size.

I currently don't have one, but an 8MB flash option would complete the set of standard sizes the ESP-WROOM-32D/U and ESP32-WROVER come in.

**Comment by lbernstone** [comment]
Is this a generally useful configuration?  I don't think we should clutter up the menus.  Are your apps getting to 7.25MB?  I made the app partitions on ffat.csv 2MB each.  Should this be larger?

**Comment by Kadah** [comment]
(Ignore the random PR close, Github was only showing the "close and comment button. For some reason it has regularly not shown any of the green buttons this week.)

**Comment by me-no-dev** [comment]
yeah... why so large apps? why not more FS instead?

**Comment by Flo082002** [comment]
Maybe it is possible to add an option to create custom partition sizes.

**Comment by lbernstone** [comment]
> Maybe it is possible to add an option to create custom partition sizes.

https://github.com/francis94c/ESP32Partitions

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/1184

**Pull request closed without merging**
