### PR TITLE
feat (Variants) Added custom boards variants GLYPH C3, GLYPHC6 & GLYPHH2

### PR DESCRIPTION
**Pull request by pcbcupid**
Added custom boards variants GLYPH C3, GLYPHC6 & GLYPHH2 based on ESP32C3, ESP32C6 & ESP32H2

## Description of Change
This Pull Request add support to our three new hardware GLYPHC3 , GLYPHC6 and GLYPHH2 which are based on ESP32C3, ESP32C6 and ESP32H2. Features onboard LiPo/Li-ion charging circuit, QWIIC connector for QWIIC compatible sensors/modules and "Adafruit Feather Series" style footprint. 

Links to the product : 
- GLYPH C3 : https://shop.pcbcupid.com/product/gd001/
- GLYPH C6 : https://shop.pcbcupid.com/product/gd002/
- GLYPH H2 : https://shop.pcbcupid.com/product/gd003/

## Tests scenarios
The hardware's are tested with these changes on a GLYPH boards using the Arduino IDE with ESP32 core. Also verified that the defined pins correspond to the correct hardware pins on the board.

## Related links
These links contain the information & documentation related to GLYPH boards : 
- GLYPH C3 Getting started : https://learn.pcbcupid.com/boards/glyph-c3
- GLYPH C6 Getting started : https://learn.pcbcupid.com/boards/glyph-c6
- GLYPH H2 Getting started : https://learn.pcbcupid.com/boards/glyph-h2

### CODE REVIEW

**Comment by P-R-O-C-H-Y** [comment]
Hello @pcbcupid, can you please fix the errors from the CI. The build.board must be uppercase.
Also as those are your first boards in the repository, please add them to the end of the boards.txt file. Thanks

**Comment by P-R-O-C-H-Y** [comment]
@pcbcupid Also please sign the CLA. Without that the PR cannot be merged.

**Comment by me-no-dev** [comment]
@pcbcupid please try again in a bit. There seems to have been an issue with the CLA service.

**Comment by pcbcupid** [comment]
image

@P-R-O-C-H-Y Seems like the license/cla is not updating or reflecting on this pull request.

**Comment by P-R-O-C-H-Y** [comment]
@pcbcupid Seems its ok now :)

**Comment by pcbcupid** [comment]
@P-R-O-C-H-Y Yes! Thanks.

**Pull request merged**
