### PR TITLE
Add new board (Deneyap Kart 1A) 

### PR DESCRIPTION
**Pull request by zeynepdicle**
*By completing this PR sufficiently, you help us to improve the quality of Release Notes*

### Checklist
1. [ ] Please provide specific title of the PR describing the change, including the component name (eg. *„Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (eg. Issue, other Project, submodule PR..)
3. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)

*This entire section above can be deleted if all items are checked.*

-----------
## Summary
Please describe your proposed PR and what it contains.

## Impact
Please describe impact of your PR and it's function.

## Related links
Please provide links to related issue, PRs etc.

### CODE REVIEW

**Comment by me-no-dev** [comment]
@zeynepdicle there seems to be a conflict with boards.txt. Would you please take care of it?

**Comment by zeynepdicle** [comment]
> @zeynepdicle there seems to be a conflict with boards.txt. Would you please take care of it?

I take care of it. I fixed it.

**Comment by me-no-dev** [comment]
it is not yet fixed.
Screenshot 2022-02-21 at 10 25 57

**Comment by zeynepdicle** [comment]
what is the exact problem ?

**Comment by me-no-dev** [comment]
I can not see because you have made the PR read-only for maintainers. I would have been able to fixed it otherwise :)

**Pull request closed without merging**
