### PR TITLE
Define Wire1 pins for ESP32-S3 PowerFeather

### PR DESCRIPTION
**Pull request by powerfeatherdev**
Define Wire1 pins for ESP32-S3 PowerFeather.

### CODE REVIEW

**Comment by powerfeatherdev** [comment]
@P-R-O-C-H-Y would this be too late to add to 2.0.15?

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Comment by P-R-O-C-H-Y** [comment]
> @P-R-O-C-H-Y @SuGlider @me-no-dev Can this still make it into 2.0.15?

@powerfeatherdev Yes, right on time :)

**Comment by powerfeatherdev** [comment]
@P-R-O-C-H-Y :sweat_smile:

**Comment by powerfeatherdev** [comment]
@P-R-O-C-H-Y, not to be pushy or anything, but has the release date (roughly) for 2.0.15 been set?

**Comment by P-R-O-C-H-Y** [comment]
@powerfeatherdev I would say roughly 2-3 weeks.

**Comment by powerfeatherdev** [comment]
@P-R-O-C-H-Y I see. I was hoping to launch PowerFeather this week - I'm just going to have to adjust.

**Pull request merged**
