### PR TITLE
Improves time for setting touch interrupt

### LINKED ISSUE #7097: touchAttachInterrupt takes 25ms for each pin!!!
### Board

ESP32-WROOM-32E (4MB Flash)

### Device Description

Nothing

### Hardware Configuration

Using On both WROOM Tester and on PCB

### Version

v2.0.4

### IDE Name

Arduino IDE 1.8.19

### Operating System

Windows 10

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

I was using ESP32 Arduino v1.0.6 to program ESP32-WROOM-32E (4MB Flash) and had no issue whatsoever. Since I upgraded to ESP32 Arduino v2.0.4 I noticed lags in hardware response. Tracking down I reached some strange difference between two versions. touchAttachInterrupt that took less than 1ms in v1.0.6 now takes 26ms!

### Sketch

```
long beginDur = 0;

void IRAM_ATTR gotTouch() {}

void setup() {
    Serial.begin(115200);
}

void loop() {
    beginDur = millis();
    touchAttachInterrupt(4, gotTouch, 30);
    Serial.println("dur: " + String(millis() - beginDur));
}
```

### Debug Message

```plain
Serial output while using ESP32 Arduino v1.0.6:

dur: 0
dur: 0
dur: 0
dur: 0

Serial output while using ESP32 Arduino v2.0.4:

dur: 26
dur: 26
dur: 26
dur: 26
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Description of Change
Fixes and improves the time it takes to set an interrupt with Touchpads in ESP32.

## Tests scenarios
With ESP32 as reported in #7097 

``` cpp
long beginDur = 0;

void IRAM_ATTR gotTouch() {}

void setup() {
    Serial.begin(115200);
}

void loop() {
    beginDur = millis();
    touchAttachInterrupt(4, gotTouch, 30);
    Serial.println("dur: " + String(millis() - beginDur));
}
```

Espected output shall report 0 as time.

## Related links
Fixes #7097

### CODE REVIEW

**Comment by P-R-O-C-H-Y** [comment]
@SuGlider With this PR, the Touch Interrupt no longer works for me on ESP32. It initialised fast (0ms) but it does not work.

Check it with this sketch:

```
long beginDur = 0;

void IRAM_ATTR gotTouch() {
    Serial.println("GOT TOUCH");
  }

void setup() {
    Serial.begin(115200);

    for(int i = 0; i<10 ; i++)
    {
      beginDur = millis();
      touchAttachInterrupt(2, gotTouch, 40);
      Serial.println("dur: " + String(millis() - beginDur));
    }
}

void loop() {

}
```

**Comment by P-R-O-C-H-Y** [comment]
@SuGlider I think the threshold is not working anymore, because we still use `TOUCH_V1` but the threshold uses the function from `TOUCH_V2`.

**Review by P-R-O-C-H-Y — CHANGES_REQUESTED** [review]
Take a look on comments above

**Comment by SuGlider** [comment]
Fixed. Thanks!

**Review by P-R-O-C-H-Y — APPROVED** [review]
LGTM!

**Pull request merged**
