### PR TITLE
Implement official Arduino IDE debugger API

### PR DESCRIPTION
**Pull request by pillo79**
## Description of Change
This PR replaces the current experimental sketch debugging description with a full implementation according to the finalized [Arduino Platform Debug Specification](https://arduino.github.io/arduino-cli/latest/platform-specification/#sketch-debugging-configuration).

**The current experimental debug configuration will no longer be supported with the release of Arduino IDE 2.3.0.**

The biggest improvement is that now the contents of `launch.json` can be fully customized from entries in `platform.txt`, so there is no need to copy files in the sketch folder and advanced customizations become possible.

In particular, `debug_custom.json` is not used anymore.

## Tests scenarios
Tested on Arduino Nano ESP32 with current nightly IDE, available from [here](https://www.arduino.cc/en/software) in the Nightly Builds section, or 2.3.0+ when it becomes public.

### CODE REVIEW

**Comment by me-no-dev** [comment]
@pillo79 could you also backport this to `release/2.x`? We will probably have to release 2.0.15 soon with some security fixes (and more)

**Comment by pillo79** [comment]
@me-no-dev thanks for looking. Sure, will do! :+1:

**Comment by pillo79** [comment]
I edited descriptions only, but rebasing to current master (60395ed6) I apparently picked up something that causes a build error. I will revert to the previous branch point for the CI to complete.

**Comment by pillo79** [comment]
Fixed a quote-related escaping issue (my personal favs :sweat_smile:) and also included a small addition to `on-release` that was present on 2.x but I missed when preparing the 3.x porting. I will test tomorrow with the IDE team then release for actual review/merge.

**Comment by kittaakos** [comment]
> available from [here](https://www.arduino.cc/en/software) in the Nightly Builds section,

Direct link: https://www.arduino.cc/en/software#nightly-builds

**Comment by pillo79** [comment]
IDE 2.3 has been [released](https://blog.arduino.cc/2024/02/07/ide-2-3-is-out-and-youll-love-the-new-debugging-features-in-it/) yesterday 👍

**Comment by cristiancardosodexcom** [comment]
Captura de pantalla 2024-03-27 a la(s) 9 30 46 p m
Does not work debugger for esp32-dev module.

**Comment by pillo79** [comment]
> Does not work debugger for esp32-dev module. `embedded:startup.tcl:28: Error: Can't find debug.cfg `Arduino IDE 2.3.2

Hello @cristiancardosodexcom, what is the version of the core you are using? Is that on a Mac?

**Comment by cristiancardosodexcom** [comment]
> > Does not work debugger for esp32-dev module. `embedded:startup.tcl:28: Error: Can't find debug.cfg `Arduino IDE 2.3.2
> 
> Hello @cristiancardosodexcom, what is the version of the core you are using? Is that on a Mac?

Yes it's a MAC.
bool ENGINE_OFF = false;

**Comment by pillo79** [comment]
I meant the Arduino-ESP32 core :slightly_smiling_face: 
What does the IDE report here?
image
(if you are using a local Git copy please provide the commit). Thanks

**Pull request merged**
