### PR TITLE
Fixed M5Stack build.board name

### PR DESCRIPTION
**Pull request by m5stack**

### CODE REVIEW

**Comment by BrunDog** [comment]
Despite this, it doesn't seem the pre-processor definition works correctly:

`#ifdef M5Stack_Core_ESP32`

is ignored on Arduino IDE with current ESP32 1.0.2. Any tips?

**Comment by atanisoft** [comment]
@BrunDog ```#ifdef ARUDINO_M5Stack_Core_ESP32``` is the correct reference for it. all of the defines are prefixed with ARDUINO_.

**Comment by BrunDog** [comment]
Wow I'm dumb... yes, forgot this. Trees/forest thingy. Thanks! BTW you have ARDUINO spelled incorrectly.

**Comment by atanisoft** [comment]
> BTW you have ARDUINO spelled incorrectly.

fingers move faster than brain :)

**Pull request merged**
