### PR TITLE
Improve support for hand-written asm source files

### PR DESCRIPTION
**Pull request by ivankravets**
Improve support for hand-written asm source files and document flag scopes

### CODE REVIEW

**Comment by me-no-dev** [comment]
these parts of the files are automatically generated by the lib-builder. Values are extracted from IDF's build system.

**Comment by ivankravets** [comment]
How about with `ASFLAGS` and `ASPPFLAGS`? There is a bug in the current scripts with `"-x", "assembler-with-cpp"` which is set for `ASFLAGS` instead of `ASPPFLAGS`.

**Comment by me-no-dev** [comment]
[This](https://github.com/espressif/esp32-arduino-lib-builder/blob/master/tools/copy-libs.sh#L247-L313) is the part of the script that generates your configs. Above it is how they are obtained. I suggest you look there for resolution :)

**Comment by ivankravets** [comment]
Could you adapt my fixes for the ASM? I'm not so good in the Bash. I'll close this PR. Thanks.

**Comment by me-no-dev** [comment]
@ivankravets will the change for "ASPPFLAGS" be enough? Can I just rename "ASFLAGS" to "ASPPFLAGS"?

**Comment by ivankravets** [comment]
If you don't use bare ASM (without C preprocessor, small `.s`), then just rename `ASFLAGS` -> `ASPPFLAGS`.

The `ASFLAGS` are common for `.s` and `.S`, whereas `ASPPFLAGS` only for `.S`. The `.s` very often require machine-related flags. However, it seems they are not required for ESP toolchains.

**Comment by me-no-dev** [comment]
Will be part of 2.0.4 :)

**Pull request closed without merging**
