### PR TITLE
feat(esp32-s3): Add support for auto-baudrate-detection on S3

### PR DESCRIPTION
**Pull request by imwhocodes**
Add support for auto-baudrate-detection on S3 variant of esp32, with different clock support (could be extended to C3 variant)

-----------
## Description of Change
Add support (fix `hal` wrapper) for auto-baudrate-detection to the esp32-S3
Currently there was no support for it and correct codepath was missing (and not even hinting to the missing support like done for the C3)

Added `#ifdef` for enabling the baudrate detection hardware
Added codepath for correctly computing baudrate given the clock source used for the uart hardware block

## Tests scenarios
I have tested my Pull Request on Arduino-esp32 core master with ESP32-S3 Boards

## Related links
Close https://github.com/espressif/arduino-esp32/issues/7718
Progress https://github.com/orgs/espressif/projects/3/views/15?pane=issue&itemId=19207281

## Note about calculations and ESP32-C3
I cannot test because i have no board with this chip (esp32-C3) but I'm supposing that the same code could be used also for fixing this:
https://github.com/espressif/arduino-esp32/blob/23d715af1b185fac21558c907af4ff5b86526aa4/cores/esp32/esp32-hal-uart.c#L670-L674

In particular S3 and C3 variant support other clock sources other than **APB** and they are in fact defaulted to XTAL clock as source by Arduino, so the previous problem could be by this line not tacking that in account:
https://github.com/espressif/arduino-esp32/blob/23d715af1b185fac21558c907af4ff5b86526aa4/cores/esp32/esp32-hal-uart.c#L725

### CODE REVIEW

**Comment by SuGlider** [comment]
> [CLA assistant check](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7782) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7782) before we can accept your contribution.
> 
> **Luca** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=7782) it.

@imwhocodes - Please check the CLA and if you agree, please sign it.

**Comment by imwhocodes** [comment]
> > [CLA assistant check](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7782) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/arduino-esp32?pullRequest=7782) before we can accept your contribution.
> > **Luca** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/arduino-esp32?pullRequest=7782) it.
> 
> @imwhocodes - Please check the CLA and if you agree, please sign it.

@SuGlider I accepted multiple times the CLA, if i click on the link it say  '`You have agreed to the CLA for espressif/arduino-esp32`' but yet if i come here it tell me I did't signed it yet

**Comment by SuGlider** [comment]
> > @imwhocodes - Please check the CLA and if you agree, please sign it.
> 
> @SuGlider I accepted multiple times the CLA, if i click on the link it say '`You have agreed to the CLA for espressif/arduino-esp32`' but yet if i come here it tell me I did't signed it yet
> 
> Edit: OK I pushed my first commit from a pc with the author/email configured wrongly

@imwhocodes 

I'm sorry, but it seems that CI won't let it pass because of commit 16ade7e56f760b4550f6b41627b51d335e738c8f
It was done by another user (the wrongly configured one) and because it has no CLA/valid Github user, it won't be able to pass CI and then we can't merge it after reviewing it.

Please close this PR and open a new one with a single commit from you valid GH user ID.

**Review by SuGlider — COMMENTED** [review]
@imwhocodes 

I'm sorry but this PR doesn't work for ESP32-S3. Neither for the ESP32-C3.
The baud rate detection only works for the ESP32 and ESP32-S2

This is the sketch I have used to test it:
``` cpp
// This sketch works correctly with ESP32 and ESP32S2 only, so far.
// ESP32C3 and ESP32S3 seems to fail with baud rate detection
void setup() {
  Serial.begin(115200);
  Serial.println("\nTesting baud rate detection\n");
}

void loop() {
  Serial.println("Started detection for next 20 seconds.");
  Serial.println("Use the Serial Monitor. Change the baud rate in the botton of the window.");
  Serial.println("Send characters using the Serial Monitor and get the detected baud rate.");
  Serial.flush();

  Serial.begin(0);
  unsigned long detectedBaudRate = Serial.baudRate();

  if (detectedBaudRate) {
    Serial.printf("\nDetected baudrate is %lu\n\n", detectedBaudRate);
  } else {
    // this may not display correctly in the Serial Monitor, given that it failed.
    Serial.println("\nNo baudrate detected, Serial will not work!\n\n");
  }
}
```

**Comment by SuGlider** [comment]
@VojtechBartoska @me-no-dev 
I have tried several ways for a couple days to make it work, but it seems that both C3 and S3 can't make it work correctly.
Therefore, the current code is valid and works fine only for the ESP32 and ESP32S2.

**Comment by imwhocodes** [comment]
@SuGlider I don't have a chip at hands right now, as I said in the issue I have this code running on production and I can confirm it working, as I said heavily tested on **ESP32-WROOM-32UE** and **ESP32-S3-WROOM-1U-N8** at both **115200** and **460800** (other baudrates tested but not in production)

Two things:
- On my test I have around 100 consecutive bytes every 200ms in the least busy moment
- Could it be that on your configuration `Serial` is actually by default `HWCDC` (the usb one)

Let me know

**Comment by SuGlider** [comment]
> @SuGlider I don't have a chip at hands right now, as I said in the issue I have this code running on production and I can confirm it working, as I said heavily tested on **ESP32-WROOM-32UE** and **ESP32-S3-WROOM-1U-N8** at both **115200** and **460800** (other baudrates tested but not in production)

It works correctly for any baud rate on the ESP32-WROOM-32, but not on the ESP32-S3-WROOM.
Using the testing sketch I had posted here, it works for a few baud rates, but not for any - using the ESP32-S3.
Therefore, it can't be approved for the S3.

> Two things:
> 
> * On my test I have around 100 consecutive bytes every 200ms in the least busy moment

I tried changing the number of bits read and other parameters with no success - using the S3.

> * Could it be that on your configuration `Serial` is actually by default `HWCDC` (the usb one)

I always tested the baud detection using UART.
HWCDC has not such API, therefore it would never get compiled.

@imwhocodes  - If you have a working sketch that demonstrates this PR working correctly for any baud rate, please post it here with instructions on how to replicate the test case. I'll happily try it again.

**Comment by imwhocodes** [comment]
@SuGlider I asked about `HWCDC/USB` only to be sure (the sketch/example provided by you should compile also for both type of serial)

I will try your sketch and explore the the influence of the length of consecutive bytes

Also I check and in my code the operations that I do are:
1. `HardwareSerial::begin(9600, SERIAL_8N1, ... )`
2. `uartStartDetectBaudrate(uart_t)`
3. `uartStartDetectBaudrate(uart_t)`
4. `uartSetBaudRate(uart_t, unsigned long)`

(I'm not using `HardwareSerial::begin(0, .... )` simply because I want to have unlimited timeout in case of no uart connected yet, but as I said baud are correctly recognised)

**Comment by SuGlider** [comment]
Ok. Please provide a code example that I can test here.

**Comment by SuGlider** [comment]
> Also I check and in my code the operations that I do are:
> 
> 1. `HardwareSerial::begin(9600, SERIAL_8N1, ... )`
> 2. `uartStartDetectBaudrate(uart_t)`
> 3. `uartStartDetectBaudrate(uart_t)`
> 4. `uartSetBaudRate(uart_t, unsigned long)`

`uart_t *` isn't exposed by any Arduino API.
Maybe the code you used isn't Arduino Code, but some sort of modification.

This PR must work using only Arduino API from `HardwareSerial` class.

**Comment by imwhocodes** [comment]
@SuGlider I run some test yesterday and indeed your example don't work

Something strange is happening, if you call `HardwareSerial::begin(0 , ....)` baud rate detected is double the one the wire, like if the UART block is gated by **APB_CLK _(usually 80Mhz)_** and not by **XTAL_CLK _(40Mhz)_**

What I'm doing on my prod codebase is adding this function to `HardwareSerial` (in prod codebase I'm inheriting the class )
It is simply the core detection part from `HardwareSerial::begin`

```cpp
unsigned long HardwareSerial::detectBaudRate(const unsigned long timeout_ms) //timeout 0 for infinite timeout
{
    uartStartDetectBaudrate(_uart);

    unsigned long detectedBaudRate = 0;

    unsigned long start_detection = millis();

    while( ( ( ( millis() - start_detection ) < timeout_ms ) || timeout_ms == 0 ) && ( !( detectedBaudRate = uartDetectBaudrate(_uart) ) ) ){
        delay(1);
    };

    return detectedBaudRate;
}
```


And the with:

```cpp
#include <Arduino.h>
void setup() {
  Serial.begin(230400);
  Serial.println("\nTesting baud rate detection\n");
}

void loop() {
  Serial.println("Started detection for next 20 seconds.");
  Serial.println("Use the Serial Monitor. Change the baud rate in the botton of the window.");
  Serial.println("Send characters using the Serial Monitor and get the detected baud rate.");
  Serial.flush();

  unsigned long detectedBaudRate = Serial.detectBaudRate(20000);
  // unsigned long detectedBaudRate = Serial.baudRate();


  if (detectedBaudRate) {
    Serial.updateBaudRate(detectedBaudRate);
    Serial.printf("\nDetected baudrate is %lu\n\n", detectedBaudRate);
  } else {
    // Serial.updateBaudRate(115200);
    // this may not display correctly in the Serial Monitor, given that it failed.
    Serial.println("\nNo baudrate detected, Serial will not work!\n\n");
  }
}
```

**And baud rate is correctly detected**

Strange thing is that it keep detecting (seem like hardware register with values for detection are not cleared)

**Comment by SuGlider** [comment]
>Strange thing is that it keep detecting (seem like hardware register with values for detection are not cleared)

Yes, this is one of the issue I also noticed with the S3. 
It nevers recover whenever `autodetect is set to 1`, even when it is set back to 0.

I also am not able to detect correctly baud rates under 38400. 
It always reports wht wrong baud rate.

**Comment by VojtechBartoska** [comment]
@imwhocodes CLA is still not signed, I am adding this to 3.0.0 milestone so it will get resolved.

**Comment by imwhocodes** [comment]
> @imwhocodes CLA is still not signed, I am adding this to 3.0.0 milestone so it will get resolved.

First commit has be signed with a wrong username for which it cannot be signed
Also I remember later I found some problem where baud-detection didn't work if serial was restarted (seem like is was changing the clock used as peripheral input)

I will write and test again this commit

**Comment by lucasssvaz** [comment]
> > @imwhocodes CLA is still not signed, I am adding this to 3.0.0 milestone so it will get resolved.
> 
> First commit has be signed with a wrong username for which it cannot be signed Also I remember later I found some problem where baud-detection didn't work if serial was restarted (seem like is was changing the clock used as peripheral input)
> 
> I will write and test again this commit

Just do a soft reset and commit with the right account

**Comment by Jason2866** [comment]
Is the auto detection working now and if yes for all speeds too?
If not the PR should imho be changed to draft.

**Comment by imwhocodes** [comment]
> Is the auto detection working now and if yes for all speeds too? If not the PR should imho be changed to draft.

It should, I wanted to write before but i didn't had time yet
It run (on production) on some of my project, I will run a new test suite on it and come back with a final PR

**Comment by imwhocodes** [comment]
**Master** branch do not compile (on platformIO) so I based my test on top of **v2.0.14**

Next week I will clean up the code and do more tests (now it work but btw)

Here is a code snippet that I used to test the auto-baud function:

```c++
#define NO_GLOBAL_SERIAL

#include <Arduino.h>

HardwareSerial log_stream = HardwareSerial(0);
HardwareSerial snd_serial = HardwareSerial{1};
HardwareSerial rcv_serial = HardwareSerial{2};



const unsigned long default_rates[] = {
                                            4800,
                                            9600,
                                            19200,
                                            38400,
                                            57600,
                                            74880,
                                            115200,
                                            230400,
                                            256000,
                                            460800,
                                            921600,
                                            1843200,
                                            3686400
                                          };

#define ARRAY_SIZE(arr)     (sizeof(arr) / sizeof((arr)[0]))


TaskHandle_t parse_task;
TaskHandle_t send_task;


void sendTask(void *pvParameters){

  delay(5000);

  while(true){
    const auto & rate = default_rates[random(0, ARRAY_SIZE(default_rates) - 1)];

    log_i("SND opening with: %d bauds", rate);

    snd_serial.begin(rate, SERIAL_8N1, 0, 1, false);

    const size_t qty = random(64, 128);

    // log_i("SND will send: %d bytes", qty);

    for(size_t i = 0; i < qty; i++){

      const uint8_t r = random();
      snd_serial.write(r);
      // log_stream.printf("SND: %02X\n", r);
    }

    snd_serial.flush();
    snd_serial.end();

    log_i("SND Closed");
    delay(10000);
  }

}



void parseTask(void *pvParameters){

  delay(5000);

  while(true){
    rcv_serial.begin(0, SERIAL_8N1, 45, 46, false, 20000);

    const auto rate = rcv_serial.baudRate();

    if(rate){
      log_i("RCV opening with: %d bauds", rate);
    }
    else{
      log_i("RCV FAILED DETECTION!!!");
    }

    delay(2500);
  }

}

void setup() {

    log_stream.begin(921600);

    delay(100);
    while (!log_stream)
    {
      delay(100);
    }
    
    log_stream.setDebugOutput(true);

    log_i("!INIT!");

    log_i("Connected!");

  	assert( pdPASS ==
      xTaskCreatePinnedToCore(
                  sendTask,        /* Function to implement the task */
                  "sendTask",      /* Name of the task */
                  1024 * 4,                 /* Stack size in bytes */
                  NULL,                     /* Task input parameter */
                  5, /* Priority of the task */
                  &send_task,     /* Task handle. */
                  PRO_CPU_NUM      /* Core where the task should run */
      )
	  );

  	assert( pdPASS ==
      xTaskCreatePinnedToCore(
                  parseTask,        /* Function to implement the task */
                  "parseTask",      /* Name of the task */
                  1024 * 4,                 /* Stack size in bytes */
                  NULL,                     /* Task input parameter */
                  5, /* Priority of the task */
                  &parse_task,     /* Task handle. */
                  APP_CPU_NUM               /* Core where the task should run */
      )
	  );
    log_e("Task Created:\t%d", millis());
}




void loop() {
  vTaskDelete(NULL);
}
```

**Comment by imwhocodes** [comment]
About the detection of seem like there is something broken on [the original rounding algorithm](https://github.com/espressif/arduino-esp32/pull/7782/files#diff-3d9c6876ed404db1b65230f87978c06285493ebaba9ceac1d2f45446f8cf8a87R816-R835)

As you can see from this log:
```
SND opening with: 1843200 bauds
[  5759][E][main.cpp:162] setup(): Task Created:        5759
SND will send: 1018 bytes
[  5760][I][esp32-hal-uart.c:655] uartBaudrateDetect(): rxd_edge_cnt = 46 lowpulse_min_cnt = 9 hightpulse_min_cnt = 10
[  5761][V][esp32-hal-uart.c:830] uartDetectBaudrate(): Rounded 2222222 to      3686400
[  5762][V][esp32-hal-uart.c:831] uartDetectBaudrate(): From Previous   ( 1843200 )     :       ( 379022 )
[  5763][V][esp32-hal-uart.c:832] uartDetectBaudrate(): From Current    ( 3686400 )     :       ( 1464178 )
[  5764][V][esp32-hal-uart.c:833] uartDetectBaudrate(): From Next       ( 1953653109 )  :       ( 1951430887 )
SND Finished
RCV FAIL        3699421 is not  1843200
```
2222222 get rounded to 3686400 even if:

```
abs(1843200 - 2222222) = 379022
abs(3686400 - 2222222) = 1464178
```

**Comment by OpenUAS** [comment]
@imwhocodes Your work is really appreciated in the sad state of affair of Espressif S3/C3 autobauding. A finalized PR welcomed, can validate on all ESP32 MCU if still needed.

**Comment by SuGlider** [comment]
@imwhocodes - I think that it will be necessary to rebase this PR. 
There 100 commits and the mergeable content doesn't match the PR objective.

**Comment by Jason2866** [comment]
@imwhocodes You can use branch master with Platformio using this PR https://github.com/platformio/platform-espressif32/pull/1281

**Comment by SuGlider** [comment]
>I will rebase the commit, it is not ready to be merged anyway (currently is rebased on v2.0.14)
>@SuGlider I can't change the target branch for the PR (current is master), I would like to be include in the future v2.0.15

@imwhocodes - This PR should be use `release/v2.x` as branch, not `master`. This will make it merge against future Core v2.0.15.

I have run exaustive testing and  also I have checked ESP32-S3 and ESP32-C3 datasheet and TRM.
My conclusions are:
-  Baudrate detection only works when UART source clock is XTAL. It doesn't work correctly when using APB (this is a problem for Arduino Core 3.0.0 because it sets APB by default).
- S3 and C3 has a 12 bits resolution, therefore, it can detect only more than 9600 bps when using XTAL. 
- The best baudrate calculation is XTAL Freq 40MHz / (Negative Pulse Count + 1)

In order to get the Negative Pulse Count, the code shall use `uart_ll_get_neg_pulse_cnt(uart_dev_t *hw)`

### additional note:
I found a couple issues when the APB Freq is lower than 80MHz - ESP32 and ESP32-S2.
Therefore, I have created anther PR rebased to be merged to 2.0.15.
I'll try to find a solution for Arduino Core 3.0.0, considering that it uses APB as UART CLK SOURCE for the S3 and C3.

Please check PR https://github.com/espressif/arduino-esp32/pull/9261 - This works for 2.0.14

**Comment by lucasssvaz** [comment]
Closing this in favor of #9261. If you find a solution for 3.0.0, please open a new PR.

**Pull request closed without merging**
