### PR TITLE
add callback to HTTPUpdate

### PR DESCRIPTION
**Pull request by jayanta525**
- add callback function to HTTPUpdate
- update example to print progress
- fix ArduinoIDE syntax coloring
- reference:  [ESP8266httpUpdate](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266httpUpdate)

```
CALLBACK:  HTTP update process started
CALLBACK:  HTTP update process at 0 of 365728 bytes...
CALLBACK:  HTTP update process at 0 of 365728 bytes...
CALLBACK:  HTTP update process at 4096 of 365728 bytes...
```

Signed-off-by: Jayantajit Gogoi <jayanta.gogoi525@gmail.com>

### CODE REVIEW

**Comment by me-no-dev** [comment]
Thanks @jayanta525 :)

**Comment by jayanta525** [comment]
@epiller I tested with the latest release 2.0.0, and the example compiled without any errors on ArduinoIDE. 

Please make sure you're using the correct src and header files.

You can turn on verbose output during compilation in ArduinoIDE and check whether the compiler is using the correct `HTTPUpdate.cpp`

**Comment by jayanta525** [comment]
@epiller You can add the HTTPUpdate library from this repo to `lib/` folder in PlatformIO project directory. 

And edit platformio.ini to ignore the built-in library.
`lib_ignore = HTTPUpdate`

```
lib_extra_dirs =
    lib/
```

https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-extra-dirs

And don't forget to set ldf_mode
https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-ldf-mode

**Comment by epiller** [comment]
@jayanta525 That solved it and it's fully working now! Thank you so much man!

**Pull request merged**
