### PR TITLE
fix(webserver): Proposal for simplifying webserver file uploads via form POST.

### LINKED ISSUE #9163: WebServer file upload fails when file ends with "--\r\n".
### Board

n.a.

### Device Description

n.a.

### Hardware Configuration

n.a.

### Version

latest master (checkout manually)

### IDE Name

n.a.

### Operating System

n.a.

### Flash frequency

n.a.

### PSRAM enabled

yes

### Upload speed

n.a.

### Description

When the file to upload ends with the string "--\r\n" (e.g. SSL cert files with windows line endings) the WebServer resets the connection before the upload is complete.

I guess the problem is somewhere here: https://github.com/espressif/arduino-esp32/blob/master/libraries/WebServer/src/Parsing.cpp#L353-L524

### Sketch

```cpp
n.a.
```

### Debug Message

```plain
n.a.
```

### Other Steps to Reproduce

n.a.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by everslick**
~The form parser has been shown to have issues with files ending with "--\r\n".~ This commit replaces the form parser with the parser from ESP8266, which is simpler and easier to reason about.

### CODE REVIEW

**Comment by everslick** [comment]
The **_uploadReadByte()** method should be also be replaced with this implementation from ESP8266:

```
int WebServer::_uploadReadByte(WiFiClient& client){
  int res = client.read();

  if (res < 0) {
    while(!client.available() && client.connected())
      delay(2);

    res = client.read();
  }

  return res;
}
```

**Comment by lucasssvaz** [comment]
> The **_uploadReadByte()** method should be also be replaced with this implementation from ESP8266:
> 
> ```
> int WebServer::_uploadReadByte(WiFiClient& client){
>   int res = client.read();
> 
>   if (res < 0) {
>     while(!client.available() && client.connected())
>       delay(2);
> 
>     res = client.read();
>   }
> 
>   return res;
> }
> ```

Could you also add this to this PR ?

**Comment by everslick** [comment]
Done.

**Comment by lucasssvaz** [comment]
Thanks, I'll test everything and get back to you

**Review by P-R-O-C-H-Y — APPROVED** [review]
Looks good. Tested with WebServer example "FSBrowser".

**Pull request merged**
