### PR TITLE
Create ledcWrite_RGB.ino

### PR DESCRIPTION
**Pull request by vseven**
adding the public domain example ledcWrite_demo_ESP32.ino to this repo.  Added RGB to the name for people searching, added some comments, and renames things to make a bit more sense.

### CODE REVIEW

**Comment by me-no-dev** [comment]
Ah I thought I commented on this... :D 

Please rename the demo to ledcWrite_RGB :) it's in examples of ESP32 so "demo" and "ESP32" are redundant here

**Comment by vseven** [comment]
Should be fixed.

**Comment by me-no-dev** [comment]
Oh I meant rename the folder/file as well :) else that long name will show in the menu

**Comment by vseven** [comment]
You make it seem like I know what I'm doing.  Haha.  I think I got it...had to google how to rename a commit, figured it out.

Also unrelated but my ESP32 is still rebooting 5 - 10 times a day and I haven't heeard from the wifi guy.  Want to use it for lights (RGB LEDs....go figure) and can't really ahve them turning off and on so if you have any other ideas on that (#653) let me know.

**Comment by me-no-dev** [comment]
I will poke again on the issue and see to get an answer :)

**Pull request merged**
