### PR TITLE
Adds HardwareSerial::setTxBufferSize()

### PR DESCRIPTION
**Pull request by gonzabrusco**
## Summary

It adds HardwareSerial::setTxBufferSize() with default value of 0 bytes (like it is now by default).
No issue related. Just adds functionality to HardwareSerial. Allows non blocking writes when they exceed the TX FIFO.

## Impact
None.

## Related links
It allows to define a Tx Buffer Size for UART, before begin().

### CODE REVIEW

**Comment by SuGlider** [comment]
Thanks @gonzabrusco !
I'll review it soon.

**Review by SuGlider — APPROVED** [review]

**Comment by SuGlider** [comment]
@gonzabrusco - This is a nice improvement! Thanks!

>Allows non blocking writes when they exceed the TX FIFO.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/uart.html#_CPPv416uart_write_bytes11uart_port_tPKv6size_t

Based on your PR, this is exactly the intended behaviour.

**Comment by SuGlider** [comment]
@gonzabrusco 

I just tested it with the example below and I got ASSERT error.

```cpp
void setup() {
  Serial.setTxBufferSize(64);
  Serial.begin(115200);
}

void loop() {
}
```

## Error message with the ESP32-S2:

```
Rebooting...
ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x400262e1
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x510
load:0x4004c000,len:0xa50
load:0x40050000,len:0x28bc
entry 0x4004c18c
E (91) uart: uart_driver_install(1529): uart tx buffer length error
ESP_ERROR_CHECK failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x4002927c
file: "C:\Users\rocor\Documents\Arduino\hardware\espressif\esp32\cores\esp32\esp32-hal-uart.c" line 166
func: uartBegin
expression: uart_driver_install(uart_nr, 2*rx_buffer_size, 2*tx_buffer_size, 20, &(uart->uart_event_queue), 0)

abort() was called at PC 0x4002927f on core 0


Backtrace:0x400262b6:0x3ffc65b00x40029289:0x3ffc65d0 0x4002dcd5:0x3ffc65f0 0x4002927f:0x3ffc6670 0x40082042:0x3ffc6690 0x40081362:0x3ffc66f0 0x40080feb:0x3ffc6730 0x40081b72:0x3ffc6760 




```

**Comment by SuGlider** [comment]
@gonzabrusco - already commited necessary changes to the code.

**Comment by gonzabrusco** [comment]
> @gonzabrusco - already commited necessary changes to the code.

Thanks @SuGlider !! I was about to check the error and noticed you were working on it (because of the commit after the comment). Thanks for helping me push this pull request (my first by the way!).

**Review by SuGlider — APPROVED** [review]
Added 2 commits to comply with IDF requirements and avoid the issue commented in this PR.

**Comment by SuGlider** [comment]
> > @gonzabrusco - already commited necessary changes to the code.
> 
> Thanks @SuGlider !! I was about to check the error and noticed you were working on it (because of the commit after the comment). Thanks for helping me push this pull request (my first by the way!).
> 
> I appreciate you removed the double buffer thing. I did not undestand that decision but I kept it like that because I thought that was an "Espressif thing". But now for me it makes perfect sense.

Thanks! Congratulations for your first PR!
I hope it will be the first of many!

**Comment by SuGlider** [comment]
@me-no-dev  - I have fininshed my review. 
Ready for merging, after your final review.

**Pull request merged**
